### ISSUE TITLE
Progress of CoverageJSON standardisation in WCS SWG/DWG

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#132]
Currently awaiting a draft specification document based on the original CoverageJSON work at Reading University.
ALso we links to JSON-LD1.1 and GeoJSON developments

**Comment by chris-little** [comment]
Contract to draft a candidate specification of CoverageJSON as a OGC standard has started. CoverageJSON community is informed and willing to review progress and deliverables.
This issue kept open to track progress

**Comment by KathiSchleidt** [comment]
Are there any ambitions on aligning this with existing work in OGC on Coverages? At present, while CovJSON makes various claims on CIS, seems this was done without reading the standard, details at https://github.com/covjson/specification/issues/91

**Comment by chris-little** [comment]
@KathiSchleidt Yes there are `ambitions on aligning this with existing work on OGC  on Coverages`. That is why the work was placed into the Coverage SWG plan of work in their new charter.

I note that you have evoked a committment from Reading University to update the misleading documentation at covjson/specification#91 . Some of the existing incompatibilities are a consequence of CoverageJSON using JSON-LD V1.0. to avoid response payloads burdened with metadata.

I envisaged that there perhaps would be a two stage approach, or perhaps two conformance classes: compatibility with the existing implmentations 'in the wild', then another version, hopefully backwardly compatible for the implementations and consistent or compatible with OGC WCS/CIS standards, and JSON-LD V1.1.  This would give the community implementations a development path.

An option that the OGC Staff have just suggested is that CoverageJSON is proposed as a community standard, and then convergence can be developed later. This has the advantage of allowing the WCS SWG to concentrate on the API-Coverage work now.

**Comment by chris-little** [comment]
Various CoverageJSON stakeholders and software developers have stated they are supportive of the OGC Community Standard approach.

**Comment by chris-little** [comment]
EDR API SWG 42 agreed to close issue
