### ISSUE TITLE
Links in table 1 point to github

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-environmental-data-retrieval#156]
Currently point to the EDR github. Should they point to sections of the spec document?

**Comment by chris-little** [comment]
@dblodgett-usgs See 6.7.5 "During the development phase, these components use a base URL of https://github.com/opengeospatial/Environmental-Data-Retrieval-API/master, but eventually they are expected to be available under the base URL http://schemas.opengis.net/ogcapi-edr-1/1.0. "

@ghobona I expect these to corrected by OGC staff as part of the publishing process.

**Comment by chris-little** [comment]
PR now merged

**Comment by ghobona** [comment]
@chris-little Yes, those can be fixed by OGC staff.

**Comment by chris-little** [comment]
Agreed in SWG 36 to be done in next PR by @m-burgoyne

**Comment by chris-little** [comment]
PR #165 incorporated
