### ISSUE TITLE
"Environmental Resources" link in section 8.1 is broken...

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-environmental-data-retrieval#160]
Not clear what that is supposed to go to.

"Environmental Resources: operations for accessing environmental data resources"

Also, I'm not quite sure what the distinction is between Collection Access and Environmental Resources. Can we just drop "Environmental Resources"?

**Comment by chris-little** [comment]
@m-burgoyne will remove 8.1 bullet 3 completely

**Comment by chris-little** [comment]
PR #165 incorporated
