### ISSUE TITLE
Table 2 missing Radius

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#163]
@m-burgoyne Is Radius subsumed in Point, or can it be invoked with its own path /{collectionId}/radius? ...

There does not seem to be an example of how to invoke a point with a radius.

**Comment by m-burgoyne** [comment]
@chris-little  Radius is invoked with it's own path

**Comment by chris-little** [comment]
PR created

**Comment by chris-little** [comment]
We need an example

**Comment by chris-little** [comment]
PR #165 incorporated
