### ISSUE TITLE
Data query's metadata

### ISSUE THREAD

**Issue by iandruska-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#166]
Currently, the list of supported output formats is advertised at the collection/instance level. So there is one list which applies to all data queries.

However, the output format applicability actually depends on the data query. For instance, GRIB is applicable to Area/Area/Cube/Corridor queries but not for Position/Trajectory.

Therefore, the list of output formats should be a property of data query. This implies a separate metadata section for each data query. For example, https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T000000Z:

```
{
  "id": "20201203T000000Z",
  "title": "2020-12-03T00:00:00Z",
  "links": [
    {
      "href": "https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T000000Z",
      "rel": "self",
      "type": "application/json",
      "title": "2020-12-03T00:00:00Z"
    }
  ],
  "dataQueries": [
    {
      "id": "position",
      "title": "Position Query",
      "description": "Data at point location",
      "links": [
        {
          "href": "https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T000000Z/position",
          "rel": "data",
          "title": "Position Query"
        }
      ],
      "outputFormats": [
        "CoverageJSON",
        "KML",
        "NetCDF3",
        "NetCDF3float",
        "NetCDF4",
        "NetCDF4float"
      ],
      "defaultOutputFormat": "CoverageJSON"
    },
    {
      "id": "cube",
      "title": "Cube Query",
      "description": "Data within 4D cube",
      "links": [
        {
          "href": "https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T000000Z/cube",
          "rel": "data",
          "title": "Cube Query"
        }
      ],
      "outputFormats": [
        "GRIB",
        "GRIB2",
        "CoverageJSON",
        "JSON",
        "GeoTIFF",
        "GeoTIFFfloat",
        "KML",
        "NetCDF3",
        "NetCDF3float",
        "NetCDF4",
        "NetCDF4float"
      ],
      "defaultOutputFormat": "GRIB2"
    },
    ...
...
```

**Comment by m-burgoyne** [comment]
Currently there is no defined output when queries are specified without query parameters, so another approach would be to return query specific metadata when the query is specified without any query parameters.
i.e. 
https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T000000Z/position
could return
```json
{
      "id": "position",
      "title": "Position Query",
      "description": "Data at point location",
      "links": [
        {
          "href": "https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T000000Z/position",
          "rel": "data",
          "title": "Position Query"
        }
      ],
      "outputFormats": [
        "CoverageJSON",
        "KML",
        "NetCDF3",
        "NetCDF3float",
        "NetCDF4",
        "NetCDF4float"
      ],
      "defaultOutputFormat": "CoverageJSON"
    }
```

https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T000000Z/cube

could return
```json
{
    "id": "cube",
    "title": "Cube Query",
    "description": "Data within 4D cube",
    "links": [
      {
        "href": "https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T000000Z/cube",
        "rel": "data",
        "title": "Cube Query"
      }
    ],
    "outputFormats": [
      "GRIB",
      "GRIB2",
      "CoverageJSON",
      "JSON",
      "GeoTIFF",
      "GeoTIFFfloat",
      "KML",
      "NetCDF3",
      "NetCDF3float",
      "NetCDF4",
      "NetCDF4float"
    ],
    "defaultOutputFormat": "GRIB2"
}
```
This could also include query specific metadata and links to information such as interpolation methods.

**Comment by iandruska-ibl** [comment]
I do not feel 100% comfortable about this approach for at least two reasons:
1. If collection metadata does not contain list of data queries, then I don't know which queries are actually implemented.
2. Data query endpoint represents two different resources: sampled data and query metadata. Better in my opinion would be something like /position/metadata.

**Comment by m-burgoyne** [comment]
The links section of the collection metadata contains a list of the queries supported by the collection

**Comment by iandruska-ibl** [comment]
But how do I know that the link represents a data query? For example, I implement a new query called /spiral as my custom extension. How do I indicate in the links section that the /spiral endpoint represents is a data query?

**Comment by m-burgoyne** [comment]
The `rel` and `type` properties can be used to differentiate between query URL' and metadata URL's.   The result of a query generates an item from the collection so in theory the `item` relation could be used and the type parameter could be the query type (i.e. Position, Area etc)

**Comment by iandruska-ibl** [comment]
There are actually two problems:
1. Indication that a link represents a data query (so the client code can automatically discover data queries)
2. Differentiation between query and metadata links

**Problem 1:**
If I understand correctly, you are suggesting that the problem 1 can be solved by putting "Position" or "Area" into the `type` property. I believe, that this would be a misuse of the `type` property. The `type` property should be a media (MIME) type (Or at least, it typically is; I have never seen a different use). It indicates the format of the response. Irreplaceable when service is able to produce metadata in different formats.

Even if I put "Position" into the `type` property, It does not solve the problem. Client code still cannot tell that the link represents a data query.

**Problem 2:**
If we agree that the `type` property can only indicate the response format, we are left with the `rel` property only. For example:
```
"links": [
  {
    "href": "https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T060000Z/position",
    "rel": "item",
    "title": "Position Query - Data"
  },
  {
    "href": "https://ogcie.iblsoft.com/edr/collections/gfs-agl/instances/20201203T060000Z/position",
    "rel": "metadata",
    "title": "Position Query - Metadata"
  },
],
```
(I could not find a suitable link relation for the metadata link, so I made one up)

Confusing thing is that both URLs respond with a metadata document. This is a consequence of the fact I mentioned earlier, that the data query endpoint represents two different resources.

**Comment by m-burgoyne** [comment]
I suspect that we may need to use `rel` values which are not in the IANA definitions, but I believe that the terms `data` and `metadata` are easy to comprehend.  I agree that if we want to take that approach we MUST not confuse data and metadata end points so I am not opposed to your original suggestion and it also has the added benefit of reducing the number of requests that a client has to make to identify the capabilities supported by the query.

**Comment by iandruska-ibl** [comment]
I think that the data queries are in this aspect analogical to instances. Collections advertise their instances explicitly in the metadata:
```
{
   "instances" : [
   ]
}
```

Even with instances, we could rely solely on the collections' `links` property, but client would be left guessing which link actually represent an instance and which represent a data query (or potentially other EDR objects in the future). Listing both explicitly in the collections' metadata, solves the problem:

```
{
   "instances" : [
     {
       "id": "2020-12-03T00:00:00Z",
       "links": [
       ]
     }
   ],
   "dataQueries" : [
     {
       "id": "position",
       "links": [
       ]
     }
   ]
}
```

**Comment by iandruska-ibl** [comment]
I agree, that using custom link relation types ("collection", "instance", "data-query", "data-query-metadata"), as you proposed, is another valid solution. But I prefer to be consistent with the existing concepts, such as the instance list.

**Comment by chris-little** [comment]
@iandruska-ibl @m-burgoyne I have just noticed this text in OGC API-Features-Part 2: CRS by Reference, which, I think, is basically the approach advocated by @m-burgoyne:
`To prevent unnecessary duplication of lists of supported CRS identifiers in the collection object, a global list of supported CRS identifiers may be provided as part of the collections object.
This global list of CRS identifiers is not automatically inherited by each collection offered by the service. Rather the global list of CRS identifiers must be explicitly referenced in the crs property of the collection object using a JSON Pointer (RFC 6901).`

**Comment by iandruska-ibl** [comment]
@chris-little If I understand correctly, the paragraph from API-Features is solely about preventing duplication. My approach suffers from duplication too. The metadata about data queries (quite lengthy) are repeated in every collection. The JSON pointer solution would work in my case as well.

**Comment by chris-little** [comment]
My summary of #166: list of supported output formats `f` is advertised at the collection/instance level. So there is one list which applies to all data queries. 

Q: The output format applicability depends on the data query. E.g. GRIB is applicable to Area/Area/Cube/Corridor queries but not Position/Trajectory. Therefore, the list of output formats should be a property of data query, with a separate metadata section for each data query
A: one could use GRIB for a single position value. Not good practice, but possible. If feasible for Corridor, then also as edge case for trajectory. So stay with f defined at collections/collection/ level.

Q: Should API return query specific metadata when the query is specified without any query parameters? Then data query endpoint represents two different resources: sampled data and query metadata. Something like /position/metadata would be better.
A: Links section of the collection metadata contains a list of the queries supported by the collection

Q: If the type property can only indicate the response format, we are left with the rel property only. 
A: May need to use `rel` values which are not in the IANA definitions, but I believe that the terms data and metadata are easy to comprehend. We MUST not confuse data and metadata end points

Q: Collections advertise their instances explicitly in the metadata. Could use Collection's links property, but client would be left guessing which links actually represent instances and which represent data queries (or potentially other EDR objects)
A: Listing both Links and DataQueries explicitly in the collection's metadata solves the problem

Q: How to Indicate that a link represents a data query, so the client code can automatically discover data queries, including extensions, such as "spiral" or "plume".
A: Do not use type property. But could use custom link relation types ("collection", "instance", "data-query", "data-query-metadata"), but not consistent with the existing instance list.

Q: How to differentiate between query and metadata links
A: ?

**Comment by chris-little** [comment]
@m-burgoyne @iandruska-ibl I am not sure is this will be helpful. For link relations, IANA has defined: 

`service-desc Identifies service description for the context that is primarily intended for consumption by machines.`   
`service-doc  Identifies service documentation for the context that is primarily intended for human consumption.`
`service-meta Identifies general metadata for the context that is primarily intended for consumption by machines.`

But also, the OGC Naming Authority is proposing to define a link relation: `data-meta` for metadata about data. Of course, nobody has implemented this, and in the future, web developers may not.

**Comment by chris-little** [comment]
EDR API SWG 49 close when PR mergeed
