### ISSUE TITLE
Intended use of the EDR API standard?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-environmental-data-retrieval#169]
I had a look at the draft that is in the TC approval process now to check some implementation requirements and have a few questions:

* As a client, how do I determine which observable properties I can request in `parametername`? My understanding from the current document is that I cannot and I have to consult API-specific documentation. 
  * Annex C has an example where those are listed in the Collection resource, but there is no normative text about this nor any discussion of the example, the schema or the semantics.
  * I also looked at the OpenAPI example (btw, the links are broken in the document, but I found the files in the GitHub repo), but `parametername` does not list the allowed values as enums, so I assume this is also not the intended way to advertise the observable properties.
* Likewise, there are no requirements for the content of the responses to `/collections/{collectionId}/instances` and `/collections/{collectionId}/instances/{instanceId}`, so using these resources will also require consulting the API documentation.

Is this correct and the goal is that clients will typically be API-specific or am I missing something?

**Comment by m-burgoyne** [comment]
The available parameters are listed in the collection and instance responses, with each collection/instance advertising the data 
 parameters they support and their units (and if appropriate the time duration they represent) . These responses are described by OpenAPI schemas but the documentation needs to be updated to clearly describe this to users.   

The intention is the clients should not be API specific, the concept is the data publisher ensures that their responses fit the advertised query patterns.

**Comment by cportele** [comment]
@m-burgoyne - thanks for the clarification, but now I am even more confused. Isn't the candidate standard already in the approval vote, i.e. outside of the control of the SWG? How can the document be changed at this stage, in particular the normative text?

**Comment by m-burgoyne** [comment]
@cportele Sorry, the intention is to improve the documentation in the next release

**Comment by cportele** [comment]
OK, understood. So generic clients will have to wait for version 1.1 or 2.0 (which I find surprising). This includes CITE tests, too, since there is no way to reliably determine the valid parameters that can be used in a request.

**Comment by KathiSchleidt** [comment]
while I can intuit how a client could parse the collection landing page to find the parameters section, I'm at a loss as to how the client will then parse the content of this section. Is the assumption that potential clients are aware of the parameter encoding utilized by the provider, or does this step depend on manual inspection of the JSON?

**Comment by chris-little** [comment]
@cportele A lot of the improvements to the documentation will not affect the normative document. We envisage, and have already started, developing better examples and informative material on the GitHub repo. This does not need a new release.

**Comment by chris-little** [comment]
@KathiSchleidt `Is the assumption that potential clients are aware of the parameter encoding utilized by the provider, ` If the serivce says the data will be returned in JSON, or NetCDF or GeoTIFF, surely the client can either process it or hand off the payload to something that could? The payload containers contain the information. If a perverse or unthinking service provider chose some obscure backwater approach inside GeoTIFF, it could cause the client problems, but not a good idea if you wnat people to use your service. Does that answer the concern?

**Comment by ghobona** [comment]
Work is [on-going](https://github.com/opengeospatial/ets-ogcapi-edr10/blob/master/teststatus.adoc) on the ETS.

**Comment by cportele** [comment]
@chris-little - Unless I am missing something, I do not see how to fix the issue without changes to the normative statements. Currently there are, for example, no normative statements related to anything in the responses to `/collections` or `/collections/{collectionId}` beyond what Common specifies. So all the content that has been added in the example in annex C.5 is currently not part of the API and no client can or should expect that such content is available. 

I can deploy a very simple API that conforms to the spec, has nothing of the content in C.5 and that requires out-of-band information to use. 

With respect to the CITE tests or any other client, how could they, for example, submit valid query requests to that hypothetical API, if the client cannot determine which parameter names are supported?

**Comment by ghobona** [comment]
@cportele Regarding the `parameter-name` parameter, I see similarities to the `filter` parameter in OGC API - Features - Part 1: Core. Needing to refer to API documentation does not prevent the API from being usable.

**Comment by cportele** [comment]
@ghobona - I did not say that the API would not be usable, if one has to consult the API documentation, it is just not possible to write a generic client, which is ok, depending on the intent.

However, from a CITE perspective, some parts won't be testable, since the ETS cannot "parse" the documentation. Or the CITE test needs parameters to provide the missing information that cannot be determined from the API definition or the API itself.

I think the situation is different with the `filter` parameter (defined in Part 3, not Part 1). The aspects of a filter expression that depend on the server are available through additional resources (mainly queryables, functions), so clients are able construct valid queries (with reading the API documentation).

**Comment by KathiSchleidt** [comment]
@chris-little - to your answer on `Is the assumption that potential clients are aware of the parameter encoding utilized by the provider,` - fear you misunderstood me. I've understood that EDR is data model agnostic on the result payload, clients shall sort whatever they get and get on with things. 

What I was referring to is what is presented on the collection landing page, currently only described in `C.4. Collections Metadata Examples`, that the client must use to determine if the required parameters are being provided by the API endpoint. I fail to see how a client can automatically determine if data for a specific concept, e.g. http://codes.wmo.int/common/quantity-kind/_windDirection, is being provided. Parse through all attributes of the parameter object to see if the concept is contained?

**Comment by chris-little** [comment]
@cportele @KathiSchleidt What we have built with the API - EDR is a framework, that allows a very simple generic client to retrieve what parameter-names are available, along with the API-Common information. If the service provider has decided that in their collections, the 'parameter-names' that can be retrieved are 海水温度 or 土壤温度, that is reasonable. The generic client has to present this to some other intelligence to decide what to do.
I think it too early or inappropriate to mandate which vocabularies should be used in which domain. The EDR approach is similar to retrieving a map from a WMS - having specified an area of interest, I still have to use a legend to select what layers are presented.

I agree that future work which would allow a user to specify a topic of interest and then the client goes and finds and retrieves it is worth pursuing. This is just the first step in that direction. The current demonstration implementations present the areas, levels and times of available `parameter-names` for chosen query patterns. We are now actively working with the API-Records group to improve interoperability across many domains of the metadata, and meta-metadata, that should enable more sophisticated use.

**Comment by cportele** [comment]
@chris-little - This discussion seems to be just going in circles. While you say that

> EDR is a framework, that allows a very simple generic client to retrieve what parameter-names are available

I opened this issue, because I do not see how this is the case. EDR as currently specified does not specify how servers expose the available parameters and so generic clients cannot retrieve this information. 

Anyway, I think I got an answer to my question. Feel free to close the issue.

**Comment by chris-little** [comment]
@cportele  does @iandruska-ibl reply at https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/179#issuecomment-770172601 answer your question?

I suppose by the term 'generic client' I meant a gneric API-EDR client, rather than a generic API-Features or API-Coverages client.

**Comment by cportele** [comment]
@chris-little - No, I do not see how it is an answer. That "EDR parameter description" is not part of the candidate EDR API standard. From your question I assume that the candidate standard was meant to specify how parameters are declared using this schema, but this has not happened. The same is then probably the case for other parts that seem underspecified, like the instances query.

> I suppose by the term 'generic client' I meant a gneric API-EDR client, rather than a generic API-Features or API-Coverages client.

Me too.

**Comment by ghobona** [comment]
@chris-little @cportele 

I envisage a similar journey for the EDR API as that of OGC API - Features - Part 1: Core. After a period of implementation and use of the specification after approval as a standard, the SWG can develop an Editor's Draft that later leads to a Corrigendum. We now list the Editor's Draft on the [OGC API - Features webpage](https://www.ogc.org/standards/ogcapi-features) alongside the approved standard. The difference between the documents is logged in the [Revision History](http://docs.opengeospatial.org/DRAFTS/17-069r4.html#_revision_history).

I recommend that the EDR API SWG maintains a log of changes after approval of the spec, so that a Corrigendum can be developed in the future if necessary.

**Comment by cportele** [comment]
@ghobona 

A corrigendum should not break existing implementations and should not introduce new capabilities. None of the changes in the Editor's Draft of Features Core makes existing implementations invalid and no new capabilities are introduced. 

This would be different, if EDR, for example, later adds a Core requirement to add information about parameters to the Collection resource, which would break implementations. This would be a major revision.

**Comment by cportele** [comment]
As mentioned earlier, I think the issue has been discussed and since the candidate standard is now in the approval vote, this is in a way "overcome by events". I am closing this issue.

**Comment by chris-little** [comment]
My summary of this issue #169: How does a client determine which observable properties can be requested of parameter-name? 
1. Consult API-specific documentation.
2. Annex C has example where parameter-name observable properties are listed in the Collection resource, but no normative text, discussion of the example, the schema or the semantics.
3.  The OpenAPI example `parameter-name` does not list the allowed values as enums, so I assume this is also not the intended way to advertise the observable properties.
4. No requirements stated for the content of responses to /collections/{collectionId}/instances and /collections/{collectionId}/instances/{instanceId}, so using these resources will also require consulting the API documentation.

A: YAML indicates properties of parameter-name via links to other info.
