### ISSUE TITLE
adjust query parameters to be kebab-case

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#170]
Related to https://github.com/opengeospatial/ogcapi-coverages/issues/23, it would be valuable to align our query parameters that are camelCase to be kebab-case 🍢.  Some examples:

- `corridorWidth` -> `corridor-width`
- `corridorHeight` -> `corridor-height`

Comments/concerns?

**Comment by chris-little** [comment]
@tomkralidis Or Coverages could align with our lowerCamelCase. Apart from alignment, what are the advantages of changing everything to kebab-yet-another-convention-case?
@cmheazel @ghobona Have API - Common or API - Features agreed a preferred convention? Or is this API - Coverages doing their own thing?

**Comment by m-burgoyne** [comment]
Comparing the two options, I think kebab-case is easier to read

**Comment by tomkralidis** [comment]
+1, plus kebab-case is easier to type.

**Comment by chris-little** [comment]
Upper-Kebab-Case, lower-kebab-case and Mixed-kebab-Case are all amenable to spell checking!

**Comment by cportele** [comment]
> Have API - Common or API - Features agreed a preferred convention?

Features does not have a fixed convention, but so far we have been using kebab-case: `bbox-crs`, `filter-lang`, `filter-crs`.

**Comment by chris-little** [comment]
@ghobona Is a global set of edits something that the OGC editorial team would be willing to do?

**Comment by tomkralidis** [comment]
I'm happy to make the updates for EDR.

**Comment by chris-little** [comment]
@tomkralidis Thanks Tom. Let's discuss tomorrow at the EDR API SWG.

**Comment by chris-little** [comment]
EDR SWG 2021-01-14 agreed on kebab-case. editing assigfned to @tomkralidis . Issue closed

**Comment by chris-little** [comment]
re-opened until task completed

**Comment by tomkralidis** [comment]
Update: PR issued in #172 for review/comment.

**Comment by chris-little** [comment]
As agreed in EDR API SWG #38, 2021-01-14, to be closed when changes made.
