### ISSUE TITLE
parametername in query, missing parameter management

### ISSUE THREAD

**Issue by tloubrieu-jpl** [opengeospatial/ogcapi-environmental-data-retrieval#171]
For parametername in query, the specification says:
"If a requested parameter doesn’t exist in the collection the data for those parameters that do exist
should be returned. If none of the requested parameters exist in the collection a 400 message
SHOULD be returned."

It not clear to me what should be returned if for some objects in the response the parameter does not exist. That might be said somewhere else in the specification.

I see 3 options:
a) the object is not returned
b) the object is returned without the parameter (which does not exist for this object)
c) the object is returned with the parameter set to a default value (null, n/a, ...) 

In our group, in the context of planetary science, we think of going for option c. This will be easier for client to process the result, as since they requested the parameter explicitly they are likely to read it on every objects.
We don't know which appropriate default value should be used, though.

I am wondering how you think EDR API should work ?

Thanks very much, I very much like this initiative of having an open API standard for environmental data retrieval.

**Comment by tervo** [comment]
This is very typical use case for weather observations as well. I also prefer the option c). Other options cast too much responsibility to the client, who should then resolve proper combinations of area, time and parameters in advance.

**Comment by m-burgoyne** [comment]
I also agree, **option c** would help reduce the overhead on client applications as it would ensure that the response contained the number of parameters that the client was expecting.

**Comment by iandruska-ibl** [comment]
I think we can generalise this problem to xy/z/t dimensions as well. I mean, what if some of the requested time frames are not present in data? Or some of the requested vertical levels?

Anyway, I am also in favour of the option c) for the same reasons as mentioned above.

**Comment by m-burgoyne** [comment]
@iandruska-ibl I agree as I think this would simplify the API by having a consistent (and simple) approach which ensured that API responses  matched the shape of the response expected by a client.

**Comment by chris-little** [comment]
Do we need to add some text to the draft spec?
Or just some examples on  the GitHub?
Let us decide in 2 hours at the SWG meeting.

**Comment by tervo** [comment]
My vote goes to the text in the draft spec

**Comment by m-burgoyne** [comment]
My vote would be for both text in the draft spec and examples

**Comment by chris-little** [comment]
@tloubrieu-jpl EDR API SWG 2021-01-14 agreed option (c) is preferred, and text should be added to the draft Specification. @ghobona considers this an acceptable minor editorial clarification. @m-burgoyne will produce example examples. Issue closed

**Comment by chris-little** [comment]
re-opened until task completed

**Comment by chris-little** [comment]
@tloubrieu-jpl please note wew have agreed with your very useful comments, and a PR will be prepared.

Meanwhile please note that `parametername` is now `parameter-name`

**Comment by m-burgoyne** [comment]
Text updated in Pull request #174

**Comment by chris-little** [comment]
PR#174 corrected and merged, as agreed in EDR API SWG39
