### ISSUE TITLE
Wrong parameter name 'corridorz' instead of 'corridor-height' used in Req. 28, 29

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/ogcapi-environmental-data-retrieval#175]
The Requirements 28, 29 contain a wrong name of the parameter `corridor-height`: `corridorz`.

**Comment by m-burgoyne** [comment]
Correction added to pull request #174

**Comment by chris-little** [comment]
Corrected in last pull requests and editorial changes. Agreed at EDR API SWG#39 to close
