### ISSUE TITLE
Inconsistent specification of units in Radius and Corridor queries

### ISSUE THREAD

**Issue by pavol-novotny** [opengeospatial/ogcapi-environmental-data-retrieval#176]
I have noticed that specification of units is inconsistent when comparing the Radius query with the Corridor query:
* Radius - The `withinunits` parameter defines the distance units of the `within` query parameter value.
* Corridor - The units specification is a part of the `corridor-width` and `corridor-height` parameters:
  * `corridor-width = width "/" units`
  * `corridor-height = height "/" units`

I think it would be better to specify the units in a unified way in all data queries. So, there should be separate parameters `corridor-width-units` and `corridor-height-units` in the Corridor query similarly to the parameter `withinunits` in the Radius query.

**Comment by m-burgoyne** [comment]
I agree, it would be a more consistent approach, but it might be worth removing the word corridor from the units name i.e.:

* `width-units`
*  `height-units`

**Comment by pavol-novotny** [comment]
> I agree, it would be a more consistent approach, but it might be worth removing the word corridor from the units name i.e.:
> 
> * `width-units`
> * `height-units`

@m-burgoyne OK, but then also parameters `corridor-width` and `corridor-height` might be renamed to `width` and `height`. What do you think about it?

**Comment by chris-little** [comment]
@pavol-novotny @m-burgoyne I think we should keep the explicit `corridor-width` and `corridor-height`. They may seem the same as, for example, cube width and height, but if we support near vertical trajectories, they may become something different.
`width-units` and `height-units` are less ambiguous.

**Comment by chris-little** [comment]
Incorporated as agreed at EDR API SWG 39.
