### ISSUE TITLE
Metadata - Add "label" property to parameter object

### ISSUE THREAD

**Issue by iandruska-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#179]
Assume the following parameter description:
```
"parameters": {
  "1001537_stat:avg/PT6H": {
    "type": "Parameter",
    "id": "1001537_stat:avg/PT6H",
    "label": {
        "en": "Total cloud cover - 6h average"
    }
    "observedProperty": {
      "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-6-1",
      "label": {
        "en": "Total cloud cover"
      }
    },
    "measurementType": {
      "method": "average"
      "duration": "-PT6H"
    }
  }
}
```

In this particular case, I believe that the "label" property is necessary at both parameter level and observedProperty level. The parameter is defined not only by the observed property but also by the measurement type. The parameter label expresses the whole definition, while observedProperty label expresses only the physical quantity.

This is in line with the CoverageJSON specification. It allows parameter label, but only when it differs from the observedProperty label (exactly the case above).

**Comment by KathiSchleidt** [comment]
is the parameters description now standardized somewhere after all? last I'd looked only informative.
FYI - O&M V3 has an ObservationCharacteristics class defined for exactly such purposes, could be worth considering when staying within OGC standards

**Comment by sgrellet** [comment]
Indeed the "parameter" really resembles what is now ObservationCharacteristics in OM V3. 
It may ease the understanding of the spec as 'parameter' is used with two different meanings: 
- "ObservationCharacteristics"
- query parameter.

Adjusting naming may clarify what is the intended use of this meaning of "parameter".

**Comment by chris-little** [comment]
@sgrellet We considered various alternative names for the 'parameter-name'.

As the data returned may not be perceived as a conventional observation/measurement (such as an estimate or prediction), we avoided those names containing 'observation'. This unfortunately upsets some geospatial experts, but we wanted a generic name that web developers and users 'in the street' could comprehend readily.

We did not like 'variable' either as some data returned (e.g. DEM content) may not be varying very much over time.

We deliberately avoided using traditional geospatial terminology wherever we could, as we wnated to lower the barriers to people outside the geospatial silo. 

It shsould be straightforward and easy to build facades on either the client or server facing sides to chnge the terminology if you wish, and of course, the returned metadata about 'parameter-name' could be whatever is considered appropriate.

Even the name 'environmental' is too specific, but we thought calling the standard something like 'spatial data retrieval' perhaps a setp too far.

**Comment by iandruska-ibl** [comment]
@KathiSchleidt Current Open API schema for EDR parameter description is here: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/parameter.json

**Comment by KathiSchleidt** [comment]
@iandruska-ibl do I understand that this is one option, but not part of the EDR standard? At least from what I read in the draft, was only informative

@chris-little I do believe that 'spatial data retrieval' would be more to the point, especially in light of the comments coming in. To my view, the "environmental" bit in EDR is pretentious, as this aspect is the only bit not really covered!

**Comment by hylkevds** [comment]
> As the data returned may not be perceived as a conventional observation/measurement (such as an estimate or prediction)

Estimates and predictions are completely valid Observations in O&M. O&M even has the field "validTime" specifically for those use cases.

**Comment by chris-little** [comment]
@hylkevds But a target audience of web developers are generally not conversant with O&M, and to be blunt, unlikely to be in the future. That is why we chose `parameter-name`. more detailed metadata could be exposed to the client using fully O&M compliant terminology, or even schema, if decided by the service provider.
The OpenAPI schema for `parameter-name` is indicated in the comment by @iandruska-ibl, and incorporated into  the draft standard, so I will close this issue.
