### ISSUE TITLE
Minor typos: minx where it should be min-z and misplaced asterisk

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#180]
Please see the attached screenshots.

![Screenshot 2021-01-20 at 14 15 40](https://user-images.githubusercontent.com/18121038/105187424-af231c80-5b2a-11eb-8fc6-b8430ea4999f.png)
![Screenshot 2021-01-20 at 14 17 02](https://user-images.githubusercontent.com/18121038/105187427-b0544980-5b2a-11eb-8b94-c4ab5ee6aeb9.png)

**Comment by chris-little** [comment]
Inline editorial change. Well spotted @ghobona

**Comment by chris-little** [comment]
@ghobona Eventually found the missing blank line!
