### ISSUE TITLE
Verify that URIs of Requirements in Annex B match those in Annex A

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#181]
The format of URIs in requirements referenced by Abstract Tests in Annex B is different from the format of URIs of requirements in Annex A.

It's possibly just a simple Copy &Paste error, but repeated across multiple Abstract Tests.

![Screenshot 2021-01-20 at 16 50 11](https://user-images.githubusercontent.com/18121038/105208274-6d04d580-5b40-11eb-9c5b-26a148bdfaad.png)
![Screenshot 2021-01-20 at 16 49 49](https://user-images.githubusercontent.com/18121038/105208276-6d9d6c00-5b40-11eb-88f2-f733cc6311e6.png)

**Comment by chris-little** [comment]
PR incorporated. Clsoed as agreed EDR API SWG40
