### ISSUE TITLE
Remove generated files from git

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ogcapi-environmental-data-retrieval#187]
There are HTML and PDF files checked in to git. These are being automatically regenerated (even when no changes to the source document are being made!) and checked in.

These documents are available on docs.opengeospatial.org and links are provided in the README.md document.

Removing the generated files would also avoid "change" alert noise on the repository.

**Comment by chris-little** [comment]
@bradh I think is a leftover consequence of how all the OGC repos for producing standards documents werwe set up in bulk. It also may a halfway house for those use to editing standalone PDF or Word-like documents and unfamiliar with GitHub. Originally, we also had difficulty in getting a single documente for people to review.
OGC's usage of GitHub is now slightly more sophisticated (but still some way to go!), so having a process whereby only changes to a document's component files initiates an overnight PDF or AsciiDoc build would be good.
We will discuss  at the next EDR API SWG.
If we can can set up

**Comment by bradh** [comment]
There is a link on the front page (see https://github.com/opengeospatial/ogcapi-environmental-data-retrieval#draft-spec) which claims that the version at http://docs.opengeospatial.org/DRAFTS/19-086.html is generated daily.

I don't think checking in generated files to source control is a good idea in general, and certainly a "blind" check in without changes is undesirable. I can understand that "getting an initial infrastructure going" can involve some temporary hacks though.

I'm not following your last sentence ("If we can can set up"), but I assume that the "we" is the SWG, and you're not looking for anything more from me.

**Comment by chris-little** [comment]
@bradh Apologies for tired typing after too long at a screen. You interpreted my ambiguous English correctly.

**Comment by chris-little** [comment]
EDR API SWG 42 agreed to stay with the agreed OGC procedure, but will suggest to @gbuehler and @ogcscotts that it could be improved.

**Comment by chris-little** [comment]
@ghobona has asked to stop putting any of the converted HTML or PDF into the repos.  They will now only be posted in the DRAFTS at:

http://docs.ogc.org/DRAFTS/

We will change our links when this happens.
