### ISSUE TITLE
Change the cube query syntax

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#189]
Currently the **Cube** query uses a `coords` query parameter and a WKT polygon to define it’s geospatial extent and whilst this means that the cube query is using the same approach as the other EDR query patterns it requires additional text description in the API definition to add a constraint limiting the acceptable polygon definitions to rectangles.
To reduce the possibility of confusion for both API implementers and API consumers I suggest it would make more sense to replace the `coords` parameter with a `bbox` definition.
At the same time, I think it would be worth replacing `min-z` and `max-z` query parameters with `z` to bring the vertical level definition into line with the approach used in the other EDR query patterns
So 

`/cube?coords=POLYGON((-8 55,-8 50, 3 50,3 55,-8 55))&min-z=10&max-z=200`

Would become

`/cube?bbox=-8,50,3,55&z=10/200` 

Another option could be to use the `ENVELOPE(minX,maxX,maxY,minY)` syntax supported by CSW CQL, although this does not seem to part of the core WKT definition 

`/cube?coords=ENVELOPE(-8,3,55,50)&z=10/200`

**Comment by iandruska-ibl** [comment]
I agree. Some sort of bbox parameter would definitely distinguish the Cube query from the Area query. The biggest selling points of the Cube query over the Area query is simplicity: for clients as well as for implementers. This change would improve both greatly.

Boost Geometry, for example, extends WKT with `BOX(minx miny, maxx maxy)` (https://www.boost.org/doc/libs/1_65_0/libs/geometry/doc/html/geometry/reference/io/wkt.html):

`/cube?coords=BOX(-8,3,55,50)&z=10/200`

**Comment by cportele** [comment]
CQL defines an `ENVELOPE` literal: 

```
envelopeTaggedText = "ENVELOPE" envelopeText;

envelopeText = leftParen westBoundLon comma southBoundLat comma [minElev comma] eastBoundLon comma northBoundLat [comma maxElev] rightParen;
````

See https://portal.ogc.org/files/?artifact_id=96288, the public review will start soon.

**Comment by chris-little** [comment]
OGC API-Tiles are currently voting on the terminology for BBOX/Envelope. See 
https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/18

**Comment by iandruska-ibl** [comment]
I just realised a little consequence of replacing `min-z`, `max-z` with `z`.

Currently, vertical sampling in Cube query is defined by three parameters: `min-z`, `max-z` and `resolution-z`. The parameters allow two types of samplings:
- Interval: `min-z=100&max-z=1000` (= give me values at all vertical levels available within this interval)
- Arithmetic sequence: `min-z=100&max-z=1000&resolution-z=20` (= give me values at these particular vertical coordinates, interpolate when needed)

`z` parameter currently gives us the following options:
1. single level: `z=100`
2. interval: `z=100/1000`
3. list: `z=100,200,500,1000,2000`

The thing is that `resolution-z` is applicable only to interval. This breaks API's orthogonality. Implementations have to handle this dependency explicitly.

I believe this burden is unnecessary. My suggestion is to extend `z` with the fourth option:
4. arithmetic sequence: z=<begin>/<end>/<count>, for example `z=100/1000/20`. This is equivalent to `min-z=100&max-z=1000&resolution-z=20`.

We can then remove `resolution-z` parameter from Cube query.

Arithmetic sequence would be useful in `datetime` parameter as well.

**Comment by ghobona** [comment]
@chris-little I have created a folder in the repo for [proposed extensions](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/proposals). All OGC API repos now have a similar folder.

Once the SWG has decided on the cube query enhancement, a draft of the enhancement can be sketched out in the proposals folder. You may also want to transfer some of the earlier ideas from the [wiki ](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/wiki/Future-Work)to the proposals folder.

**Comment by m-burgoyne** [comment]
@iandruska-ibl  ISO8601 allows for an Arithmetic sequence using Recurring time intervals, the difference is the number of recurrences is defined at the start and the amount to increment the time by is defined at the end

`i.e. Rn/start time/time duration`

so **R6/2021-02-15T00:00/PT5H** would increment in **5 hourly** timesteps **6 times**

if we followed a similar convention for `z`, 

`i.e. z=Rn/min height/height interval` 

**min-z=100&max-z=1000&resolution-z=20** could be defined as **z=R20/100/50**

**Comment by chris-little** [comment]
Do we need to use a [bbox-crs parameter](https://docs.ogc.org/is/18-058/18-058.html?utm_source=phplist792&utm_medium=email&utm_content=HTML&utm_campaign=Public+Comment+sought+on+new+OGC+API+-+Features+-+Part+3%3A+Filtering+and+the+Common+Query+Language#_parameter_bbox_crs)  to support a bbox approach to the Cube query?

**Comment by m-burgoyne** [comment]
No, in EDR the `coords` query parameter is always specified in the same coordinate reference system as the output data has been requested in.

**Comment by chris-little** [comment]
@iandruska-ibl @m-burgoyne  I think that the ISO8601 style is clunky and should not be copied
 i.e. `z=Rn/min height/height interval   ... could be defined as z=R20/100/50` 

As a Fortran programmer, I prefer the addition to the interval style listed by @iandruska-ibl , z=100/1000/50, as this is a variant on the existing syntaxes. The ISO8601 style is much less intuitive.
The two approaches have different implementations:
    z=100/1000/200 has 5 levels but not 6, easy to test and understand the range. 
    z=R5/100/200 not so intuitive - have to calculate the maximum value or the number of repetitions.

**Comment by m-burgoyne** [comment]
@chris-little But there is the argument for a consistent approach, ISO8601 is a documented standard.

**Comment by chris-little** [comment]
@m-burgoyne @iandruska-ibl Let us keep ISO8601 in its temporal box. Even though it is an ISO standard, the parts that are not about time-stamps are still clunky.

**Comment by iandruska-ibl** [comment]
@chris-little @m-burgoyne I am with Mark on this. I prefer consistency too. Less to keep in mind.

I agree with Chris that the ISO8601's way is a bit clunky. But it is standardly clunky :-) It is hard to resist the standard for me.

**Comment by chris-little** [comment]
z parameter currently gives us the following options:

    single level: z=100
    interval: z=100/1000
    list: z=100,200,500,1000,2000

We remove `resolution-z` and add either
z=100/1000/200 

or

z=R5/100/200

**Comment by chris-little** [comment]
The z parameter used with the Cube query currently has the following options:
    single level: z=100
    interval: z=100/1000
    list: z=100,200,500,1000,2000

We agreed to remove the `resolution-z` parameter and add syntax to the above options

Like this comment before 25-02-2021 if you think the syntax should be:
z=R5/100/200

**Comment by chris-little** [comment]
EDR API SWG 46 agreed
