### ISSUE TITLE
Add a data type definition to the Parameter metadata

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#190]
The current Parameter metadata in the collections response does not provide the client with information about the data type of the response.  Whilst a client application is provided with this information by self describing response formats such as **CoverageJSON,** **netCDF** and **GML** other common  formats such as **GeoJSON** and **CSV** do not have a standard mechanism to define the data type of the returned data values.  

I suggest that we add an optional `data-type` attribute to the Parameter metadata to support describing the data type of the response

```javascript
    "Air Temperature": {
     "type": "Parameter",
     "data-type": "float",
     "description": {
      "en": ""
     },
     "unit": {
      "label": {
       "en": "degC"
      },
      "symbol": {
       "value": "°C",
       "type": "http://labs.metoffice.gov.uk/edr/metadata/units/degC"
      }
     }
```

**Comment by chris-little** [comment]
EDR API SWG 43 agreed to close when PR merged
