### ISSUE TITLE
Upload Recording of 2021-02-18 SWG Meeting to OGC Portal

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#196]
The recording of each OGC API SWG meeting is supposed to be posted to the OGC Portal. This GitHub issue is meant to keep track of the upload of the recordings and also to serve as a quick reference. Note that the recordings are to remain access controlled (only accessible by OGC Members).

**Comment by chris-little** [comment]
@ghobona We been good - they are all in the portal, and editing is restricted.

**Comment by chris-little** [comment]
EDR API SWG 43 agreed to close

**Comment by ghobona** [comment]
https://portal.ogc.org/files/?artifact_id=96503
