### ISSUE TITLE
Rename the standard to Spatial Temporal (Simple) Data Retrieval

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#199]
Several voters, both YES and NO have suggest clarifying the scope of Environmental Data resource by changing the name.

STDR API and STSDR have both been suggested.

This would probably entail changing all of the links in OGC registeries and the document.

**Comment by tomkralidis** [comment]
How about SpatioTemporal Data Retrieval (STDR), where 'retrieval' would mean machinery 'to extract'.  Then again, this might cause some confusion with STAC proper.

Proposal then: SpatioTemporal Data Extraction API (STDE API)?

**Comment by chris-little** [comment]
replaced by #206
