### ISSUE TITLE
minimum capabilities for EDR API

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#201]
I tried running the EDR ETS against the pygeoapi implementation and found numerous errors for core conformance classes.

What is the absolute minimum that an implementing server must support in order to pass ETS.  Say I only have a position query implemented.  Is this enough?  The Core and ETS implementation of same should reflect a low barrier to entry.

**Comment by ghobona** [comment]
@tomkralidis Thanks for asking this question.

@chris-little It would be great if the SWG confirmed the minimal set of EDR conformance classes that should be supported by a compliant product.

**Comment by cportele** [comment]
Isn't this the Core requirements class is, also based on the mod spec?

The lastest draft also says:

> The Core Requirements Class is the minimal useful service interface for an OGC API. The requirements specified in this Requirements Class are mandatory for all implementations of the EDR API.

**Comment by ghobona** [comment]
Thanks @cportele . That answers the question I had.

**Comment by tomkralidis** [comment]
Thanks for the clarifications. It seems that my issues may be bound to the interaction with the ETS itself.  Will follow up in https://github.com/opengeospatial/ets-ogcapi-edr10 accordingly.

**Comment by tomkralidis** [comment]
FYI followup in https://github.com/opengeospatial/ets-ogcapi-edr10/issues/5

**Comment by tomkralidis** [comment]
As per https://github.com/opengeospatial/ets-ogcapi-edr10/issues/5 , the ETS needs to be updated.  I still think it would be valuable to say in the specification what the minimum capability is (again my one query type implementation use case)?

**Comment by chris-little** [comment]
@tomkralidis The spec does say `The Core Requirements Class is the minimal useful service interface for an OGC API. The requirements specified in this Requirements Class are mandatory for all implementations of the EDR API.`

There may be an issue about whether EDR API would work without a collection
`The EDR API Collection Requirements Class extends the common requirements to those specific to the query and retrieval of collections of Environmental Data.
The EDR Collection requirements class is specified in Requirements Class Collection (Chapter 9).`

**Comment by tomkralidis** [comment]
Right. Can/should we make it clear that a collection need to only support one query type?

**Comment by chris-little** [comment]
@tomkralidis If no queries are implemented, it is just API-Common Core, Collections, HTML/JSON/CoverageJSON & OpenAPI. 
I will put a statement in the branch I am working on. See also #237

**Comment by chris-little** [comment]
@tomkralidis So of the 8 queries, are there any that do not make sense by themselves? 
Items (-otherwise it is just Features?
Instances - otherwise it is just enhanced Collections?
So perhaps at least one of the other 6: Position, Radius, Area, Cube, Trajectory, Corridor.

**Comment by tomkralidis** [comment]
Makes sense.  If no queries are implemented, then what makes makes the service an EDR per se?

**Comment by chris-little** [comment]
EDR API SWG 46 Close when text inserted to the effect `at least one of the other 6: Position, Radius, Area, Cube, Trajectory, Corridor, plus Location.`

**Comment by chris-little** [comment]
EDR API SWG 47 agreed  to close. already PR merged
