### ISSUE TITLE
Requirements / tests traceability issues

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ogcapi-environmental-data-retrieval#202]
Found the following requirements that do not have matching test references:
/req/oas30/conformance
/req/oas30/oas-common
/req/edr/corridor-width-definition
/req/edr/corridor-height-response
/req/edr/width-units-definition
/req/edr/width-units-response
/req/edr/f-response
/req/edr/within-units-response
/req/edr/height-units-definition
/req/edr/crs-response
/req/edr/corridor-width-response
/req/edr/within-response
/req/edr/corridor-height-definition
/req/edr/height-units-response
/req/edr/f-definition
/req/edr/within-units-definition
/req/edr/within-definition
/req/core/conformance
/req/core/api-common
/req/core/rc-bbox-definition

Found tests that refer to a requirement, but these requirements were not found:
/req/edr-geojson/content
/req/edr-geojson/definition
/req/oas30/oas-definition-2
/req/oas30/oas-impl
/req/oas30/oas-definition-1
/req/json/content
/req/json/definition
/req/edr/rc-outputformat-definition
/req/edr/rc-parameter-name-definition
/req/collections/rc-outputformat-response
/req/collections/rc-response
/req/edr/rc-crs-response
/req/edr/rc-z-definition
/req/edr/rc-md-query-links
/req/instances/rc-md-success
/req/instances/rc-md-op
/req/core/bbox-definition
/req/core/rc-time-response
/req/core/conformance-op
/req/collections/rc-op
/conf/core/rc-bbox-definition
/conf/core/rc-bbox-response
/conf/core/rc-time-definition
/conf/core/rc-time-response
/req/html/content
/req/html/definition
/req/queries/position
/req/queries/position
/req/queries/position
/req/queries/position
/req/queries/cube
/req/queries/cube
/req/queries/cube
/req/queries/cube
/req/queries/cube
/req/queries/cube
/conf/collections/coords-definition
/conf/collections/coords-response
/conf/collections/min-z-definition
/conf/collections/min-z-response
/conf/edr/max-z-definition
/conf/edr/max-z-response
/conf/collections/rc-parameter-name-definition
/conf/collections/rc-parameter-name-response
/req/queries/area
/req/queries/area
/req/queries/position
/req/queries/area
/req/edr/rc-parameter-name-definition
/req/edr/rc-parameter-name-response
/req/queries/locations
/req/queries/locations
/req/queries/locations
/conf/collections/rc-parameter-name-definition
/conf/collections/rc-parameter-name-response
/conf/collections/rc-time-definition
/conf/collections/rc-time-response
/req/queries/trajectory
/req/queries/trajectory
/req/queries/trajectory
/req/queries/trajectory
/req/queries/trajectory
/req/queries/trajectory
/req/queries/trajectory
/req/queries/trajectory
/req/queries/trajectory
/req/queries/trajectory
/req/edr/rc-parameter-name-definition
/req/edr/rc-parameter-name-response

(For the tests, that is the number of times it was referenced).

**Comment by chris-little** [comment]
@bradh A lot of these mismathces are a consequence of renaming (OpenAPI) parameters to lower-kebab-case. I am sure there are typos too. A Pull Request is being prepared for review tomorrow (Thursday 25 Feb 2021) .

**Comment by chris-little** [comment]
@bradh Happy to close the issue?

**Comment by bradh** [comment]
Its your SWG, so its really your decision, but I think there are still disconnects:

Found the following requirements that do not have matching test references:
/req/oas30/conformance
/req/oas30/oas-common
/req/collections/rc-md-success
/req/collections/rc-md-op
/req/edr/REQ_rc-corridor-width-definition
/req/edr/REQ_rc-width-units-response
/req/edr/rc-position
/req/edr/rc-area
/req/edr/height-units-response
/req/edr/REQ_rc-f-definition
/req/edr/REQ_rc-within-definition
/req/core/datetime-parameter
/req/core/api-definition-op
Found tests that refer to a requirement, but these requirements were not found:
/req/edr/within-definition
/req/edr/rc-f-definition
/req/edr/corridor-width-definition
req/collections/rc-md-success
req/edr/max-z-response
req/collections/rc-md-op
/req/edr/REQ_rc_width-units-response
/req/edr/REQ_rc_height-units-response
/req/instances/src-md-success
/conf/core/rc-bbox-definition
/conf/core/rc-bbox-response
/conf/core/rc-time-definition
/conf/core/rc-time-response
/req/core/api-definition
/req/queries/position
/req/queries/position
/req/queries/position
/req/queries/position
/req/edr/z-definition
/req/edr/z-definition
req/edr/rc-area
req/edr/rc-area
req/edr/rc-area
req/edr/rc-area
/req/edr/z-definition
/req/queries/trajectory
/req/edr/z-definition
/req/edr/z-definition

Some of that looks like format issues (missing leading `/` in the ATS version). Looks like there are still a couple of identifiers that are not in kebab-case too.

**Comment by bradh** [comment]
Have provided a partial fix at #235.

If that is merged, the discrepancies would be:

Found the following requirements that do not have matching test references:
/req/oas30/conformance
/req/oas30/oas-common
/req/core/datetime-parameter

Found tests that refer to a requirement, but these requirements were not found:
/conf/core/rc-bbox-definition
/conf/core/rc-bbox-response
/conf/core/rc-time-definition
/conf/core/rc-time-response
/req/edr/z-definition
/req/edr/z-definition
/req/edr/z-definition
/req/edr/z-definition
/req/edr/z-definition

**Comment by bradh** [comment]
Residual from #235 

@chris-little said:

> @tomkralidis @m-burgoyne These first requirements should come from OGC API-Common Core and therefore that is where the test should be too?
> /req/oas30/conformance
> /req/oas30/oas-common
> /req/core/datetime-parameter
> 
> These requirements also come from OGC API-Common Core
> /conf/core/rc-bbox-definition
> /conf/core/rc-bbox-response
> /conf/core/rc-time-definition
> /conf/core/rc-time-response
> 
> @tomkralidis @m-burgoyne were these several tests not updated when the requirements were?
> /req/edr/z-definition
> ?

I noted:

> If the requirement is a partial URI, it isn't pointing to Common. Note https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/clause_5_conventions.adoc#identifiers

> 
>     The normative provisions in this standard are denoted by the URI:
> 
>     http://www.opengis.net/spec/ogcapi-edr-1/1.0
> 
>     All Requirements and Conformance Tests that appear in this document are denoted by partial URIs which are relative to this base.

> 
> That is, /req/oas30/conformance means http://www.opengis.net/spec/ogcapi-edr-1/1.0/req/oas30/conformance.
> 
> More generally, if we have a requirement that is "complies with (some document)", then there should be a matching ATS clause to check that compliance (which could point to that document for the test process if it has one, or could specify it). It doesn't matter if its some part of Common or something else. As a practical matter, the ETS implementers only need to code what is in the ATS, so if we want compliance checked, it needs to be in the ATS.

**Comment by chris-little** [comment]
EDR API SWG 46 Close when PR merged

**Comment by bradh** [comment]
I note that https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/requirements/edr/query_type/no-data.adoc does not have a corresponding ATS entry.

[I'm assuming the parts from Common are being ignored, which I disagree with, but will accept for the sake of moving forward.]

**Comment by tomkralidis** [comment]
No data ATS addressed in #253 (thanks @bradh for the help/guidance).
