### ISSUE TITLE
TC E-vote Comment 5a: Clarify relationships with other OGC Standards

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#211]
Comment 5 is rather large, so split into separate issues: 5a,b,c,d,e,f.

`We can see the interest of this (Simple) API for Spatio-Temporal Resource Retrieval API, but we are facing some confusion (and potentially conflicts) with other environmental data and other features API in the OGC. The coherence / relations with STA, Observations API, Coverages and Moving Features should be considered and clarified in this document. If this is done, we would be happy to change our vote to yes.`

`Coherence / Relationship with other OGC APIs: This specification discusses and exemplifies the potential use for Observation, Features of interest and Coverages (on basis of Coverage-JSON), and compares with SOS and WCS. However there is clearly an overlap with emergent Coverages API and the revision of STA for OGC API alignment. There should be a section (or an annex) for the relationship with other OGC APIs summarizing the relations with other OGC API standards, including OGC API Features, Moving feature access, WCS MetOcean AP (which has been adopted after more than 5 years of effort in OGC, and does not seem to be promoted any more) and STA with which there is a significant overlap.
If not, this specification will introduce overlap conflicts with Coverage, Observation, STA and Moving Feature access APIs, and this will be a source of confusion in the new generation of OGC APIs.`

**Comment by chris-little** [comment]
I suggest we add an Informative Annex (as we said we would) clarifying the relationships, if any, to the other mentioned OGC standards:
Sensor Things API (STA), 
Observations API, [I am not aware of one, presumably O&M?]
Coverages [presumably both the coverages concept and the in progress OGC API-Coverages]
Moving Features [

**Comment by dr-shorthair** [comment]
There absolutely is an OGC Observations API - SOS - which is designed in classic OGC WXS style. 
Definitely SOS is from another era, and needs to be updated or replaced with something more modern. 
But it is quite troubling that this group appears to have gone so far without looking at the OGS baseline on this topic. 

SensorThings is more modern with a similar scope.

**Comment by chris-little** [comment]
Issues #211, and #217 arising from the TC E-vote Comments are basically the same.

**Comment by chris-little** [comment]
Annex, without content, to be added in PR #227, and page added to GitHub Wiki.

**Comment by chris-little** [comment]
EDR API SWG 46 Close when PR merged
