### ISSUE TITLE
TC E-vote Comment 5d: What is the base resource

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#214]
Comment 5 is rather large, so split into separate issues: 5a,b,c,d,e,f.

`General/major: Supposedly there is no underlying data model behind this API, except the “Environmental Data Resource” under discussion and “Environmental Data Resource Collection”. This concept is not the object of any model, and seems to be designed to be flexible and versatile. However there is a need (for users) to properly define, name and document this base resource(s) of this specification, supposed to make it different from other OGC APIs (or add special value).`

**Comment by chris-little** [comment]
@EmDevys References to "Environmental Data Resource" replaced generally by "spatio-temporal resource" in PR #239

**Comment by EmDevys** [comment]
This proposed change clarifies the object of this API, and avoids the need to define this concept of "Environmental Data Resource" under discussion in the OGC. I fully support this change.

**Comment by chris-little** [comment]
EDR API SWG 46. Issue addressed
