### ISSUE TITLE
TC E-vote Comment 4b: Propose O&M V3 terminology for parameter-name

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#222]
Instead of trying to contribute to overcome the missing interoperability between OPC API and SensorThings API, this specification increases their divergence as it aims at resolving already resolved requirements of the environmental domain (such as sensor data management) in a different, incompatible manner. See detailed comment at https://portal.ogc.org/files/?artifact_id=96471.

`EDR Feedback from O&M, EDR Analysis Version: 2021-02-16
**Overloading of the word “parameter”**
The word “parameter” is used in different contexts, making it difficult to scan and search for:

    The OpenAPI definition
    The EDR definition “the values that go into parameter-name”, that is never actually defined, but still used.

Other commonly used terms for this are:

    Characteristic
    Variable
    Observed property (or just property)
    Measurand
    Analyte.

It seems the second use is core to the standard, but very much overshadowed by the many cases where the first use occurs.→ overall OGC Observation context : O&M V3 has created ObservationCharacteristics for the express purpose of describing types of observations by their characteristics, would be valuable for users if this were utilized in collection landing page in the informative annex→ proposed solution: -provide example utilizing ObservationCharacteristics-rename parameter-name into something without “parameter” contained, e.g observation-characteristics or something neutral like data-field-nameThe parameter “parameter-name”The spec never defines the semantics of the content of this parameter. The specification does not seem to define what the meaning is of the values that go in there, nore how a client is supposed to find this information.?It only refers to OpenAPI Specification which specifies what informatic content is to be expected: a list of strings. But not what communities are supposed to dowith it. The only hint on this is given in the informative Annex

**Comment by chris-little** [comment]
We have discussed this several times in the SWG, and have agreed on `parameter-name`, in "lower-kebab-case", in spite of `parameter` being already defined in OpenAPI, because it is generic and ope ended, and easy to understand.

To summarise previous discussions about naming what is retrieved:
Characteristic - it is not, it is a fundamental elemental data thing;
Variable - sometime it is not variable but fixed, over long periods of time;
Observed property (or just property) - manydata values are not observed in the conventional sense;
Measurand - many data values are not measured in the conventional sense;
Analyte - many data values are not analysed in the conventional sense.

**Comment by dr-shorthair** [comment]
@chris-little not sure what you are getting at here? 
Your natural-language analysis of these terms is not entirely the point. 
All those terms have precedents. sometimes in multiple specific domains, but with very clear semantics. 
Natural-language interpretations can't override those and be taken seriously.

**Comment by chris-little** [comment]
Good morning @dr-shorthair. i suppose the point is that this API is going to be used by web developers who do not know much, or anything, about geospatial, OGC, or even W3C for that matter. 

I think the safest thing is to use a bland name that can be over-loaded. If they are exposed to those precisely defined terms, they will still overload them with other, imprecise, meanings.

`parameter-name` is just a tag in an OpenAPI YAML/JSON schema fragment and scripts. And `parameter` is  one of the ubiquitous names used in WMO and meteorology., especially in the GRIB format. `parameter=parameter` was problematic, hence `parameter=parameter-name` 

The other ubiquitous name, used in BuFR tables, is `Element` but that has problems too.

Does that make sense? (it is rather late here!)

**Comment by dr-shorthair** [comment]
Most of those terms come from science, not from OGC or W3C.

**Comment by chris-little** [comment]
@dr-shorthair Good point. I expect there will also be web developers who are not scientifically literate. 

I am not sure why precisely defined terminology from controlled vocabularies or ontologies should appear in a generic API definition. In the metadata yes, but not the API.

**Comment by KathiSchleidt** [comment]
But, if the API defines the API landing page where the metadata is to be provided, I would expect some indication of this in the API spec!
The real background of this issue is the double use of parameter, both as a query parameter (so spatio-temporal plus the parameter-name), as well as the naming of the parameter name. This makes it difficult to understand the standard, search for parameter throws up everything, finding the observable property becomes difficult

**Comment by iandruska-ibl** [comment]
What about `quantity`? I believe it should be clear even to a scientifically illiterate web developer (we all learned what a physical quantity is in elementary school, I hope).

**Comment by KathiSchleidt** [comment]
Quantity is strange with concentrations, also wouldn't see temperature as a quantity

**Comment by iandruska-ibl** [comment]
Both concentration and temperature are physical quantities: https://en.wikipedia.org/wiki/List_of_physical_quantities.

Quantity applies to both countable and uncountable phenomena: https://www.oxfordlearnersdictionaries.com/definition/american_english/quantity

**Comment by chris-little** [comment]
Consensus is that `parameters` used in collections should be changed to `parameter-names`, to be consistent with `parameter-name` used in queries, which is unchanged, for commuity  and historical reasons.
A PP will be prepared

**Comment by chris-little** [comment]
EDR API SWG 48 agreed to close as change now merged
