### ISSUE TITLE
TC E-vote Comment 4c: Potential reuse of ObservationCharacteristics as feature type

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#223]
Instead of trying to contribute to overcome the missing interoperability between OPC API and SensorThings API, this specification increases their divergence as it aims at resolving already resolved requirements of the environmental domain (such as sensor data management) in a different, incompatible manner. See detailed comment at https://portal.ogc.org/files
`EDR Feedback from O&M, EDR Analysis Version: 2021-02-16

**Potential reuse of ObservationCharacteristics as feature type**
E.g. ObservationCharacteristics for mean wind direction could be hosted once by WMO as a featureType, all EDR endpoints could reference. This would be standardized and reusable. We could provide an example of ObservationCharacteristics in an OGC API -Feature endpoint.

**Comment by chris-little** [comment]
Mean wind direction observation characteristics are mandated by WMO, and it is the EDR API SWG intention, and the Met Ocean DWGs, to reference those authoritative standards if appropriate. Sometimes, ICAO standards may be more appropriate, etc. Unfortunately, the WMO standards are not in an O&M format but in vocabulary registries and sometimes in ISO19115 records.

There is no barrier in the EDR API standard, and in fact it is encouraged, that service providers give access to structured metadata as they consider appropriate. Generally, this would be at the OGC API-Common Part 2: Collection level, not the query level.

**Comment by KathiSchleidt** [comment]
Does this mean that a data provider can utilize any structure for the provision of the parameter-name in the landing page, e.g. we could do valid implementations replacing the placeholder currently taken from CovJSON and replace with either ObservationCharacteristics or the DataStream from STA?
How does a data user know about the structure under which the parameter-name will be provided?

**Comment by chris-little** [comment]
@KathiSchleidt I think the answer to your question is Yes.
`parameter` was originally chosen for EDR and presumably CoverageJSON, because it was and is common usage in the Met communities.

**Comment by KathiSchleidt** [comment]
@chris-little now would just need to know which part of my question the "yes" answer applies to!

Assuming the "yes" applies to the first question `Does this mean that a data provider can utilize any structure for the provision of the parameter-name in the landing page`, it seems in contradiction to your statement under [TC E-vote Comment 4f: Allowed values for "parameter-name" parameter not discoverable #242 ](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/242#issuecomment-796773133)

Also - still missing how a client will know about the structure to be provided within the parameter description in the collection landing page, unclear if [parameter definition](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/parameter.yaml) as well as the dependent bits such as the [observedProperty definition](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/observedProperty.yaml) schemas are normative or informative (problem with a simple yes to a complex question!)

**Comment by chris-little** [comment]
@KathiSchleidt Nearly, but not all, the Pull Requests that fix problems in the metadata responses have been merged, but there is still one outstanding. This PR procedurally needs confirmation from the OGC Planning Committee, as it is a breaking change from the version that the Technical Committee approved. And the SWG needs to agree that it is the best approach.
That said, the SWG's intent is that `parameter-name` should be a mandatory part of the standard, though YAML or other schema frameworks are not, by design. And notwithstanding that, the API-Common SWG has recently proposed that no OpenAPI parameters should be mandated, and no specified parameters is valid for a GET on a resource.

There are rather a lot of moving pieces at present, so I think the answer to your roiginal question is still Yes and No.

@gbuehler And even though all the ASCIIDoc errors seem to have been fixed, and local builds work, we still do not know why the nightly document build fails.

**Comment by chris-little** [comment]
@KathiSchleidt All the technical changes to the EDR API spec are in place, though there are still some minor editorial changes to the English, all in a separate branch, to be merged hopefully tomorrow and then frozen.
We think there is enough OpenAPI YAML fragments and link relations defined to support a range of uses cases, though there is still no consensus in OGC as to which is preferred or agreed. Hopefully, experience in production enviromenets will indicate good practice.
Hence, we then proose to close this issue.

**Comment by KathiSchleidt** [comment]
@chris-little still haven't gotten an answer on if these OpenAPI YAML fragments are normative or informative, also continue to be irritated by the new OGC philosophy that "if I don't bother to encode it in UML, only YAML, it's not a data model"

Sorry for my preconceptions that standardization is about harmonization and interoperability, sure your customers will be most happy to get on without such undue burden

**Comment by chris-little** [comment]
@KathiSchleidt See the comments on Issue #266 from @cportele

**Comment by chris-little** [comment]
@KathiSchleidt To address your concern, and perhaps establish a precedent for OGC APIO-Common Part 2: Collections/GeoData and other APIs, we are adding an "Annex Collection Response", with a list of EDR Collection objects, indicating which are mandatory and which are optional.
Currently awaiting full reviews in PR #284.

**Comment by chris-little** [comment]
@KathiSchleidt PR#284 now merged
