### ISSUE TITLE
TC E-vote Comment 4d: Non-standard use of ISO 8601 periods / intervals

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#224]
Instead of trying to contribute to overcome the missing interoperability between OPC API and SensorThings API, this specification increases their divergence as it aims at resolving already resolved requirements of the environmental domain (such as sensor data management) in a different, incompatible manner. See detailed comment at https://portal.ogc.org/files
`EDR Feedback from O&M, EDR Analysis Version: 2021-02-16

**Non-standard use of ISO 8601 periods / intervals**
We can’t find a definition for negative durations, nor for intervals consisting of two durations, as used in the example:"measurementType": {"method": "mean","period": "-PT10M/PT0M"}

**Comment by chris-little** [comment]
The example given is at `C.4. Collections Metadata Examples` and is a real-world realistic example.

Mandated common and best practice world wide for reporting wind speeds is at a nominal hour, but in fact it is a 10 minute arithmetic mean over the previous 10 minutes, so that the observation can be transmitted immediately after the hour, along with other instantaneous synoptic observations at that time.
We would welcome a fully standard,but compact way of indicating this.

The ISO8601 standards give useful notation for specifying durations & repeating intervals as well as time-stamps.

Rather than invent Yet Another Micro Syntax, we have extended the notation in an obvious intuitive way.
ISO8601 is not defined prior to the adoption of the Gregorian calendar, between 1588 and 1923 in various regions, but it is still used for pro-leptic Gregorian dates.

**Comment by hylkevds** [comment]
If you extend a specification, you should clearly define that extension. Even if you find something "obvious intuitive", if it is not normatively defined it will cause confusion. Especially since software does not have "intuition".

**Comment by KathiSchleidt** [comment]
Could somebody please clarify the different between "invent Yet Another Micro Syntax" and "extended the notation in an obvious intuitive way"?
While the 2nd seems to take some aspects of the standard into account, for an application parsing, it's basically the same as YAMS

**Comment by chris-little** [comment]
@KathiSchleidt Some text will be prepared to explain that obvious extension to the ISO8601 notation.

**Comment by dr-shorthair** [comment]
Merely repeating loaded language like 'obvious' is disrespectful to the legitimate commenters.

**Comment by chris-little** [comment]
@KathiSchleidt @dr-shorthair I apologises for that unintended interpretation. Perhaps 'simple' would be better. Text to explain the use of the minus sign is being prepared.

**Comment by chris-little** [comment]
@KathiSchleidt @hylkevds The ISO860n explanatory text of the informative example is in PR #284 which will be merged once fully reviewed.

**Comment by chris-little** [comment]
@hylkevds @KathiSchleidt PR#284 now merged.
