### ISSUE TITLE
TC E-vote Comment 4e: No Mention of the OGC SensorThings API

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#225]
Instead of trying to contribute to overcome the missing interoperability between OPC API and SensorThings API, this specification increases their divergence as it aims at resolving already resolved requirements of the environmental domain (such as sensor data management) in a different, incompatible manner. See detailed comment at https://portal.ogc.org/files
`EDR Feedback from O&M, EDR Analysis Version: 2021-02-16

**No Mention of the OGC SensorThings API**
While in the intro there is a reflection on how EDR supports the same data as SOS and WCS, it then continues to explain how EDR finally provides an API for this data. There is no mention of the OGC SensorThings API, a long established and well deployed OGCstandard that already does much of what EDR does`

**Comment by chris-little** [comment]
I have started an Informative Annex to the EDR API standard, to explain the relationship of the EDR API to other OGC standards

**Comment by chris-little** [comment]
OGC API-Features Part 1: Core and Part 2 CRS do not mention Sensor Things API either.
Nor does the draft API-Common Part 1: Core and Part 2: Collections
Sensor Things API Part 1:Sensing is defined using ODATA running over MQTT.
The other OGC APIs, EDR included, are defined with OpenAPI v3.0 running over HTTP(S)
EDR API does not have a streaming mode - one query, one response.
EDR API does not do sensor management and has no overlap with Sensor Things Part 2: Tasking
EDR API allow access to whatever metadata the EDR API server decides is appropriate. This could be compatible with STA, or SOS and O&M, but this is exposed at the Collection level, being defined in OGC API-Common Part 2: Collections (aka Geospatial Data).

**Comment by hylkevds** [comment]
> OGC API-Features Part 1: Core and Part 2 CRS do not mention Sensor Things API either.

They don't need to, they don't deal with Observational type data

> SensorThings API Part 1:Sensing is defined using ODATA running over MQTT.

Incorrect, please read the standard. The MQTT part is merely an extension.

> EDR API does not have a streaming mode - one query, one response.

The streaming bits are merely an extension in the SensorThings API. The core is one query, one response.

Currently, there is nothing EDR does that can not be done with SensorThings. EDR just makes the queries less verbose. That would be worth mentioning...

**Comment by KathiSchleidt** [comment]
`EDR API allow access to whatever metadata the EDR API server decides is appropriate. This could be compatible with STA, or SOS and O&M, but this is exposed at the Collection level, being defined in OGC API-Common Part 2: Collections (aka Geospatial Data).`
Could somebody please provide a pointer on how/where the parameter-name bit in the collection description is now being specified in common? Thought this only pertained to the kebab-case aspects, didn't realize that there was more semantics there

**Comment by sgrellet** [comment]
To help share knowledge about ST API and avoid misconception about it, I think the EU ELISE workshop done last year as an output from our API4INSPIRE project may help : 
https://joinup.ec.europa.eu/collection/elise-european-location-interoperability-solutions-e-government/event/elise-workshop-sensorthings-api-brings-dynamic-data-inspire
Slides & recording here : 
https://joinup.ec.europa.eu/collection/elise-european-location-interoperability-solutions-e-government/document/presentation-sensorthings-api-brings-dynamic-data-inspire
HTH

**Comment by chris-little** [comment]
EDR API SWG 46 agreed to close, as Annex describing relationship is about to be added, and project work identified to implement EDR and STA alongside and investigate intergration opportunities. 
.

**Comment by hylkevds** [comment]
Closing an issue because you are planning to do something is very bad form. Please re-open until you have actually done it.

**Comment by KathiSchleidt** [comment]
Related - based on the number of modifications done in the last days - will there be a further review cycle on this standard, or do we just have to trust the SWG agreement on closing, no reasons or concrete changes stated?

**Comment by dr-shorthair** [comment]
I agree with @hylkevds - this issue should not be closed until we have actually seen the Annex. Announcing a plan to resolve it is not enough to take it off the list.

**Comment by chris-little** [comment]
@hylkevds @KathiSchleidt The [Annexe](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/annex_relationship.adoc) was not incorporated into recent builds of the standard as it was in a separate Branch, awaiting other merges and SWG approval.

**Comment by chris-little** [comment]
@hylkevds @KathiSchleidt @dr-shorthair We propose to close this Issue at the next SWG meeting on Friday, as there has been no negative comment on the [Annexe](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/annex_relationship.adoc), or further suggestions for improvement, incorporated 13 days ago.
Please note such an annexe is now likely to be incorporated into OGC standards template.

**Comment by hylkevds** [comment]
Thanks for the reminder, it got lost in the piles...

The STA part is mostly fine, but the OGC SensorThings API can support any result format using the $resultFormat query parameter. The default result format is JSON, but the standard itself already defines an extension that adds a more compact JSON result format, and there are community extensions for [CSV](https://github.com/INSIDE-information-systems/SensorThingsAPI/blob/master/CSV-ResultFormat/CSV-ResultFormat.md) and [GeoJSON](https://fraunhoferiosb.github.io/FROST-Server/extensions/GeoJSON-ResultFormat.html). If developers would like an XML result format, it is trivial to add. In this respect there is no difference between the EDR API and STA.

**Comment by chris-little** [comment]
@hylkevds Do you have any proposed editorial changes to the wording?

**Comment by hylkevds** [comment]
I suppose that, since the second to last paragraph doesn't really highlight a difference between the APIs, the simple fix would be to just remove it.
The last paragraph could be changed a bit to highlight that EDR and STA are not incompatible, and can be used on the same data. Suggestion:

> An EDR and STA interface could be deployed on the same data set, so that users and developers that do not need the full details of observational, feature or coverage conceptual models and associated metadata could use the EDR API to hide the extra complexity, while users that do need all the details can use the STA API to retrieve those.

**Comment by chris-little** [comment]
EDR API SWG 49 incorporate proposed change and close

**Comment by chris-little** [comment]
Currently in a separate minor editorial branch to be merged on 2021-04-22 with the master branch, which has had technical content frozen.
