### ISSUE TITLE
response for no data

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#228]
cc @ShaneMill1 @solson-nws @m-burgoyne 

Suppose I have an underlying dataset with data at discrete coordinates.

What should be the response of something like (assuming there is no data at `POINT(1 1)`):

`http://localhost:5000/collections/edr-test/position?f=json&coords=POINT(1 1)&parameter-name=SST`

The 'resource' is technically there, so 404 would seem odd.  In OACov when we encounter this issue we throw 204.

Should we consider 204 here?

**Comment by ShaneMill1** [comment]
https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/EDR_OpenAPI.json#L331

I think the spec implies a 400. However, to @tomkralidis point, a 204 may be better, also it aligns with OACov.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

**Comment by solson-nws** [comment]
I put this in gitter.  Adding it here:

204 seems better than a 404 to me, because it at least informs the client
the request was successful , just no content. In this case it would suggest
that a resource DOES exist but for some reason the server chose not to
include the resource in the response body. Another good outcome of a 204
code is that it can also be used as a response to a POST request.

**Comment by m-burgoyne** [comment]
The concept in EDR is that the response to a request for underlying dataset with data at discrete coordinates would be dependent on the collections business logic.  In EDR a collection is a combination of business logic and the underlying data, this logic could be a simple as select the data from the underlying data source that matches the spatial temporal location in the query or it could be more complicated (i.e. return a interpolated value or a nearest neighbor value or an error value).  The key is the collection publisher is responsible in providing to best result for the users query.  Depending on the collection, if the query is not an exact match the response could be a 404 for not found or a derived value based on what the publisher decides is the best response for the query or a 400 if the request is outside of the bounds of the collection.  If 204 is used I think the response would have to provide some feedback to inform the user of what a valid spatial-temporal locations are.

**Comment by tomkralidis** [comment]
cc'ing @jerstlouis for possible input/recommendation here on 404 vs. 204.

**Comment by jerstlouis** [comment]
Thanks @tomkralidis 
See (C) https://github.com/opengeospatial/ogcapi-coverages/blob/master/standard/requirements/coverage-subset/REQ_cov-subset-definition.adoc
and
(C) https://github.com/opengeospatial/ogcapi-tiles/blob/master/core/standard/requirements/core/REQ_tc-success.adoc
For use of 204 in Coverages and Tiles.
I prefer 204 myself as an indication that the client did nothing wrong and that there is simply no data resulting from the request.

**Comment by m-burgoyne** [comment]
After Looking at the description of the 204 message, I agree that 204 would be a better response than 404. 4XX messages imply an error which would not be the case with the request

**Comment by chris-little** [comment]
@tomkralidis @ShaneMill1 @m-burgoyne Will this go in a new PR or an existing one?

**Comment by tomkralidis** [comment]
I can add to to new PR so feel free to assign to me

**Comment by tomkralidis** [comment]
PR in #240

**Comment by chris-little** [comment]
close when PR merged
