### ISSUE TITLE
inconsistency between YAML schemas and documentation

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#230]
The draft specification specifies support for `z=ALL`, per http://docs.opengeospatial.org/DRAFTS/19-086.html#req_edr_z-definition, however the docs in the YAML schema at https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/parameters/z.yaml do not mention this capability.

**Comment by chris-little** [comment]
@tomkralidis Well spotted. Let's bundle all the ALL changes in one PR.

**Comment by tomkralidis** [comment]
PR in #241

**Comment by chris-little** [comment]
close when PR done
