### ISSUE TITLE
make YAML properties consistent

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#232]
It seems that we support multilingual properties in some places but not others:

- https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/parameter.yaml (see `en` properties)
- https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/collectionInfo.yaml

We should probably apply the same approach throughout the schemas.

**Comment by chris-little** [comment]
EDR API SWG 46 agreed to close after PR
