### ISSUE TITLE
collection link relations

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#233]
For a given collection, consider the following link relations snippet:

```json
        {
            "type": "text/json",
            "rel": "data",
            "title": "position query for this collection as JSON",
            "href": "http://localhost:5000/collections/edr-test/position?f=json"
        },
        {
            "type": "text/html",
            "rel": "data",
            "title": "position query for this collection as HTML",
            "href": "http://localhost:5000/collections/edr-test/position?f=html"
        }
```

Each of those will result in a 400 (missing parameters).  Should we consider [examples](http://docs.opengeospatial.org/DRAFTS/19-086.html#collections-metadata-examples) that provide a 2xx response?

**Comment by tomkralidis** [comment]
Note that this also relates to [Principle 23](https://github.com/opengeospatial/OGC-Web-API-Guidelines/blob/master/README.md#principle-23---make-default-behavior-explicit) of the OGC Web API Guidelines.

**Comment by chris-little** [comment]
@tomkralidis If a mandatory parameter is missing, return `400` plus explanatory messages meets Principle 23?
Returning ALL data not realistic.

**Comment by tomkralidis** [comment]
@chris-little agree that returning ALL data is not realistic.  Having said this, principle 23 also mentions to avoid exceptions as a best practice?  We may or may not be able to meet this, OR specify that the server can do either (`400` or a `200` if they can handle it).  Then again that breaks the mandatory parameter rule, as well as introduces ambiguity.

**Comment by m-burgoyne** [comment]
@tomkralidis, @chris-little  the link schema only has the `href` and `rel` properties as required, so we could solve this issue by using the approach I took in the original Weather on the Web demo.
Firstly in the links section only needs to have a single reference to each supported query and the link information does not need to include a mime/type i.e.:

  {
      "rel": "data",
      "title": "position query for this collection as JSON",
      "href": "http://www.example.org/collections/edr-test/position"
  }

if the user does not include the mandatory query parameters the server would return would return a HTML form with fields for the query parameters (this could be as simple as a Swagger-UI page driven by a subset OpenAPI document containing details for just the requested query parameter).  

This would allow a `200` response without having to return all of the data 

The mime/types supported by the query are available elsewhere in the collection response and this would have the added advantage of reducing the number of similar links in the links section.

**Comment by tomkralidis** [comment]
EDR API SWG meeting 2021-03-26: we should consider the approach put forth in OARec, as a means to provide query parameter information in our EDR collections:

https://github.com/opengeospatial/ogcapi-records/issues/95

cc @pvretano @jerstlouis

**Comment by tomkralidis** [comment]
Example:

```json
        {
            "type": "text/json",
            "rel": "data",
            "title": "position query for this collection as JSON",
            "href": "http://localhost:5000/collections/edr-test/position?parameter-name={parameter-name}&coords={coords}&f=json",
            "templated": true,
            "variables": {
               "coords": {
                  "description": "WKT geometry",
                  "type": "string"
               },
               "parameter-name": {
                  "description": "CSV of parameter names",
                  "type": "string"
               }
            }
        }
```

**Comment by cportele** [comment]
@tomkralidis - I think the "parameter-name" variable should look like the following:

```json
{
   "description": "CSV of parameter names",
   "type": "array",
   "minItems": 1,
   "itemType": {
      "type": "string",
      "enum": [ "temperature", "wind-speed", "pressure" ]
   }
}
```

PS: There is no `text/json` media type.

**Comment by tomkralidis** [comment]
Thanks @cportele .  Updated example:

```json
{
  "type": "application/json",
  "rel": "data",
  "title": "position query for this collection as JSON",
  "href": "http://localhost:5000/collections/edr-test/position?parameter-name={parameter-name}&coords={coords}&f=json",
  "templated": true,
  "variables": {
    "coords": {
      "description": "WKT geometry",
      "type": "string",
      "minItems": 1
    },
    "parameter-name": {
      "description": "CSV of parameter names",
      "type": "array",
      "minItems": 1,
      "itemType": {
        "type": "string",
        "enum": [
          "temperature",
          "wind-speed",
          "pressure"
        ]
      }
    }
  }
}
```

Having said this, would the `enum` work here, given the user can specify one or more of the values as part of a CSV value?  Example:

- `parameter-name=temperature`
- `parameter-name=temperature,wind-speed`

**Comment by cportele** [comment]
Yes, each value in the array has to be one of the enums. The array of values is represented as comma-separated values, this is the OpenAPI default for query parameters. We use that all the time in ldproxy API definitions to be explicit what values are accepted and also use the schema to validate the query parameters in requests automatically against the JSON Schema of the parameter.

**Comment by chris-little** [comment]
The EDR API is now technically frozen, with one branch of minor editorial changes to be done on 2021-04-22.

Any outstanding technical detail will need consensus and approval for future work.
