### ISSUE TITLE
Corridor definition not very good

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#238]
Current Corridor definition: `path of a moving point described by a one-parameter window around a set of points`.

Propose: `two-parameter region around a trajectory`.

A corridor has two degrees of freedom more than the trajectory.

This should allow "curtain" and "time-curtain".

**Comment by solson-nws** [comment]
Do we need to differentiate the fact that a corridor be expressed as a set
of points varying in X, Y, and T as well as X, Y, Z and T?

Do we need to define a default interpolation scheme for a corridor?

Steve

**Comment by chris-little** [comment]
@solson-nws No. (x,y), (x,y,z), (x,y,t), (x,y,z,t) are all implicit in the ISO "one-parameter" definition. All of those cases are a  single line - wiggly across various space dimensions, but still one dimensional, therefore one parameter.

No default interpolation scheme - depends on the data, service and even `parameter-name`

**Comment by chris-little** [comment]
updated in PR #239

**Comment by chris-little** [comment]
EDR API SWG 46 agreed to close
