### ISSUE TITLE
TC E-vote Comment 4f: Allowed values for "parameter-name" parameter not discoverable

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/ogcapi-environmental-data-retrieval#242]
I've not been able to find how a (software) client is supposed to find the allowed values for the parameter "parameter-name", nor what those values mean. Just stating that they must be "listed in the collections metadata" is not sufficient for discovery.

My suggestion would be to require that the response to 
```
/collections/{collectionId}
/collections/{collectionId}/instances/{instanceId}
```
contains, at minimum, something like below, but leaving it open for extensions to define further content. That way a (software) client will know at least where to find the list of allowed values, with a human readable name and description, but it leaves the definition open for an extension to state, for instance, that the objects should be SWE Common fields.

```JSON
{
  "parameter-name": {
    "Maximum_temperature": {
      "name": "Maximum Temperature",
      "description": "The maximum temperature measured during the day"
    },
    "Minimum_temperature": {
      "name": "Minimum Temperature",
      "description": "The minimum temperature measured during the day"
    },
    "Total_precipitation": {
      "name": "Total Precipitation",
      "description": "The total cumulative precipitation measured during the day"
    }
  }
}
```

**Comment by tomkralidis** [comment]
@hylkevds thanks for the feedback.  You can see this in the YAML schemas at:

- `/collections/{collectionId}`: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/collection.yaml#L88

This needs to be fixed in schemas for instance metadata, but the idea is that the same [parameter definition](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/parameter.yaml) will be present there as well.

**Comment by ghobona** [comment]
An example implementation is at https://ogcie.iblsoft.com/edr/collections/GFS_0-isoterm

Scroll to the bottom of the page to see the parameter descriptions.

**Comment by KathiSchleidt** [comment]
Could somebody clarify if the [parameter definition](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/parameter.yaml) being discussed here will be in a normative or informative part of the standard.
To date, I've only seen in the informative annexes.

**Comment by chris-little** [comment]
@KathiSchleidt `the parameter definition` is normative, and the broken renamed links have been fixed.
EDR API SWG 46 agreed to close

**Comment by hylkevds** [comment]
Please point to where the normative description is, that defines how the values that go into this parameter called "parameter-name" can be found. If that description does not exist, then please re-open.

**Comment by chris-little** [comment]
@hylkevds The `parameter-name` is a required OpenAPI parameter, but the content can be whatever the service provider chooses, such as `temperature` or `温度`. The `parameter-name` format [requirement](http://docs.opengeospatial.org/DRAFTS/19-086.html#req_edr_parameters-definition) is specified by a schema fragment.

`Each resource collection operation SHALL support a parameter parameter-name with the following characteristics (using an OpenAPI Specification 3.0 fragment):`

> name: parameter-name
in: query
required: true
explode: false
schema:
      minItems: 1
      type: array
      items:
            type: string

**Comment by hylkevds** [comment]
Yes, and that in no way explain to the user (be it a human or software) what those values are, or mean. THAT needs to be exposed in way that is described normatively.

**Comment by KathiSchleidt** [comment]
@chris-little we're not discussing the operations schema, we're discussing the schema used to describe the structure of the parameter description in the collection, the [parameter definition YAML](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/parameter.yaml) referenced by @tomkralidis above.

In the draft version, this structure was only available as an example collection landing page in an informative annex. Now you claim that this structure, directly adopted from CovJSON, is normative. Please clarify
