### ISSUE TITLE
address OGC Web API Guidelines

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#248]
Assess EDR API against the [OGC Web API Guidelines](https://github.com/opengeospatial/OGC-Web-API-Guidelines).

cc @solson-nws @chris-little

**Comment by tomkralidis** [comment]
First pass at https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/wiki/OGC-Web-API-Guidelines

**Comment by chris-little** [comment]
Feedback will be given to the Web API Guideline's authors on Monday 15 March 2021.
The guidelines seem good, and the process of filling in a "checklist" not onerous.

We may have to append this to the candidate standard, or preferab,ly, publish on the GitHub.

**Comment by tomkralidis** [comment]
Content moved from wiki to repo in PR #262

**Comment by tomkralidis** [comment]
Update: I met with @securedimensions and @fterpstra on 2021-03-29 who provided fulsome and valuable feedback based on [our checklist](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/ogc-web-api-guidelines-checklist.md), summarized below:

- Principle 3
  - clarify CoverageJSON IANA status (proposed, etc.)?
- Principle 5
  - add support HTTP POST
    - helps with URL truncation
    - helps with security (to send sensitive data)
  - add support for HTTP OPTIONS
    - required for CORS/preflight
- Principle 8
  - copy/paste list into our checklist
  - add 401 (authorization) and 403 (authentication)
- Principle 10
  - actually complete (currently not addressed)
- Principle 14
  - explicitly do NOT support HTTP
    - privacy issues
    - insecure communication
  -  elaborate on HTTP POST as an additional security mechanism
- Principle 23
  - add examples of successful requests in link relations

**Comment by chris-little** [comment]
@tomkralidis @m-burgoyne I have updated the Guidelines check list in the editorial branch with the above comments, except Principle 23. 
Could we point to some examples please?

**Comment by tomkralidis** [comment]
PR issued in #287
