### ISSUE TITLE
What is the definition of spatiotemporal (or Environmental) data

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#250]
ISO defines a spatiotemporal object: `object representing a set of direct positions in spaceand time` [ISO19123]

OGC uses this, and derivations, rather than separate definitions.

Cannot find any definition for `spatiotemporal data`

How about: 
`spatiotemporal data: data associated with a 4D position in space-time`

**Comment by KathiSchleidt** [comment]
What worries me is that while `data ` is inherently plural, `a 4D position in space-time` is singular
Alternatives:

- data associated with a set of direct positions in space and time [riffing off ISO19123]
- Spatiotemporal data are data that relate to both space and time. [stolen from https://www.sciencedirect.com/topics/computer-science/spatiotemporal-data]

**Comment by dr-shorthair** [comment]
Arguing about 'data' as a plural or singular is just the pompous last gasps of the classicists that held the administrative positions in the now defunct British Empire.

**Comment by chris-little** [comment]
@KathiSchleidt Actually, `data` was intended to be plural - there are often lots of pieces of data, or datums whatever, for a given 4D position. The classic 5 of meteorology: pressure, temperature, humidity and wind speed and direction, for example.

I was not sure about the `set of`. I removed it to ensure there is a strong connection for piece(s) of data to a position. If there is/are a lot of data and a set 4D positions, there is room for fudging, at least in English.

**Comment by chris-little** [comment]
EDR API SWG 46 suggested spatiotemporal data: `data associated with a position in space-time`

**Comment by chris-little** [comment]
EDR APAI SWG 46 close when PR #252 merged
