### ISSUE TITLE
Minor typo: -f parameter

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#256]
Minor typo in Requirement 16 note

![Screenshot 2021-03-16 at 13 04 31](https://user-images.githubusercontent.com/18121038/111313509-5bc7d900-8658-11eb-900f-4001b18e30c6.png)

**Comment by m-burgoyne** [comment]
Fix added to pull request #245

**Comment by chris-little** [comment]
PR merged
