### ISSUE TITLE
Minor typo: /req/instances/rc-md-success

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#259]
Abstract Test 93 references `/req/instances/rc-md-success`. However, that Requirement does not appear to exist.

**Comment by chris-little** [comment]
@ghobona Thank You. Correction will be added to existing PR. Will close when merged

**Comment by m-burgoyne** [comment]
Fix added to PR #245

**Comment by chris-little** [comment]
PR #245 merged
