### ISSUE TITLE
parameter-name yaml schema normative or informative?

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/ogcapi-environmental-data-retrieval#266]
As the statements made in various issues are contradictory, here once more the question of if the parameter-name yaml schemas are normative or informative?

In **[#242](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/242#issuecomment-800563463)** there is a statement on the mandatory nature, but seemingly referring to the parameter-name in the query (based on the yaml fragment posted there), while the discussion had originally been on the parameter-name structure in the collections landing page, see a bit further up **[#242](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/242#issuecomment-790551737)**

The most current answer is a definite maybe, [I think the answer to your question is Yes.](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/223#issuecomment-801093650)

So, could anybody clarify if the various yaml schemas posted in the [schemas directory](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/candidate-standard/openapi/schemas) and actually subtly defining a data model (just not expressed in UML, only in yaml fragments) will be a normative part of the standard, or an informative good practice?

**Comment by chris-little** [comment]
@KathiSchleidt Why don't we say that `various yaml schemas posted in the schemas directory and actually subtly defining a data model` are normative? The technical content of the standard has been frozen since the Planning Committee unanimous vote of approval.
Obviously, there may be some YAML fragments that specify optional attributes. For example a `z` is not required for a 2D Trajectory or Area.

Can we close this issue please?

**Comment by cportele** [comment]
@chris-little - The "why don't we say"-part of following statement does not make sense to me:

> Why don't we say that various yaml schemas posted in the schemas directory and actually subtly defining a data model are normative?

Only those parts of schema documents are normative that are part of a requirement or recommendation. Where that is not the case, the schema fragments are informative. You cannot call something normative, if it isn't. Reading the requirements and recommendations will clarify, which schema definitions are normative and which are not.

And if a schema fragment is only referenced from a recommendation, it will not be relevant for CITE as these tests only test the requirements.

**Comment by chris-little** [comment]
@cportele Thank you for expressing, much more precisely and unambiguously in English than I could, that some parts of the standard are normative and some are not.

**Comment by KathiSchleidt** [comment]
Ah yes, speed kills! ;) Guess this is what happens when one puts an incomplete standard to vote (as seen by the serious activity here since the votes), but to each their own

**Comment by chris-little** [comment]
Thank you.
