### ISSUE TITLE
Conformance Chapter 3 does not clearly list the 9 conformance classes

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#270]
The 9 conformance classes are listed in Annex B. Should each be described in Chapter 3? The missing ones are: JSON, EDRGeoJSON, CoverageJSON.
Also, do we need a separate EDRGeoJSON conformance class from the GeoJSON conformance class?

**Comment by ghobona** [comment]
@chris-little At this stage the edits should be minor. Describing the conformance classes, with a brief paragraph, would be minor. However, separating out the EDRGeoJSON conformance class could be a major edit.

**Comment by chris-little** [comment]
@ghobona Thanks. I'll prepare a PR for clarifying the conformance classes. We will discuss the EDRGeoJSON conformance in the SWG on Friday

**Comment by chris-little** [comment]
@ghobona The EDRGeoJSON conformance class is needed in addtion to the GeoJSON calss, so there are no major edits to be made.

**Comment by KathiSchleidt** [comment]
Do I read this correctly that a CoverageJSON conformance class will be added to the final version of the standard? Would have expected something of this impact in the review version!

**Comment by chris-little** [comment]
@KathiSchleidt It is already there, and has been since the beginning. it is an optional conformance class.

**Comment by KathiSchleidt** [comment]
@chris-little : Interesting how CoverageJSON can be referenced without a reference, as all references currently dead-end in broken links. As a [CovJSON Schema](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/schemas/coverageJSON.yaml) does seem to be part of the standard, I would expect this to be somehow linked.
Assuming such integrated schemas will become visible in the final version of the standard (though to my view should be subject to some sort of review)

**Comment by chris-little** [comment]
@KathiSchleidt The CoverageJSON schema is given as an optional example. It is not mandated, and is unneccessary if an implementation is returning, for example a NetCDF  or GRIB or any other kind of file payload. It is referenced from the References secion, but of course it is not a _de _jure__ standard.

We think most of the broken links have been fixed, but of course some point to OGC API-Common which is not yet fully extant, and similarly for some other OGC links There should be fixed in the OGC Staff editing process. 

As the technical content has been frozen since the Planning Committee unanimous vote in favour, and only minor editorial changes allowed, do you have any to suggest please? Or any proposal for future work?

Otherwise we would like to close this issue to concentrate on publication and testing of implementations against the spec.

**Comment by KathiSchleidt** [comment]
@chris-little as I've lost too much time looking for readable document versions, and not really in the mood to search through the various fragments on github, I wish you all (and your users) the best of luck
