### ISSUE TITLE
Consider hanging EDR processes off a different endpoint ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-environmental-data-retrieval#276]
I informally maintain an HTML page titled **_OGC API Resource Tree_** here: https://www.pvretano.com/Projects/ogcapitree/.  

I recently updated the tree to include the EDR endpoints.

The issue I see is that these endpoints are just hanging off the `/collection/{collectionId}` endpoint without any context.  An even more pressing issue is that the names used for EDR processes are fairly common in this domain thus increasing the possibility of name collisions with other OGC API modules.

```
/collections
 |
 |
 +- /{collectionId}
    |
    |
    +- /position
    |
    +- /area
    |
    +- /cube
    |
    +- /trajectory
    |
    +- /corridor
    |
    +- /locations
    |
    +- /instances
    |
    .
    .
    .
```

My modest proposal would be to organise and collect these endpoints under an `edr` subtree.

```
/collections
 |
 |
 +- edr
 |  |
 |  +- /{collectionId}
 |     |
 |     |
 |     +- /position
 |     |
 |     +- /area
 |     |
 |     +- /cube
 |     |
 |     +- /trajectory
 |     |
 |     +- /corridor
 |     |
 |     +- /locations
 |     |
 |     +- /instances
 |     |
 .     .
 .     .
 .     .
```

My **BOLD**, alternate, proposal would be to introduce the concept of "libraries" to the OGC API Processes specification and say that the EDR endpoints should be hung off  the `/collections/{collectionId}/processes/edr/...` subtree where `edr` is the library name.  However, this is probably a bridge too far at this time! ;)

**Comment by ghobona** [comment]
@pvretano Thanks for the feedback.

Version 1.0 of the EDR API has been approved by the TC & PC. There are at least 5 implementations that I am aware of and an ETS that is at an advanced stage. Reorganising the structure of the paths would be a major change, potentially requiring re-validation in sprints. Such a change would set the API back by possibly a year (based on experiences with other APIs).

**Comment by pvretano** [comment]
@ghobona the modest proposal is to put one path element between {collectionId} and each EDR process just to add some context to these processes rather than them just hanging out there.  Would that been too much of a "breaking" change at this point?  Does not seem like it to me but I completely understand if the issue is tabled until a future release or rejected.  My apologies for not raising this earlier.

**Comment by ghobona** [comment]
@pvretano Yes, I see it as a major change that would require validation.

**Comment by chris-little** [comment]
EDR API SWG 50 agreed to close as too much work, too late, and conflicts with other APIs and interoperability
