### ISSUE TITLE
Open API example is broken

### ISSUE THREAD

**Issue by jwovens** [opengeospatial/ogcapi-environmental-data-retrieval#277]
https://opengeospatial.github.io/ogcapi-environmental-data-retrieval/docs/edr_api.html is broken.  I was finding it quite useful.  Thanks, Jim.

**Comment by alaisslx** [comment]
There is a Diff fragment in [line 861 of the EDR_OpenAPI.yaml file](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/openapi/EDR_OpenAPI.yaml#L861:L868)

**Comment by chris-little** [comment]
@jwovens @alaisslx Thank you for spotting this. PR reviewed and merged.
