### ISSUE TITLE
Position query - Confusing example of the 'coords' parameter

### ISSUE THREAD

**Issue by pnovotny-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#282]
The specification says that there are the following options to specify the `coords` parameter:
* To retrieve a single location:
`POINT(x y)`
* And for a list of locations:
`MULTIPOINT((x y),(x1 y1),(x2 y2),(x3 y3))`
* And for a list of locations **at defined heights**:
`MULTIPOINT((x y),(x1 y1),(x2 y2),(x3 y3))`

The last option is confusing, because it mentions **heights** that are **not specified by the `coords`** parameter in fact - rather, the height is specified by the separate `z` parameter. Thus, I suggest to drop the third option from the specification.

**Comment by chris-little** [comment]
@pnovotny-ibl This is fixed in PR#208
