### ISSUE TITLE
Position query - Swapped coordinates in the 'MULTIPOINT' example

### ISSUE THREAD

**Issue by pnovotny-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#283]
There is the following example of the `coords` parameter in the Position query:
> Example 2. Multiple locations
Retrieve data for a list of locations: 38.9N 77W, 48.85N 2.35E, 39.92N 116.38E, 35.29S 149.1E, 51.5N 0.1W:
`coords=MULTIPOINT((38.9 -77),(48.85 2.35),(39.92 116.38),(-35.29 149.1),(51.5 -0.1))`

The coordinates are swapped - longitude should be the first coordinate if WGS84 is assumed (to be consistent with the previous example `coords=POINT(0 51.48)` for Greenwich, London).

**Comment by chris-little** [comment]
@pnovotny-ibl @m-burgoyne @tomkralidis So, should the example read as below? 

`Example 2. Multiple locations`
`Retrieve data for a list of locations: 38.9N 77W, 48.85N 2.35E, 39.92N 116.38E, 35.29S 149.1E, 51.5N 0.1W:`
`coords=MULTIPOINT((-77 38.9),(2.35 48.85),(116.38 39.92),(149.1 -35.29),(-0.1 51.5))`

**Comment by tomkralidis** [comment]
Correct. Also seems to display on https://arthur-e.github.io/Wicket/ as expected.

**Comment by chris-little** [comment]
@pnovotny-ibl @tomkralidis Corrected in place as minor editorial
