### ISSUE TITLE
Annex C: Location of Link Relation register 

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#285]
The OGC-NA maintains a register for link relation types at http://www.opengis.net/def/rel.

In section C.1.1 , please replace https://www.opengis.net/def/rel/ with http://www.opengis.net/def/rel/.

**Comment by chris-little** [comment]
@ghobona Correction in PR

**Comment by chris-little** [comment]
PR#284 now merged
