### ISSUE TITLE
Trajectory and Corridor query - Swapped coordinates in the examples

### ISSUE THREAD

**Issue by pnovotny-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#286]
This issue is similar to #283. There are the following examples for the `coords` parameter in the **Trajectory query**:
>Example 1. A basic surface route
From Bristol to Exeter
`coords=LINESTRING(51.14 -2.98,51.36 -2.87,51.03 -3.15,50.74 -3.48,50.9 -3.36)`

>Example 2. A basic surface route with defined datetime intervals
From Bristol to Exeter
`coords=LINESTRING(51.14 -2.98 0 1560507000,51.36 -2.87 0 1560507600,51.03 -3.15 0 1560508200,50.74 -3.48 0 1560508500,50.9 -3.36 0 1560510240)`

The latitude and longitude coordinates are swapped - longitude should be the first coordinate if WGS84 is assumed, so the examples do not match coordinates of Bristol and Exeter, as declared. The **same issue** is also in examples of the **Corridor query**.

Even if we swap the latitude and longitude values as follows `coords=LINESTRING(-2.98 51.14,-2.87 51.36,-3.15 51.03,-3.48 50.74,-3.36 50.9)`, the route seems to be quite strange - see the picture:
![image](https://user-images.githubusercontent.com/63053940/115859159-14d7bb00-a430-11eb-986d-88a1e839e748.png)

**Comment by chris-little** [comment]
@pnovotny-ibl @m-burgoyne I may have corrupted the route many months ago, when truncating excessive precision coordinates. I propose to replace the string: 
(51.14 -2.98, 51.36 -2.87, 51.03 -3.15, 50.74 -3.48, 50.9 -3.36) 
with:
(-3.53 50.72,-3.35 50.92,-3.11 51.02,-2.85 51.42,-2.59 51.46) 
in all the appropriate places: trajectory and corridor.

**Comment by chris-little** [comment]
@m-burgoyne @pnovotny-ibl And of course, the time coordinates will be, say:
(-3.53 50.72 1560507000,-3.35 50.921560508800,-3.11 51.02 1560510600,-2.85 51.42 1560513600,-2.59 51.46 1560515400)

**Comment by pnovotny-ibl** [comment]
@chris-little @m-burgoyne Now, I have noticed that there is one more mistake in this example (in both Trajectory and Corridor):
`coords=LINESTRING(51.14 -2.98 0 1560507000,51.36 -2.87 0 1560507600,51.03 -3.15 0 1560508200,50.74 -3.48 0 1560508500,50.9 -3.36 0 1560510240)`
Here, `LINESTRING` should be obviously **`LINESTRINGZM`**. Or, alternatively, it could be just **`LINESTRINGM`** if the height values were dropped (as there is always 0).

So, taken all corrections into account, it should look like this:
`coords=LINESTRINGM(-3.53 50.72 1560507000,-3.35 50.92 1560508800,-3.11 51.02 1560510600,-2.85 51.42 1560513600,-2.59 51.46 1560515400)`

**Comment by chris-little** [comment]
@pnovotny-ibl @m-burgoyne @iandruska-ibl  In the examples of Position query, there is also:
`MULTIPOINT((x y z),(x1 y1 z1),(x2 y2 z2),(x3 y3 z3))`
Should this be 
`MULTIPOINTZ((x y z),(x1 y1 z1),(x2 y2 z2),(x3 y3 z3))` 
or is it common practice to use the different syntax to identify the 3D case?
It is perhaps best practice to be explicit, and consistent.

**Comment by m-burgoyne** [comment]
@chris-little  you are correct it should be MULTIPOINTZ, see section 7.2 of the [Simple Feature Access specification](https://portal.ogc.org/files/?artifact_id=25355)

**Comment by chris-little** [comment]
@m-burgoyne @iandruska-ibl @pnovotny-ibl Two PR created to correct the trajectory and corridor examples

**Comment by chris-little** [comment]
@m-burgoyne MULTIPOINTZ examples updated in place in Master branch

**Comment by chris-little** [comment]
Merged PR #289 and #290
