### ISSUE TITLE
update implementations documentation

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#294]
Update our current [implementations documentation](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/implementations.md) in the same manner as implemented in the [OGC API - Features GitHub repository](https://github.com/opengeospatial/ogcapi-features/tree/master/implementations).

**Comment by tomkralidis** [comment]
Thanks @iandruska-ibl can you provide the name of the product and a link to its OGC products page?  I can update my fork/branch thereafter.  See https://github.com/tomkralidis/ogcapi-environmental-data-retrieval/tree/update-implementations-pages/implementations#servers for the example filled in for pygeoapi.

**Comment by iandruska-ibl** [comment]
@tomkralidis The name of the product is Open Weather (https://www.iblsoft.com/products/open-weather). It is not a certified OGC product yet so it is not listed on the OGC products page.

**Comment by ghobona** [comment]
I have just sent @iandruska-ibl a [link to the product registration page](https://www.ogc.org/resource/products/registration).

**Comment by iandruska-ibl** [comment]
@tomkralidis Finally, I have registered Open Weather: https://www.ogc.org/resource/products/details/?pid=1684.
