### ISSUE TITLE
bbox-crs vs. crs parameter

### ISSUE THREAD

**Issue by iandruska-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#297]
[`bbox` parameter specification](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/requirements/core/REQ_rc-bbox-response.adoc) used in Cube query refers to to `bbox-crs` parameter. However, [Cube query specification](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/requirements/edr/REQ_rc-cube.adoc) does not include the `bbox-crs` parameter. It includes only `crs` parameter. Which parameter actually applies to cube query, `crs` or `bbox-crs`?

**Comment by m-burgoyne** [comment]
It should be `crs`,  in EDR the `crs` query parameter defines both the coordinate reference system of the output data and the coordinate reference system of the `bbox` and `coords` query parameters.

**Comment by iandruska-ibl** [comment]
This leads me to another issue. The default value of `crs` parameter is not defined consistently in the specs.
1. [Specification of `coords` parameter](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/requirements/edr/REQ_rc-coords-response.adoc) states that the default is WGS 84
2. [Specification of `crs` parameter](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/requirements/edr/REQ_rc-crs-response.adoc) states that the default is native CRS of the data.

**Comment by m-burgoyne** [comment]
The intention was to recommend that a data provider should provide WGS84 as a default but that if the `crs` query parameter is not defined the interpretation of the values of the `coords` will default to the native CRS of the data.

**Comment by dblodgett-usgs** [comment]
Fixed in #299
