### ISSUE TITLE
Publishing ogcapi EDR 1.0.0 schema

### ISSUE THREAD

**Issue by kstegemoller** [opengeospatial/ogcapi-environmental-data-retrieval#298]
I am working to publish the schemas for OGC API EDR 1.0 and ran into an inconsistency.

Is locationId replacing locId in 1.0.0?  If so, then the master branch schemas appear more up to date than the schemas in tags/1.0.0-draft.1.  Also if so, should the ogcapi/parameters/locId.yaml be renamed locationId.yaml?

The current DRAFT 
https://docs.ogc.org/DRAFTS/19-086.html 
appears to support those conclusions.

**Comment by ghobona** [comment]
**Is locationId replacing locId in 1.0.0?**

Yes, locationId is the name to use.

Please ignore the document at https://docs.ogc.org/DRAFTS/19-086.html

The spec has now been converted to Metanorma, processed and can be found at https://portal.ogc.org/files/?artifact_id=97581


**should the ogcapi/parameters/locId.yaml be renamed locationId.yaml?**

The filename should not have an effect on the on parameter names. So the filename can be left as locId.yaml. Isn't that right @m-burgoyne ?

**Comment by m-burgoyne** [comment]
@ghobona You are correct the filename can be left as locId.yaml, as long as the ref entries which refer to the file in the main 
EDR_OpenAPI.yaml  file are not changed.  It is the contents of the locId.yaml file that must refer to  locationId not the file name.

**Comment by chris-little** [comment]
@kstegemoller Are you happy to close this issue?

**Comment by kstegemoller** [comment]
Sounds good.  I will use the master branch version (79f64d7) of the candidate-standard/openapi directory as the base.

Trying to post
http://schemas.opengis.net/ogcapi/edr/1.0/openapi/EDR_OpenAPI.yaml

Should replace in EDR_OpenAPI.yaml "https://raw.githubusercontent.com/opengeospatial/ogcapi-common/master/collections/openapi/"

but with what since ogcapi-common isn't finalized?

Proposed ogcapi-common URL? http://schemas.opengis.net/ogcapi/common/1.0/collections/openapi/parameters/datetime.yaml

If we leave the githubusercontent, then we will need to update the EDR schema to version 1.0.1 when common is posted and the githubusercontent URL is changed.

So the question is use the githubusercontent URL now and update the version to 1.0.1 and URL once ogcapi-common is published or put the correct URL now?

**Comment by ghobona** [comment]
@kstegemoller We previously agreed to place the draft OGC API - Common schemas in the Beta Schemas site.

**Comment by ghobona** [comment]
@kstegemoller Therefore it would be http://beta.schemas.opengis.net/ogcapi/common/part1/0.1/collections/openapi/parameters/datetime.yaml

Notice that there is 'part1' segment.

Please also note the '0.1' version number. This is to avoid confusing developers once version 1.0 is released.

**Comment by kstegemoller** [comment]
OGC API EDR 1.0 posted to
http://schemas.opengis.net/ogcapi/edr/1.0/openapi/

I published OGC API Core (part1) and Collections (Part2)as-is to the beta.schemas.opengis.net -- straight from the master branch.
They will only be updated upon manual request to @kstegemoller.

* OGC API Part 1 - Core - version BETA
    https://github.com/opengeospatial/ogcapi-common/tree/master/core/openapi
    http://beta.schemas.opengis.net/ogcapi/common/part1/0.1/core/openapi/

* OGC API Part 2 - Collections - version BETA
    https://github.com/opengeospatial/ogcapi-common/tree/master/collections/openapi
    http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/
