### ISSUE TITLE
does `datetime` parameter support ISO8601 time intervals?

### ISSUE THREAD

**Issue by 7yl4r** [opengeospatial/ogcapi-environmental-data-retrieval#311]
Can a request within this spec span a time interval using [ISO8601 time intervals](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals)? Example: `"2007-03-01T13:00:00Z/2008-05-11T15:30:00Z"`

Would this return a data matrix with time as one of the axes or would it aggregate over time using a mean or similar?

**Comment by m-burgoyne** [comment]
The spec does support requesting data using a [ISO8601 time intervals](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) as well as [repeating intervals](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals),  this would return a data matrix with time as one of the axes.

**Comment by 7yl4r** [comment]
Very cool. Thank you. I am curious what such a request would mean exactly regarding aggregations or summations but that is probably best left up to the implementations to decide for now.

Looking now under 8.2.1.2 in [the spec](https://docs.ogc.org/is/19-086r4/19-086r4.html#toc28) I do see mention of interval datetimes. It looks quite clear I must have just missed it the first time around.

**Comment by chris-little** [comment]
@7yl4r The need for aggregatiions and statistical functions has been identified, and we agreed to tackle them in version 1.1. But first,  we wanted to be confident that Versi0n 1.0 was on the correct track. So watch this space, or join in!  We would probably tackle those functions that could be easily pre-computed first, so thresholding, that possibly requires a POST value probably would be a separate requirement.

Thanks for closing the issue.
