### ISSUE TITLE
Support for HTTP POST

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#316]
This could be useful/necessary for coords parameters with large geometries, using POST could also allow for large geometries to be provided by existing binary sources such as Shapefiles and GeoPackages.

**Comment by iandruska-ibl** [comment]
This is definitely useful. We constantly keep hitting the URL length limit. Especially when URLs are automatically generated. Not only large geometries are problematic, but also long lists of irregularly spaced vertical levels or time coordinates (need to enumerate coordinates, impossible to utilize sequences)

**Comment by m-burgoyne** [comment]
Whilst I understand the desire to have HTTP POST behave in a similar way to other OGC APIs, this approach would add extra steps and complication to server and client implementations and have to be explained in the documentation (and would be difficult to describe in an OpenAPI definition).  POST of form encoded data is a well understood pattern and would keep the API simple.

**Comment by dblodgett-usgs** [comment]
I agree in concept, but if we allow this to go forward it is enabling an anti pattern that will allow (require) http connections to be held open and make systems that use the API more fragile. 

This is my main concern here -- EDR can not become known as the API that has requests that might time out unexpectedly. Making sure that the API fosters good design and scalability is really important. 

What we are talking about here _is_ executing a process on the back end. EDR is in a grey area between dynamically generated resource and custom process specification. While I'm ok with flexibility in the GET query parameters that allows very large requests, taking this step is too much. Once your request body is large enough to not fit in a URL, IMHO, it needs to be handled as a process. We could adopt the same semantics as OGC API Processes if documentation is an issue?

**Comment by m-burgoyne** [comment]
This would be true of the GET requests as well and is the argument for implementing asynchronous requests.  It could be handled by returning a 308 status message and returning a URL to to location of the result.   The amount of information in the form is not the only indicator of effort required to process the request, the request performance will be a combination of query type, query values and the structure of the underlying data.

**Comment by dblodgett-usgs** [comment]
Right, I basically stated that at the end of my last comming...

> While I'm ok with flexibility in the GET query parameters that allows very large requests, taking this step is too much. Once your request body is large enough to not fit in a URL, IMHO, it needs to be handled as a process. 

I guess I'd point back to 

> EDR API SWG#64 agreed experimentation, more investigation and explicit examples needed.

and lump asynchronous support into the need to experiment. I have some work starting up now with @ShaneMill1 and others where we could do some experimentation.

**Comment by dblodgett-usgs** [comment]
In conversation with @tomkralidis, another argument to support POST is the ability to encrypt the request body no-matter the size. 

With that use-case in mind, I am more open to pursuing this as an option.

**Comment by tomkralidis** [comment]
+1 for HTTP POST, this was discussed during our API review against the [OGC Web API Guidelines](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/248).

**Comment by chris-little** [comment]
@m-burgoyne @ShaneMill1 Will try to demonstrate HTTP POST by the end of April 2022.
Agreed that this may need asychronous handling at the same time for scalability. This will be raised as a separate issue, possibly for V1.2 and experimented and experience gained.

**Comment by solson-nws** [comment]
HTTP POST testing was done during the recent Partitions Code Sprint.  Results are posted on the MetOcean DWG github wiki at:  [(https://github.com/opengeospatial/MetOceanDWG/wiki/EDR-API-v.1.1.0-POST-Testing
)]

**Comment by dblodgett-usgs** [comment]
Fixed by #390 -- review of changes for this will happen there.

**Comment by chris-little** [comment]
Text of spec needs more explanation and highlighting of the new functionality. Schemas/YAML believed correct. Wehn text improved, will submit to OAB.

**Comment by chris-little** [comment]
V1.1 passed OAB review, public comment period and is now in final approval vote from the OGC Technical Committee, closing at the beginning of June 2023.

**Comment by chris-little** [comment]
V1.1 was approved and is being published in July 2023.
