### ISSUE TITLE
Add query support for subsetting by Ensemble members

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#317]
Ensemble datasets are datasets that consist of a number of equally probable realizations which aim to give a measure of the uncertainty in the data fields; such datasets are common the data science domain.  

To provide support for ensemble queries would require:

1. Enhancing the Collections/Instances metadata to provide information about the available ensemble members
2. Add a query parameter to allow subsetting  by the members dimension.

**Comment by iandruska-ibl** [comment]
For inspiration, this is how we extended our implementation to support ensembles:
```
      "extent": {
        "spatial": {
          "bbox": [
            0,
            -90,
            359,
            90
          ],
          "crs": "GEOGCS[\"Unknown\", DATUM[\"Unknown\", SPHEROID[\"WGS_1984\", 6378137.0, 298.257223563]], PRIMEM[\"Greenwich\",0], UNIT[\"degree\", 0.017453], AXIS[\"Lon\", EAST], AXIS[\"Lat\", NORTH]]",
          "_projString": "+proj=longlat +lon_0=180 +R=6371229"
        },
        "vertical": {
          "interval": [
            "10"
          ],
          "vrs": "ibl#meters"
        },
        "temporal": {
          "interval": [
            "2017-06-14T00:00:00Z",
            "2017-06-14T06:00:00Z",
            "2017-06-14T12:00:00Z",
            ...
          ],
          "trs": "TIMECRS[\"DateTime\",TDATUM[\"Gregorian Calendar\"],CS[TemporalDateTime,1],AXIS[\"Time (T)\",future]"
        },
        "realisations": [
          1,
          2,
          3,
          4,
          ...
        ]
      },
```
We introduced a new dimension called `realisations` (https://en.wikipedia.org/wiki/Realization_(probability)). Coordinates can be either integers or strings, whichever is more convenient in particular scenario.

Next we added a query parameter called `realisation` which allows subsetting. For example:
`https://myserver/collections/GFS/position?parameter-name=temperature&realisation=1,3,5,7`.

When `realisation` parameter is not specified, all ensemble members are returned. Thus backward compatibility is preserved.

**Comment by chris-little** [comment]
@m-burgoyne @iandruska-ibl What are the advantages of `realisation` over `instance`? Can't we use existing instances to retrieve ensemble members?

**Comment by m-burgoyne** [comment]
@chris-little Instances could be used, but then it would not be possible to use instance to access different runs of the ensemble model, it would also not allow subsetting by ensemble member.

**Comment by m-burgoyne** [comment]
replaced by issue #338
