### ISSUE TITLE
Add support for Pub/Sub to inform subscribers of data updates  

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#318]
Pub/Sub could be used to provide an approach to inform users when the data provided by a collection has changed.  Allowing users to subscribe to changes in the collection metadata could make applications more efficient and responsive by removing the need to repeatedly poll the collections endpoint.  OGC guidance on Pub/Sub can be found here: [OGC Publish-Subscribe White Paper](https://docs.opengeospatial.org/DRAFTS/20-046.html)

**Comment by chris-little** [comment]
This is a long term requirement dependent on many other moving pieces, such as underlying transport layer MQTT, and whether applied to data or metadata, and asynchronous approaches. Add to the post-V1.1 roadmap.

**Comment by tomkralidis** [comment]
Note that this is also being [discussed](https://github.com/opengeospatial/ogcapi-records/issues/111) in OGC API - Records.  In addition, PubSub is being discussed in WMO circles for event-driven data exchange.

Having said this, possible options include (but are not limited to):
- standard messaging protocols, such as MQTT or AMQP
- OpenAPI callbacks
- loosely related: [AsyncAPI](https://www.asyncapi.com)

At first glance, not sure if/how the above can be used together/combined.

**Comment by jkreft-usgs** [comment]
This would be very shiny.  Ideally integration with sensorthings would be part of this work as well

**Comment by m-burgoyne** [comment]
Rather than specifying the technology the EDR standard could take the approach that EDR services would use the [AsyncAPI](https://www.asyncapi.com/) standard to define their pub/sub capabilities and technology choices.

**Comment by chris-little** [comment]
There is work ongoing in OGC, with an Engineering Report on Async behaviour of APIs, to be published later this year, and this may be be relevant too.

**Comment by dblodgett-usgs** [comment]
To be worked at [pubsub sprint](https://www.ogc.org/ogcevents/2022-joint-ogc-isotc-211-code-sprint-aka-metadata-code-sprint)

**Comment by chris-little** [comment]
EDR API SWG 107 agreed to close has now superceded by establishment of PUBSUB SWG and API EDR Part 2: PubSub developments.
