### ISSUE TITLE
Recommend STAC item as a best practice template for /locations and /items responses  

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#320]
The SpatioTemporal Asset Catalog (STAC) specification provides a common language to describe geospatial information, [STAC item](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md) is the core atomic unit, representing a single spatiotemporal asset as a GeoJSON feature.  

GeoJSON does not provide any guidance beyond geometry on how metadata should be published, Using STAC item as the recommended template for the `/items` and `/locations` queries would allow EDR to benefit from the work done by the STAC community in defining recommended fields for the GeoJSON properties object.

**Comment by chris-little** [comment]
Awaiting a response from STAC people to API-Records SWG re convergence.
