### ISSUE TITLE
Add an annex listing the aggregation methods for measurementType 

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#321]
The measurementType properties in the `/collections` response allow publishers to define time periods that values represent and how they are  aggregated, but currently the standards document provides no definitions for aggregation methods.

the [CF-NetCDF Cell Methods table](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#appendix-cell-methods) provides a set of definitions that could be used for the purpose.

**Comment by chris-little** [comment]
EDR API SWG 69 agree to add to V1.1

**Comment by chris-little** [comment]
EDR API SWG 73 agreed that this is a best practice, rather than a mandated requirement. Some examplar text in V1.1 would be the way forward.

**Comment by dblodgett-usgs** [comment]
Still outstanding -- will need to add to v1.1 changes.

**Comment by chris-little** [comment]
EDR API SWG 88 agreed as immplementation experience needed, it would not make the V1.1 so now slated for V1.2

**Comment by chris-little** [comment]
Clsoe when Pr#472 resolved into the appropriate branch.
