### ISSUE TITLE
Use the canonical URI http://www.opengis.net/def/crs/OGC/1.3/CRS84 in examples

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#324]
Some Abstract Tests in the Standard use the canonical URI (http://www.opengis.net/def/crs/OGC/1.3/CRS84), whereas some examples in the Standard use the short name **CRS84**.

Ideally, future versions of the standard should state the complete canonical URI in examples, Requirements, and  Abstract Tests. This would avoid any potential ambiguity.

Use of the canonical URI would also be consistent with both OGC API - Common and OGC API - Features.

**Comment by chris-little** [comment]
@ghobona Thaks, we will prepare a PR tpo create a V1.0.1

**Comment by chris-little** [comment]
PR request megerd at EDR API SWG 67
