### ISSUE TITLE
JSON and EDR GeoJSON schemas?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-environmental-data-retrieval#325]
The spec leaves me wondering, where are the json schemas?? 

https://docs.ogc.org/is/19-086r4/19-086r4.html#rc_edr_geojson doesn't help and I can't find any useful links. Am I missing something?

**Comment by chris-little** [comment]
@dblodgett-usgs This will be fixed by adding a page to the web and spec listing all the schemas. See Issue #329.
