### ISSUE TITLE
groups in our schemas?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-environmental-data-retrieval#327]
https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/groups.yaml

That probably shouldn't be in there?

**Comment by chris-little** [comment]
@m-burgoyne Any idea what the /groups endpoint is for?

**Comment by m-burgoyne** [comment]
@chris-little This section should probably be removed, it was originally intended to allow service providers to define a group of collections.  The work on collections of collections will probably make this idea obsolete.

**Comment by chris-little** [comment]
@m-burgoyne Could you prepare a PR against the master branch, V1.0.1, please?

**Comment by m-burgoyne** [comment]
@chris-little New V1.0.1 branch added with groups removed from OpenAPI definitions

**Comment by chris-little** [comment]
Branch created. PR will be created when other changes added. Agreed to close the issue at EDR API SWG #66
