### ISSUE TITLE
Advertise availability of json schemas?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-environmental-data-retrieval#329]
The spec doesn't link to all our schemas. They are all here: http://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/ is this something we should add to the spec and/or should we be embedding links to schemas in documentation?

**Comment by chris-little** [comment]
@dblodgett-usgs Is it easy to summarise which schemas are not linked? I'm assuming they are not indirectly linked by nesting.

**Comment by dblodgett-usgs** [comment]
If you search ".yaml" in the spec, you'll see the ones that are linked. It's not very many. I think we generally missed the need to actively link to the schemas from winthin the spec.

**Comment by chris-little** [comment]
After discussion with @ghobona and @dblodgett-usgs , agreed to add page to web to identify all schemas, then later add to spec v1.0.1.
