### ISSUE TITLE
Missing commas in cube bbox example?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-environmental-data-retrieval#330]
In https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/requirements/edr/query_type/cube.adoc ( _8.2.5.1.  Parameter bbox_ )

> Example 1. A cube covering the South West of the UK
`bbox=-6.0 50.0,-4.35 52.0`

Shouldn't this say:

`bbox=-6.0,50.0,-4.35,52.0`

to properly follow the `bbox=minx,miny,maxx,maxy` pattern?

**Comment by chris-little** [comment]
@jerstlouis Well spotted. Now fixed by @tomkralidis PR, now merged.
