### ISSUE TITLE
Change the Coordinate Reference Systems recommendation from must to should

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#340]
Section 9.6 of the documentation states that EDR API's `MUST` support CRS84,  this will not always be possible or even recommend for certain data sources. Changing this to `SHOULD` would still support the best practice need for compatability whilst not preventing use of EDR in those situations where CRS84 is not possible or appropriate for the data being queried.

**Comment by chris-little** [comment]
EDR API SWG 69 agreed NOTUC to the change, and tasked @m-burgoyne with adding the change to the PR

**Comment by m-burgoyne** [comment]
Changes merged in pull request #346
