### ISSUE TITLE
Errors in the OpenAPI schemas

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#352]
The following errors in the OpenAPI definitions were identified by Eugene Genong Yu at the [2022 Joint OGC - OSGeo - ASF Code Sprint](https://www.ogc.org/ogcevents/2022-joint-ogc-osgeo-asf-code-sprint) :

- Invalid `default: {}` value in edrProperties.yaml
- Invalid bbox array items definition

**Comment by ghobona** [comment]
Cc: @eugenegmu

**Comment by chris-little** [comment]
PR addressing these merged at EDR API SWG 73
