### ISSUE TITLE
OAS fragments in Annex A

### ISSUE THREAD

**Issue by kevpax-24** [opengeospatial/ogcapi-environmental-data-retrieval#354]
The following OAS param specification fragments give 'required: true' when I believe they should be 'required: false':
parameter-name (A.2.9)
within (A.2.17) 
corridor-height (A.2.28)
height-units (A.2.30)
corridor-width (A.2.32)
width-units (A.2.30)

Additionally the following fragments appear to be in the wrong requirement subsection:
within (A.2.17)
within-units (A.2.19)

**Comment by chris-little** [comment]
@m-burgoyne @ShaneMill1 @iandruska-ibl FYI

**Comment by m-burgoyne** [comment]
@kevpax-24 @chris-little The `parameter-name` value was incorrect and should be false, but the other values are correct.  They are required but only apply to specific query types (for instance `within` only applies to the Radius query).  As you identified  a requirements class called Core should probably not include requirements for query parameters that do not apply to all of the query types.  I suggest this is added to the refactoring for the 1.0.2 release,  the following are possible approaches we could take:

* Create a new section in Annex A which is dedicated to all query parameter requirements
* Create a new requirements section in Annex A for query parameters that are required for specific query types
* Combine the information for query parameters that are required for specific query types with the query type requirement classes in section A.4

**Comment by kevpax-24** [comment]
Thanks for the explanation. All options look agreeable and I don't feel I have the knowledge to weigh in on them.

In the short-term, updating the requirement text to specify the applicable query type could be a quick fix. For example,  REQ_rc-width-units-definition (A.2.34)  states 'Each corridor resource collection operation...' whereas corridor-width-definition (A.2.32) simply states 'Each resource collection operation...'. I propose the latter is updated to match the former, also updating the other requirements I have listed, with their applicable query types.

**Comment by chris-little** [comment]
Fix identified and PR will be prepared for draft V1.1

**Comment by dblodgett-usgs** [comment]
Fixed in #390 related to #319
