### ISSUE TITLE
Inconsistencies in Cube Query requirements

### ISSUE THREAD

**Issue by kevpax-24** [opengeospatial/ogcapi-environmental-data-retrieval#356]
A.4.4.  /req/edr/rc-cube

C + D specify that 'coords' is required - shouldn't this be 'bbox'?

Additionally, If 'coords' is always mandatory as specified in core (/req/edr/coords-definition) how does this square with bbox requirement? Is this another case where 'coords' is only mandatory for specific queryTypes?

E + F refer to non-existent 'min-z' and 'max-z' parameters.

In addition, /req/core/rc-bbox-definition and /req/core/rc-bbox-response:D describe how 6 numbers can optionally be used to specify min/max depth, however this is contradicted by /req/core/rc-bbox-response:E ("The bounding box SHALL consist of four numbers...") and is not described in 8.2.5.

**Comment by m-burgoyne** [comment]
Thanks @kevpax-24, I have added a pull request to resolve the errors that you have identified in the Cube query

**Comment by chris-little** [comment]
PR merged at EDR API SWG 75 2022-04-27
