### ISSUE TITLE
"patternProperties" appears to be unsupported in OpenAPI 3

### ISSUE THREAD

**Issue by crbunney** [opengeospatial/ogcapi-environmental-data-retrieval#366]
I noticed `patternProperties` in a few schemas (such as [parameterNames.yaml](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/parameterNames.yaml) and [units.yaml](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/units.yaml)) and whilst looking for more information, found this [documentation](https://swagger.io/docs/specification/data-models/keywords/) that states `patternProperties` isn't supported in OpenAPI 3, which is the version used by the EDR OpenAPI definition.

This appears to be corroborated by the [OpenAPI 3.0.3 specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object) for schema objects, which doesn't mention `patternProperties` at all and goes on to state

> Additional properties defined by the JSON Schema specification that are not mentioned here are strictly unsupported

**Comment by chris-little** [comment]
Fixed at EDR API SWG 78 with PR #372
