### ISSUE TITLE
Is parameter-names mandatory or optional?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#370]
[collection.yaml](http://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/collection.yaml) declares:

```yaml
type: object
required:
  - links
  - id
  - extent
  - parameter-names
```

However, Step 6 of Abstract Test 14 says "Verify that **if** the collection entry includes an parameter-names property, the property complies with /req/edr/rc-parameters".

The use of the word 'if' implies that parameter-names is optional. 

Recommended actions:

1. Update the text or the yaml file to clarify whether parameter-names is optional or not.
2. Fix the typo "an parameter-names property" should be "a parameter-names property"

NOTE: The presence of a parameter-names  or parameter_names property is currently (at v1.0.0) the only way to determine whether a collection is an EDR collection or not. So the property is very helpful.

**Comment by chris-little** [comment]
Already Merged. Agreed to close at EDR API SWG76
