### ISSUE TITLE
Add Requirements and Tests to validate the data_queries metadata

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#371]
The data_queries attribute in the collections metadata is essential to describe the query functionality of a collection but is not defined in the requirements or abstract tests

**Comment by ghobona** [comment]
@m-burgoyne Please comment about what will happen to Abstract Test 15 which currently (in v1.0.0) says:

"Verify that the links properties of the collection includes an item for each supported encoding with at least one link to either a query resource (relation: `data`) or instance resource (relation: `collection`)."

**Comment by m-burgoyne** [comment]
@ghobona That test would no longer be needed, but the are new tests needed for the data_queries section

**Comment by chris-little** [comment]
fixed at EDR API SWG 78 with PR #374
