### ISSUE TITLE
distanceunits in collection metadata

### ISSUE THREAD

**Issue by kevpax-24** [opengeospatial/ogcapi-environmental-data-retrieval#376]
/req/edr/rc-collection-info states that collections with a radius query must have a 'distanceunits' parameter containing an array of supported distance units, however the collection.yaml definition does not include this parameter.

Additionally, other sections e.g. /req/edr/within-definition suggest that the parameter should be called 'within-units' (matching the radius query parameter itself): "If the instance metadata does not provide within-units values the API SHALL NOT support within queries"

**Comment by m-burgoyne** [comment]
@kevpax-24 pull request #371 should resolve the issue that you have spotted as it removes the invalid requirements and adds the missing requirements for the data query definitions.

**Comment by chris-little** [comment]
Fixed at EDR API SWG 78 with PR #371
