### ISSUE TITLE
Requirement A.46 K should state 'parameter_names' instead of 'parameter'

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#377]
Requirement A.46 (/req/edr/rc-collection-info) K states that "Every Collection within a collections array MUST have an `parameters` parameter containing a list of parameters must comply with the requirement `/req/edr/rc-parameters`.".

According to [collection.yaml](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/collection.yaml) the parameter should be called 'parameter_names'.

Requirement A.46 (/req/edr/rc-collection-info) K therefore needs to be updated to be in sync with [collection.yaml](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/collection.yaml).

**Comment by m-burgoyne** [comment]
Will be resolved by the changes in pull request #374

**Comment by chris-little** [comment]
Fixed at EDR API SWG 78 with PR #374
