### ISSUE TITLE
Dead Link to OpenAPI Schema on GitHub Pages

### ISSUE THREAD

**Issue by crbunney** [opengeospatial/ogcapi-environmental-data-retrieval#386]
I've found the link to the OpenAPI schema in [docs/edr_api.html](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/docs/edr_api.html) is broken

When it's deployed to [GitHub Pages](https://opengeospatial.github.io/ogcapi-environmental-data-retrieval/docs/edr_api.html) an error occurs: `Failed to load API definition`... `Fetch error. undefined ../standard/openapi/EDR_OpenAPI.yaml`.

I presume the name or location of the file has changed, but I'm not familiar enough with how the pages are built to pinpoint what specifically needs to be changed

**Comment by m-burgoyne** [comment]
Thanks @crbunney that page had been missed when the OpenAPI schema documentation was refactored, the example has been now been updated to reference the new schema definition.

**Comment by crbunney** [comment]
Yep, I can see the page is working again now
