### ISSUE TITLE
Extent values field description incorrect

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#387]
There are errors in the OpenAPI yaml description for the time extent values field:

https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/collections/extent.yaml#L143

   as number of **repeatitions** / **end time** / interval (e.g. R4/2017-11-14T21:00Z/PT3H)

It should be 

   as number of **repetitions** / **start time** / interval (e.g. R4/2017-11-14T21:00Z/PT3H)

**Comment by chris-little** [comment]
Agreed at SWG 2022-06-30 that PR will incorporate this change.

**Comment by chris-little** [comment]
@m-burgoyne Can we close this now?

**Comment by m-burgoyne** [comment]
@chris-little not yet, its fixed in the v1.0.1 branch but not the master branch

**Comment by chris-little** [comment]
EDR API SWG 81 agreed to close
