### ISSUE TITLE
Simplify references to CoverageJSON and its schemas, as now a Community Standard

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#407]
When the CoverageJSON Community Standard is formally published and the CoverageJSON schemas, JSON-LD context files and namespace prefix registry are all at the [OGC Schema Registry](http://schemas.opengis.net) under the /covjson/ folder, we can simplify much of the text.
Should we do this editorial change in V1.2 or later, or earlier?

**Comment by m-burgoyne** [comment]
@chris-little I don't think we can do this until we move to OpenAPI 3.1 (see issue #375), the CoverageJSON schemas rely on features in JSON schema that are not supported by OpenAPI 3.0.x.

**Comment by chris-little** [comment]
CoverageJSON schemas have now been fixed, and are formally in the OGC Shcema reppo with apporpriate IPR, so the move to OpenAPI3.1 is the only constraint. 
Agreed to close at EDR API SWG #98
