### ISSUE TITLE
Improve documentation for definition of response schemas

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#416]
The documentation only states that EDR uses OpenAPI to document a service, update the text for the documentation of the Locations and Items queries to state that the schemas for the Locations and Items responses SHOULD be defined in the OpenAPI definition for the service.  If a Schema is not defined in the OpenAPI responce a client MUST assume that the responses  are based on the edr-geojson schema.

**Comment by chris-little** [comment]
Implemented in PR #417.
Agreed to close EDR API SWG 95.
