### ISSUE TITLE
optional z and bbox query parameters for the /cube endpoint

### ISSUE THREAD

**Issue by Annegies** [opengeospatial/ogcapi-environmental-data-retrieval#418]
In the Environmental Data Retrieval Standard 1.0.1 the cube query must include a bbox and z parameter.
I think it would be more user friendly to make them optional and when empty return the full extent and all available heights.

In the Developer-friendly OpenAPI definitions (Swagger, redoc) it is already so,but that’s not how it is defined in the spec.

**Comment by m-burgoyne** [comment]
This problem should be resolved in [v1.1](https://opengeospatial.github.io/ogcna-auto-review/19-086r6.html) of the specification, it has been updated to bring the documentation in line with the OpenAPI definitions

**Comment by chris-little** [comment]
@Annegies I agree that a "no parameters" default is more user friendly. But we have discussed these options at length, and as many collections that are likely to be queried are Terabytes or even Petabytes in size, the response will certainly be failed by API management software. Such a query could also be construed as a DOS attack.
The primary use case is to retrieve manageable amounts of data from large dataset resources that are impractible to move on a reasonable timescale.
The EDR API already allows retrieval of all levels if `z` is not specified, for some query patterns. Whether such an approach is feasible for temporal extent or horizontal spatial extent is up to service provider and their resource.

**Comment by chris-little** [comment]
@m-burgoyne will update the V1.0.1 documentto V1.0.2 to correspond with V1.1.

**Comment by chris-little** [comment]
@Annegies Do these responses resolve your issue so that it can be closed?

**Comment by chris-little** [comment]
@Annegies This has been fixed in V1.1 by correcting the text to be consistent.

Are you happy to close this issue please?

**Comment by chris-little** [comment]
V1.1 has been approved, final editorial changes finished, and is being published July 2023.
