### ISSUE TITLE
Update URIs to reflect v1.1

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#419]
The following updates are needed to prepare v1.1 for approval and release.

The external identifier on the cover page should be changed from http://www.opengis.net/doc/IS/ogcapi-edr-1/1.0 to http://www.opengis.net/doc/IS/ogcapi-edr-1/1.1

The base URI of the specification elements should be changed from http://www.opengis.net/spec/ogcapi-edr-1/1.0 to http://www.opengis.net/spec/ogcapi-edr-1/1.1

**Comment by chris-little** [comment]
@ghobona I have prepared PR #424 to change the Base URI, but I have no idea where the  Cover Page content asctually is in this repo!

**Comment by chris-little** [comment]
@ghobona I changed all the appropriate occurences of 086r4/5 to 086r6, and V1.0 to V1.1 that I could find, but the external reference on the title page still out of date. No idea where that piece of source is.

**Comment by chris-little** [comment]
Corrected 2023-05-18
