### ISSUE TITLE
OpenAPI spec of CoverageJSON's coverage domain type is missing a datatype

### ISSUE THREAD

**Issue by petergarnaes** [opengeospatial/ogcapi-environmental-data-retrieval#420]
As stated in the [OpenAPI specification for enums](https://swagger.io/docs/specification/data-models/enums/), an enum schema must contain a `type: string` for an enum of textual values. This is not the case in the CoverageJSON OpenAPI spec, as seen [here on version 1.0.1](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/1.0.1-final/standard/openapi/schemas/coverageJSON.yaml#L8-L13). This is causing issues for software like swagger-codegen.

**Comment by chris-little** [comment]
@jonblower @m-burgoyne Is this an EDR API omission or a CoverageJSON one? Or something else?

**Comment by m-burgoyne** [comment]
@chris-little Its an error in the EDR schema definition

**Comment by chris-little** [comment]
@m-burgoyne So do we need a PR for V1.0.1/2

**Comment by m-burgoyne** [comment]
@chris-little Yes, the same change will need to be made to the v1.0.2 branch

**Comment by chris-little** [comment]
@petergarnaes The schema has now been changed in the V1.1 version, and a potential V1.0.2 for the original version.

Are you happy to close this issue, please?

**Comment by chris-little** [comment]
@petergarnaes The formal vote to approve V1.1 closes in two weeks. Providing this succeeds, the V1.0.2 will be abandoned, as V1.1 is completely backward compatible.
Currently the vote is 15 Yes, 6 Abstain, 0 No. 
10 more votes of any kind out of 70 are needed to pass. So I will close when the the Technical Committee has approved V1.1.

**Comment by chris-little** [comment]
@petergarnaes V1.1 was approved in Huntsville at the beginning of June 2023, and is now just finishing final editorial changes. Formal publication will be later this month, July 2023, after press releases, etc. The GitHub repo master branch has been tagged V1.1.0, so closing this issue.
