### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by smguru** [opengeospatial/ogcapi-environmental-data-retrieval#425]
Hello,
The following URLs are not working
Landing page: https://data-api.mdl.nws.noaa.gov/EDR-API
OpenAPI document (Swagger): https://data-api.mdl.nws.noaa.gov/EDR-API/api?f=html

**Comment by chris-little** [comment]
@ShaneMill1 FYI.

**Comment by smguru** [comment]
@chris-little, is there any timeline to ix the URL? None of the example URLs are working.

**Comment by chris-little** [comment]
@smguru I've asked @ShaneMill1 who is the API-EDR developer in NOAA

**Comment by chris-little** [comment]
@ShaneMill1 Something for your inbox! Hope you had a good holiday/honeymoon.

**Comment by ways** [comment]
Shane Mill replied me with:

> We unfortunately do not have a publicly available EDR-API prototype at this time so that website is unreachable.

I think the link should be removed.

**Comment by chris-little** [comment]
@smguru @ShaneMill1 I have added a comment that the implementation isnot publicly available, so will close the issue.
