### ISSUE TITLE
Editorial: V1.1 Table formatting issues

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#428]
Some of the tables (e.g. Table 2) have some formatting errors.

![table_issues](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/assets/18121038/9be6686d-f9e4-44a6-ba76-edd34c441334)

**Comment by chris-little** [comment]
@ghobona Comment from TC Voter: "In the PDF there are some minor formatting issues (e.g. in  Annex A the word STATEMENT is cut off in the first column of the  Requirement tables."

**Comment by ghobona** [comment]
@chris-little Ok, thanks. Noted. Screenshot attached.

![Screenshot 2023-05-31 at 19 34 55](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/assets/18121038/d96d9c26-e4c5-4678-bf7d-f0e6a286c1bc)

**Comment by chris-little** [comment]
All formating fixed except a pdf one. Awaiting response from Metanorma.

**Comment by chris-little** [comment]
As V1.1 now in the publishing pipeline, and tagged as V1.1, the master branch now can become V1.2 etc. So Closing, agreed at EDR API SWG 102.
