### ISSUE TITLE
Editorial v1.1: Security Considerations

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#430]
Clause IV states that "No security considerations have been made for this document".

Clause 9.10, which is titled "Security", describes support for documentation of security schemes through OpenAPI.

If Clause 9.10 is re-titled "Security considerations", the contents will automatically be placed in Clause IV. This is a mechanism provided by metanorma.

@chris-little Should Clause 9.10 be re-titled  "Security considerations" and thus moved to Clause IV....or should the contents be left where they are (i.e. in Clause 9.10) with a title of "Security"?

**Comment by m-burgoyne** [comment]
@ghobona @chris-little I think it would make sense to re-title the section to Security considerations to avoid any confusion

**Comment by chris-little** [comment]
@ghobona @m-burgoyne I agree to retitle from 'Security' to 'Security Considerations' The layout of the preface by Metanorma always confused me! @m-burgoyne will add to his Pull Request.

**Comment by ghobona** [comment]
Fixed by https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/commit/337b4a4d43732a88ef7a9150805e1f01c68033ba
