### ISSUE TITLE
Abstract Tests for Radius queries are missing from Annex B

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#442]
Abstract Tests for Radius queries are missing from Annex B.

This was spotted by @CarstenTeichert and reported in Issue https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/423#issue-1633934758

**Comment by chris-little** [comment]
@m-burgoyne Are there some tests that were lost in repo-synching?

**Comment by chris-little** [comment]
@ghobona Fixed by PR#443
