### ISSUE TITLE
Allow collections to specify optional query parameters as mandatory.

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#446]
To support data that does not have time and vertical extents OGC-API EDR defines the  `datetime` and `Z` parameters as optional.  

When querying large data sources which have time and vertical dimensions, client application requests which don't specify the time and vertical query parameters can sometimes only be handled by returning a HTTP 413 error (request entity too large) .

Suggested Resolution

Enhance the EDR specification to use the OpenAPI response to allow individual collections the ability to advertise that query parameters are mandatory when necessary.  This would allow client applications to check if a query parameter was required before making a request.

**Comment by chris-little** [comment]
Addressed by PR #577
