### ISSUE TITLE
PubSub: links are not useful / usable

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-environmental-data-retrieval#451]
Note: I open the issue here and not in the [PubSub repository](https://github.com/opengeospatial/pubsub), because the draft requirements are still in this repository. Feel free to move the issue to the PubSub repository, if this should be discussed there. 

I see no value in providing the links as specified in ~[REQ_rc-links.adoc](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/pubsub/standard/requirements/pubsub/REQ_rc-links.adoc)~ [REQ_rc-links.adoc](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/extensions/pubsub/standard/requirements/pubsub/REQ_rc-links.adoc):

- The use of templates in the channel attribute is unclear. To be usable, the parameters would have to be defined like in the AsyncAPI definition. 
- The `rel` values in the current examples do not make sense. For example, the first link is not a link "to a resource which represents the collection resource for the context IRI" as the link relation type declares. The links as currently specified are links from the API landing page to some resource where I can subscribe to messages related to the API. This probably requires a new link relation type (e.g., `ogc-rel:subscribe`). 
- In any case, since links are "relationships between resources on the Web" [RFC 8288], the starting point of the link should not be the API landing page, but the resource that one can subscribe to. The link could also be on the API landing page, but then the `anchor` attribute would have to be used.
- Even, if I understand the additional, OGC-specific `channel` attribute, without which the link is basically not usable, I have no idea how to actually subscribe without the binding information as it is provided in the AsyncAPI definition.

I propose to drop the links. I do not see how a client can subscribe to channels without processing the AsynciAPI definition. The only alternative seems to be to duplicate much of the AsyncAPI definition, but in a very OGC-specific way that others won't understand.

**Comment by chris-little** [comment]
@cportele My understadning was that the ED API SWG envisaged that the AsyncA definition would be processed. We agree it is wasted effort to duplicate what is already in AsyncAPI. @tomkralidis , @m-burgoyne and @ShaneMill1 should be able to spuuply more clarity than me, when they return from their holidays.

**Comment by tomkralidis** [comment]
@cportele thanks for the comments/feedback.

>> The use of templates in the channel attribute is unclear. To be usable, the parameters would have to be defined like in the AsyncAPI definition.

That should be a fixed/actual example (i.e. ` "channel": "collections/foo"`).  Will update.

>> The rel values in the current examples do not make sense. For example, the first link is not a link "to a resource which represents the collection resource for the context IRI" as the link relation type declares. The links as currently specified are links from the API landing page to some resource where I can subscribe to messages related to the API. This probably requires a new link relation type (e.g., ogc-rel:subscribe).

>> Even, if I understand the additional, OGC-specific channel attribute, without which the link is basically not usable, I have no idea how to actually subscribe without the binding information as it is provided in the AsyncAPI definition.

I agree that an AsyncAPI document is the fulsome point of truth/definition.  At the same time, if a client is at `/collections/{collectionId}` and perusing links in same, should they drop back to the AsyncAPI document, even if they are "right there" to be able to construct a subscription?  Then again, a client would need to be aware of the message payload schema to be able to parse without apriori knowledge.

Having said this, what if we move the link requirements to the pubsub message payload conformance class?  In this case, thee is enough there for a client to expect a valid GeoJSON from any supporting broker, linked from an API endpoint.

**Comment by cportele** [comment]
@tomkralidis

I still do not see value in the links. A link must be useful also without any custom properties, otherwise it is not a proper link, but a custom data type that looks like a link. Without the channel property, the links do not seem usable to construct a subscription, also in the pubsub message payload conformance class. The broker will likely have channels where the message is not a GeoJSON feature.

**Comment by tomkralidis** [comment]
2023-10-31 OGC Sprint Pub/Sub breakout:
- change https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/extensions/pubsub/standard/requirements/pubsub/REQ_rc-links.adoc `channel` REQUIREMENT to PERMISSION

**Comment by tomkralidis** [comment]
PR in #464.

**Comment by chris-little** [comment]
CLosed at EDR API SWG 2023-11-23
