### ISSUE TITLE
PubSub: channel identifiers

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-environmental-data-retrieval#452]
Note: I open the issue here and not in the [PubSub repository](https://github.com/opengeospatial/pubsub), because the draft requirements are still in this repository. Feel free to move the issue to the PubSub repository, if this should be discussed there. 

The current requirement ~[REQ_rc-channels](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/pubsub/standard/requirements/pubsub/REQ_rc-channels.adoc)~ [REQ_rc-channels](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/extensions/pubsub/standard/requirements/pubsub/REQ_rc-channels.adoc) is not testable. It is also too vague to be useful, I think.

My proposal would be that we

* define a common base template for use by all OGC API PubSub implementations;
* leave the resource specific add-ons to the relevant resource-specific standards.

In AsyncAPI, a channel identifier is a relative URI template. The base template could be something like `ogcapi/{publisherId}/{apiId}/{+resourcePath}`. The combination of `{publisherId}` and `{apiId}` should uniquely identify the OGC Web API.

For feature resources, obvious `{+resourcePath}` values could then be:

* `collections/{collectionId}/items` to receive messages about new, updated or deleted features. 
* `collections/{collectionId}/items/{featureId}` to receive messages about changes to some feature. 

In addition, I am also thinking about channels like

* `collections/{collectionId}/filters/{+filters}` to receive messages about features (new or updated) that match a CQL2 filter expression. Multiple filter expressions will be combined with `AND`.

Examples with full channel identifiers could then be:

* `ogcapi/t19.ldproxy.net/wis20/collections/surface_obs/items` to receive new surface-based weather observations from the WIS 2.0 network. 
* `ogcapi/t19.ldproxy.net/wis20/collections/surface_obs/filters/{wigos_station_identifier}` to receive only messages for observations from a specific weather station.
* `ogcapi/t19.ldproxy.net/wis20/collections/surface_obs/filters/{wigos_station_identifier}/air_temperature` to receive only messages for air temperature observations from a specific weather station. These could be retained by the broker.
* `ogcapi/t19.ldproxy.net/wis20/collections/surface_obs/filters/3hour_pressure_change_gt_4hPA` to receive only messages for observations that report an absolute pressure change >4hPa over the last three hours.

**Comment by chris-little** [comment]
@cportele thank you for these informed and constructive comments. We postponed the next EDR API SWG meeting until next week, after various holidays, on the Thursday, 22 August 2023, so we can discuss in detail then with @tomkralidis , @m-burgoyne and @ShaneMill1 .

**Comment by tomkralidis** [comment]
2023-10-31 OGC Sprint Pub/Sub breakout:
- depends on various use cases
  - Pub/Sub as an add on to an OGC API
  - Pub/Sub as an aggregation activity
- to be future proof, move channels requirement into its own conformance class

**Comment by tomkralidis** [comment]
PR in #464.

**Comment by chris-little** [comment]
PR merge, so closed at EDR API SWG 2023-11-23
