### ISSUE TITLE
enable publication of EDR Part 2: Pub/Sub 

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#458]
Now that Part 2 is in place (in the GitHub repository that is), should we enable publication of Part 2 as a DRAFT to https://ogcapi.ogc.org/edr? so:

```
The standards can be found at:

* [OGC API - Environmental Data Retrieval Standard 1.1.0](https://docs.ogc.org/is/19-086r6/19-086r6.html)
* [OGC API - Environmental Data Retrieval - Part 2: Publish-Subscribe workflow](TBD) draft
```

cc @solson-nws @chris-little @ShaneMill1 @m-burgoyne

**Comment by chris-little** [comment]
@tomkralidis @ghobona How about:
```
* [OGC API - Environmental Data Retrieval Standard - Part 1: Core, V1.1.0] (https://docs.ogc.org/is/19-086r6/19-086r6.html)
* [OGC API - Environmental Data Retrieval - Part 2: Publish-Subscribe workflow](TBD) draft
```

**Comment by tomkralidis** [comment]
+1

**Comment by ghobona** [comment]
@chris-little OGC API - EDR v1.1.0 has already been published. So the new title would have to apply to the next version. I will update the OGC API website to use the titles proposed by @tomkralidis on the initial comment above.

**Comment by ghobona** [comment]
@tomkralidis Please request a document number from the Pending Documents register.

Once you have the document number, please update document.adoc with the number, and then let me know.

I will then ask @gbuehler to set up a cronjob to automatically build the document at docs.ogc.org/DRAFTS.

**Comment by tomkralidis** [comment]
@ghobona I've reserved 23-057 from pending and updated `extensions/pubsub/standard/document.adoc` in 23d65a58abeb411dfd18ffabaf61046e4f481cb7.

We should be ready for the cronjob at this point.  If I need to also upload the output of 23-057 to pending, let me know.

**Comment by ghobona** [comment]
There is now a cron job that builds the document daily at https://docs.ogc.org/DRAFTS/23-057.html

The next action is to list it at ogcapi.ogc.org/edr

**Comment by chris-little** [comment]
@tomkralidis  As the actions have all been done ( thank you @ghobona !), I will close this issue.
