### ISSUE TITLE
Inconsistencies in EDR spec

### ISSUE THREAD

**Issue by rosinaderks** [opengeospatial/ogcapi-environmental-data-retrieval#459]
While implementing the EDR spec into a Pydantic model, we encountered some inconsistencies in the spec between objects, requirements and the examples. Hopefully, it is possible to overcome some of these inconsistencies or define which of them is leading for easier implementation.

Object C.1 **Collections**:
- Object defines a 'crs' string array, while requirement A.24 defines an object with 'name' and 'wkt', and while object C.4 CRSDetails defines an object with 'crs' and 'wkt'. 
- Object defines 'output_formats', while requirement A.13 defines this variable as 'f'.
- Object defines 'data_queries', while there is no mention of this attribute in requirement A.13.

Object C.2 **EDRQuery**:
- Object defines 'link' as a Link object for which the attribute 'variables' not required, while requirement A.16 defines that 'variables' is required.

Object C.3 **Variables**:
- Object defines 'query_type' as not required, while requirement A.15 defines it shall be included.

Object C.9 **Data Queries**:
- Object defines 'item', 'location', while requirement A.14 speaks of 'items', 'locations'.

Object C.11 **Parameter**:
- Object has no mention of 'categoryEncoding', while requirement A.25 mentions an optional attribute 'categoryEncoding'.
- Object defines i.e. 'description', 'label', etc as a string, while requirement A.25 defines that these must be an i18n object.

Object C.15 **Observed Property**:
- Object defines that only 'label' is required, while requirement A.25 defines that both 'label' and 'id' are required.
- Object has no mention of 'categories', while requirement A.25 defines the possible attribute 'categories'.

General:
MUST and SHALL are both used which can cause confusion, for example in requirement A.18 and A.19.

**Comment by chris-little** [comment]
@rosinaderks Thank you for this detailed reading, experimentation and report. We will have an online EDR API Standard Working Group meeting on Thursday, 19 Oct 2023, where we can try to agree on the correct resolutions.

**Comment by rosinaderks** [comment]
Hi @chris-little! Yes, I am working from the V1.1 specification. I appreciate the discussion within the working group and am eager to see the outcomes.

**Comment by PaulVanSchayck** [comment]
In case anyone is interested, these are our Pydantic models for the EDR spec:
https://github.com/KNMI/edr-pydantic

**Comment by chris-little** [comment]
@rosinaderks Thank you for identifiying those inconsistencies. We have fixed the Master Branch (Part 1: Core, V1.2)

V1.1 will be fiexed when we have the correct procedure fro OGC staff. We may have to publish a V1.1.1

The fixes that we applied are:
Object C.1 Collections:
    Object defines a 'crs' string array, requirement A.24  now defines an object with 'crs' 
    Object defines 'output_formats', requirement A.13 now defines this variable as 'output_formats'.
    Object defines 'data_queries', reuirement A.13 now mandates at least one.
Object C.2 EDRQuery:
    Object now defines 'link' as a Link object for which the attribute 'variables' is required.
Object C.3 Variables:
    Object defines 'query_type' as not required, while requirement A.15 defines it shall be included.
Object C.9 Data Queries:
    Object now defines 'items', 'locations', and requirement A.14 speaks of 'items', 'locations'.
Object C.11 Parameter:
    Object has no mention of 'categoryEncoding', now requirement A.25 does not mentions an optional attribute 'categoryEncoding'.
    Object defines i.e. 'description', 'label', etc as a string, now requirement A.25 defines that these as strings.
Object C.15 Observed Property:
    Object defines that only 'label' is required, while requirement A.25 now defines that 'id' is optional.
    Object has no mention of 'categories', similarly requirement A.25.

General:
MUST and SHALL are both used which can cause confusion, for example in requirement A.18 and A.19.
We are still working on these (I have identified A.15, A.19, A.30 and A.31). There are also quite a lot of `should`s that SHALL be `SHOULD`!

**Comment by rosinaderks** [comment]
Hi @chris-little. Great to hear, nice to see the inconsistencies fixed! Thanks for the quick responses.

**Comment by chris-little** [comment]
Agreed at EDR API SWG 2023-11-23. Will close this issue when V1.1 correction branch merged (proobably into V1.1.1 branch)

**Comment by chris-little** [comment]
EDR API SWG 2024-12-05 Agreed to close as addressed.
