### ISSUE TITLE
PubSub: Mentions of "this paper" in the abstract

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#466]
There is a mention of "this paper" in the [abstract](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/extensions/pubsub/standard/sections/clause_0_front_material.adoc). It could be from text copied from the Discussion Paper.

**Comment by chris-little** [comment]
@tomkralidis @ghobona I suggest `This paper...` -> `This specification...`

**Comment by tomkralidis** [comment]
PR in #474
