### ISSUE TITLE
PubSub: Mentions of "This Discussion Paper" in the Scope

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#467]
There is a mention of "This Discussion Paper" in the Scope. The text should be revised to refer to the standard.

**Comment by chris-little** [comment]
@tomkralidis @ghobona I suggest `This Discussion Paper...` -> `This specification ...`. I also suggest that the text about WMO and WIS2 is not suited to a specification (think about oceanographic, engineering or health uses cases!).

**Comment by tomkralidis** [comment]
PR in #474
