### ISSUE TITLE
DataQuery OpenAPI definitions duplicate information

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#476]
The DataQuery definitions for the EDR Query types (Position,Radius,Area,Cube,Trajectory,Corridor and Locations) share common query parameters.  Currently these are replicated in the OpenAPI definitions for each of the Query types, this could be improved by modifying the schemas to inherit the common properties.

**Comment by chris-little** [comment]
This is addressed by PR #475
