### ISSUE TITLE
PubSub: Support for Partial Fulfillment Requests

### ISSUE THREAD

**Issue by ShaneMill1** [opengeospatial/ogcapi-environmental-data-retrieval#478]
The use case is for NWP Model Data as new data becomes available.

Status of a fully qualified model run:

- Can publish a message once the full model run is fully qualified
- Can publish a message for individual forecast hours being available

We want to ensure that users are informed when the data is available as the model run is in progress.

CC: @solson-nws @tomkralidis

**Comment by ShaneMill1** [comment]
Discussed in MetOcean DWG 11/16/23

Similar use cases to help generalize:

- You can request a map, but notify when specific tiles become available
- Tell me when individual parameters become available
- I've completed the ingestion process and there will not be any more granules reviving, so for the perspective of the ingest, the data is complete (whether data is missing or not)

Maybe we can generalize this as "granules becoming available"

This would be one of the key features specific to the MetOcean domain to prevent users from continuously polling while a model run is in progress

This could be added as an informative example or an annex.

There could be a relation to Processes here as well.

**Comment by chris-little** [comment]
@ShaneMill1 Could you prepare a PR please? Agreed at EDR API SWG 2023-11-23.

**Comment by tomkralidis** [comment]
Initial PR in #498.

**Comment by chris-little** [comment]
PR now merged, so closing issue
