### ISSUE TITLE
Add reference to CoverageJSON Community Standard

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#479]
Add reference to CoverageJSON Community Standard ([OGC 21-069r2](https://docs.ogc.org/cs/21-069r2/21-069r2.html)) to the next version of [OGC API - EDR](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/sections/clause_3_references.adoc).

**Comment by chris-little** [comment]
@ghobona @m-burgoyne The change will be added to PR #472
