### ISSUE TITLE
PubSub: When to use the slash

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#480]
Just reading through some previous documentation on Publish/Subscribe, including the OWS-oriented Standard and the recently approved Charter. The convention appears to be to use **Publish/Subscribe** or the short name of **PubSub**.

That means that the slash should only be used when the full words are spelt out (i.e. Publish/Subscribe).

That also means that all occurrences of "Pub/Sub" should be replaced with "PubSub" in the Part 2 candidate standard.

**Comment by chris-little** [comment]
@ghobona @tomkralidis So, should we use `Publish/Subscribe` or `Publish-Subscribe`?

**Comment by ghobona** [comment]
Please use `Publish/Subscribe`, and when appropriate abbreviate with `PubSub`

**Comment by tomkralidis** [comment]
I see use of `Publish-Subscribe` (https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern)  and `Pub/Sub` (https://aws.amazon.com/what-is/pub-sub-messaging/), which was reasoning for the convention.

Having said this, perhaps we can use 'Asynchronous workflow' for the document title (noting that `Publish-Subscribe` and `Pub/Sub`) would be used throughout the document per se.

**Comment by chris-little** [comment]
@tomkralidis Agreed to `Pub/Sub` but think `Asysnchronous Workflow` is too general, as it encompasses asynchronous responses just using HTTPS.

**Comment by chris-little** [comment]
Fixed in PR #495

**Comment by chris-little** [comment]
@ghobona Now consistently `Publish-Subscribe` and `Pub\Sub` from PR #495
