### ISSUE TITLE
Inconsistency between specification and schema in 'C.13. Unit Object'

### ISSUE THREAD

**Issue by iandruska-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#486]
[Specification](https://docs.ogc.org/is/19-086r6/19-086r6.html#col-unit) mandates that both 'label' and 'symbol' properties are mandatory, while in [schema](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/schemas/collections/units.yaml) only one of them is mandatory.

Similar inconsistency in [C.14.  Symbol Object](https://docs.ogc.org/is/19-086r6/19-086r6.html#col-symbol): Specifications states that all properties are optional, while [schema](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/schemas/collections/units.yaml) states that 'value' and 'type' are mandatory. Moreover, the schema does not mention 'title' and 'description' properties.

**Comment by chris-little** [comment]
@iandruska-ibl Are you happy with @m-burgoyne 's Commit?

**Comment by iandruska-ibl** [comment]
Yes, it looks good to me.

**Comment by iandruska-ibl** [comment]
Yes, it looks good to me.

**Comment by chris-little** [comment]
Fixed by PR 487 merged at EDR API SWG 113
