### ISSUE TITLE
Replace mentions of "OGC APIs"

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#491]
There is a request from the OAB for clearer use of terminology regarding OGC API Standards. 

The detail of the Issue is documented at https://github.com/opengeospatial/ogcapi-common/issues/336

This GitHub Issue may be closed once the relevant edits have been made to relevant OGC API Standards documents.

**Comment by chris-little** [comment]
@ghobona @cnreediii Terminology made consistent, and applied most edtorial suggestions.

Still outstanding are some definitions and terminology issues listed below.

**Comment by chris-little** [comment]
@tomkralidis All @cnreediii edits done but some comments outstanding:
1. Scope: what is a Topic Structure?
2. Conformance: two `TBD` to be done.
3. Wrong template used for all requirements, recommendations and permissions.
4. Requirements Class Pub/Sub: define or explain `hierarchy of channels'.
5. Requirements Class Channels: define endpoint hierarchy.
6. Recommendations: define `collection endpoint`.
7. Requirement `channels depending on endpoint` needs clarifying
8. Requirement for GeoJSON IETF7946 - what if CAP notifications which is XML based?MAY?
9. Annex: What is a GeoJSON `baseline`? I've replaced with `object`.

**Comment by chris-little** [comment]
@tomkralidis @m-burgoyne PR#495 needs review, then I'll merge.

**Comment by cnreediii** [comment]
@chris-little Thanks for the quick turnaround and the update!

**Comment by chris-little** [comment]
PR awaiting review. Some outstanding request raised as separate issues.
