### ISSUE TITLE
Should Payload be mandated or recommended as GeoJSON

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#501]
Requirement for GeoJSON IETF7946 - what if CAP notifications which is XML based? We could change Requirement to Recommendation MAY.

**Comment by chris-little** [comment]
PR will be prepared by @chris-little so that it is clear that GeoJSON is optional, but if used, must be conformant.

**Comment by chris-little** [comment]
@cnreediii Payload format is not mandated. But if GeoJSON is chosen, it must be standard GeoJSON, and if a CRS other than WGS84 is desired, OGC FG-JSON is preferred. Will close issue when PR merged.

**Comment by chris-little** [comment]
Addressed by PR504

**Comment by cnreediii** [comment]
@chris-little Thanks!
