### ISSUE TITLE
Pub/Sub Security Considerations

### ISSUE THREAD

**Issue by Gugym** [opengeospatial/ogcapi-environmental-data-retrieval#503]
Create a threat model for the Pub/Sub including documenting any security around the protocols of MQTT and AMQP etc. This would provide a framework to assess security of the evolution of the EDR service to 1.2.

**Comment by chris-little** [comment]
@Gugym I am assuming that the threat model does not need to be part of the PubSub spec.

**Comment by Gugym** [comment]
@chris-little No, I would suggest it should be a supporting document for the benefit of a security assessment.

**Comment by chris-little** [comment]
@Gugym There is a series of weekly meetings of the OGC Security SWG planned to re-charter the Security SWG to produce a common security approach, like OGC API-Common Part 1: Core (the landing page), to address the exposure and query of security approaches.

**Comment by chris-little** [comment]
@Gugym There have been a couple of meetings of the API Security SWG. They will be specifying appraoches for APIs in general, not just OGC APIs, so I propose to close this issue. We can always re-open if there are untackled issues.
