### ISSUE TITLE
relax temporal extent string format

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#512]
EDR collection [temporal definitions](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/schemas/collections/extent.yaml#L115-L158) constrain time values as JSON Schema as follows:

```json
"type": "string",
"format": "date-time"
```

As discussed at EDR SWG on 2024-02-15, removing the `format` constraint would allow for valid durations and repetitions.

**Comment by tomkralidis** [comment]
PR in #514

**Comment by chris-little** [comment]
Unitl there is better tight specification of dates, times, durations, periods etc (such as https://datatracker.ietf.org/doc/draft-ietf-sedate-datetime-extended), being looser with the date-time string is an appropriate interim solution.
