### ISSUE TITLE
Standard document and OpenAPI spec disagree on the existence of /collections/{collectionId}/instances/{instanceId}

### ISSUE THREAD

**Issue by petergarnaes** [opengeospatial/ogcapi-environmental-data-retrieval#518]
Looking in the [SwaggerUI](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/opengeospatial/ogcapi-environmental-data-retrieval/master/core/standard/openapi/ogcapi-environmental-data-retrieval-1.bundled.json), `/collections/{collectionId}/instances/{instanceId}` is nowhere to be found.

However, looking at the second to last entry in the [table of resource paths](https://docs.ogc.org/is/19-086r6/19-086r6.html#_fde2fe15-18e2-4077-91a7-23a90f6f0c48) in the official standard, it clearly states that it exists and returns the instance metadata.

I assume the document is the correct one, but I am not sure, which is it?

**Comment by m-burgoyne** [comment]
@petergarnaes the schema is incorrect, pull request #525 has been raised to fix the error and pull request #462 has been updated to include the fixes.
