### ISSUE TITLE
Pub/Sub notification make geographical information optional

### ISSUE THREAD

**Issue by andrewgryan** [opengeospatial/ogcapi-environmental-data-retrieval#519]
I guess my point is, is GeoJSON the most suitable format for a Pub/Sub message payload?

EDR REST endpoint(s) have the same information, to me a notification should simply indicate what has changed and how to go retrieve the fresh data. The additional geospatial info, while useful for visualising an event stream, should be optional or supplementary information

## Long read
Is it possible, in the current Pub/Sub draft specification, to communicate that an update has taken place for a collection but not also have to specify geospatial coordinates? 

The current notification specification requires GeoJSON format to be used for the payload body, with the `properties` attribute a vehicle for carrying the endpoint information.

I ask because the GeoJSON information is readily available from the EDR REST endpoint(s) related to the collection, is it also a requirement to duplicate this information in the notification?

My attempts so far to specify a null-ish GeoJSON FeatureCollection/GeometryCollection to encode the relevant REST endpoint(s) in the `properties` field, have resulted in invalid `GeoJSON`. I also think it is a lot of boilerplate, for a simple message, I want to express "the following collections have updated" in a simpler way.

```json
{
  "id": "0cf33b4a-8258-43e1-b84d-4ff2a4f8177c",
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": []
      },
      "properties": {
        "pubtime": "2022-03-20T04:50:18.314854383Z",
        "operation": "create",
        "events": [
          {
            "event_type": "exercise",
            "sources": [
              {
                "number": 211060,
                "primary_name": "Etna"
              },
              {
                "number": 371032,
                "primary_name": "Fagradalsfjall"
              }
            ]
          }
        ]
      },
      "links": [
        {
          "href": "api-management.metoffice.cloud/qva-service/1.0/collections/qva_deterministic/locations",
          "rel": "collection",
          "type": "application/json"
        },
        {
          "href": "api-management.metoffice.cloud/qva-service/1.0/collections/qva_probabilistic/locations",
          "rel": "collection",
          "type": "application/json"
        },
        {
          "href": "api-management.metoffice.cloud/qva-service/1.0/collections/qva_iwxxm/items",
          "rel": "collection",
          "type": "IWXXM"
        }
      ]
    }
  ]
}
```

Note: My use case is notifying Volcanic Ash Advisory Centre users when eruptions take place, so I've added some custom `properties` to the payload that my users may be interested in

**Comment by andrewgryan** [comment]
A promising workaround is to use the `MultiPoint` Geometry type, which allows for `coordinates` arrays of length zero. It passes validation at least.

The additional boilerplate and potentially confusing interpretation of the payload message formatted as GeoJSON with an empty geometry still troubles me a little. I'll think about this further and propose some ideas if a good one comes to mind.

**Comment by tomkralidis** [comment]
FYI GeoJSON allows for defining a geometry as `null`, so:

```json
"geometry": null
```

**Comment by andrewgryan** [comment]
Sorry, misread your comment. That's a good workaround.

**Comment by chris-little** [comment]
Sub@andrewgryan OGC API-EDR Part 2: PubSub now in pipeline for Public Comment. Are you happy to close this issue?
@tomkralidis for info.

**Comment by andrewgryan** [comment]
Happy to close this issue, specifying `"geometry": null` signals the correct intention to the consumer of the message and allows for a progressive enhancement to ship geometry where appropriate
