### ISSUE TITLE
Inconsistent treatment of /collections/<collectionId>/instances endpoint

### ISSUE THREAD

**Issue by iandruska-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#524]
Specification lists the /instances endpoint among data queries: https://docs.ogc.org/is/19-086r6/19-086r6.html#_e55ba0f5-8f24-4f1b-a7e3-45775e39ef2e.

Metadata example at https://docs.ogc.org/is/19-086r6/19-086r6.html#_162817c2-ccd7-43c9-b1ea-ad3aea1b4d6b also shows "instances" among "data_queries".

However, schema is not listing "instances" among "data_queries": https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/schemas/collections/collection.yaml

Is the specification wrong or schema is wrong?

**Comment by m-burgoyne** [comment]
@iandruska-ibl the schema is incorrect, pull request #525 has been raised to fix the error and  pull request #462 has been updated to include the fixes.
