### ISSUE TITLE
Open ranges for 'z' parameter

### ISSUE THREAD

**Issue by iandruska-ibl** [opengeospatial/ogcapi-environmental-data-retrieval#527]
I wonder whether there is any reason why open ranges (e.g., `../850`, `../..`) are not specified for the `z` parameter?

It is an option for the `datetime` parameter (Statement F in https://docs.ogc.org/is/19-086r6/19-086r6.html#_3abf1496-c07a-41bd-9884-cd1eb5ce2dbf).

I think it is equally useful for the `z` parameter. It would make the `datetime` and `z` perfectly symmetrical too.

**Comment by chris-little** [comment]
@iandruska-ibl Good suggestion. Do you think it increases the Denial of Service attack risk?

**Comment by iandruska-ibl** [comment]
@chris-little I think that security is irrelevant at this level of abstraction. Security is a matter of implementation. Implementations are free include mechanisms to prevent attacks at specific EDR features. For example, to prevent DoS attacks, implementations might evaluate the size of a query and deny if it is too large. No need to restrict capabilities of API because of that in my opinion (BTW, DoS attacks are usually detected/prevented at a different architecture layer, e.g., load balancers, API gateways, etc.).

**Comment by m-burgoyne** [comment]
@iandruska-ibl I agree that it makes sense for any of the query parameters which support a range input to follow the same rules.
