### ISSUE TITLE
Public Comment 1.2: UUID/GUID in 10.1.2

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-environmental-data-retrieval#531]
I'm currently reading through https://docs.ogc.org/DRAFTS/23-057.html as part of the RFC.

10.1.2 says:
> A universally unique identifier of the message using the **UUID** standard (RFC4122)
> [...]
> Requirement 4 [...] A: A Pub/Sub notification message SHALL provide an id property as a **GUID**.

1. It would be great to link to the RFCs throughout the document.
2. As long as the IDs are unique, does the standard really need to define how the IDs look like?
3. GUID is not mentioned before. What is it? Is it the same as a UUID? There are also more mentions of GUID in the annex.

**Comment by chris-little** [comment]
@tomkralidis @m-burgoyne Any comments?

**Comment by chris-little** [comment]
EDR API SWG 115 agreed GUID and UUID shold really be (globally) Unique Identifier throught the document. We also agreed that a Unique Identifier is Mandated, and UUID is Recommended.
@m-mohr Are you happy with this? A PR is being prepared by @tomkralidis.

**Comment by m-mohr** [comment]
Sounds good to me so far.

**Comment by chris-little** [comment]
GUID - > UUID so far

**Comment by chris-little** [comment]
@m-mohr Are you happy to close this issue once @tomkralidis PR #539 merged?

**Comment by m-mohr** [comment]
Looks good, thanks.
