### ISSUE TITLE
Public Comment 1.3: Allowed values for operation

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-environmental-data-retrieval#532]
I'm currently reading through https://docs.ogc.org/DRAFTS/23-057.html as part of the RFC.

Chapter 10.1.2.2 says:

> The operation property indicates the stage of the lifecycle for the resource described in the notification, and can be used to notify users that a resource has been updated or deleted. If not specified, the default value is create.

1. The first sentence seems to imply update and delete, but then in the next sentence the default is create. Shouldn't this be "that a resource has been added, updated or deleted"? The same applies to Req. 6 A
2. You should provide a list of allowed values in the description. I see "delete" (example) and "create" (default value). I assume for updated the value is "update" but that's not specified.

Permission 3 says:

> A Pub/Sub Notification Message MAY provide the properties.operation property to indicate if a resource has been inserted.

What does this mean? How is insertion different from created?

**Comment by chris-little** [comment]
EDR API SWG 115 agreed that the text needs clarifying and `inserted` means `created. Editorial review will bedone to make wording consistent and explicit to make the schema enumeration at https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/extensions/pubsub/openapi/schemas/pubsub-message-payload-schema.yaml#L31 
@m-mohr Thank you for your constructive comment.

**Comment by tomkralidis** [comment]
Thanks @m-mohr.  Updates now in PR #539

**Comment by m-mohr** [comment]
Thanks, looks good so far.

**Comment by chris-little** [comment]
@m-mohr Are you happy to close this issue once @tomkralidis PR https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/539 merged?

**Comment by m-mohr** [comment]
>     2. You should provide a list of allowed values in the description. I see "delete" (example) and "create" (default value). I assume for updated the value is "update" but that's not specified.

I think the allowed values should be listed explicitly and not just in examples.
The following comment proposes a change:
https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/539/files#r1586876634

Otherwise LGTM.
