### ISSUE TITLE
Public Comment 1.4: Collections, (Geo)JSON and Properties

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-environmental-data-retrieval#533]
I'm currently reading through https://docs.ogc.org/DRAFTS/23-057.html as part of the RFC.

This is more a set of high-level thoughts and questions.

- It looks like channel / is "all notifications". Is this only items or e.g. also new collections? Is there a way to only be notified about new collections?
- It sounds like GeoJSON is one of the payloads, but not necessarily required. So could this also be a Collection JSON?
- If yes, it is a bit weird that the properties (which originate from GeoJSON Features) is explicitly referenced in 10.1.2.x for pubtime and operation. The Collections don't have properties. That seems to bei GeoJSON specific.

**Comment by andrewgryan** [comment]
This seems to be related to #519. The decision there was to use `geometry: null` for payloads not tied to coordinates. I don't know if that helps with this top-level notification question?

**Comment by chris-little** [comment]
EDR API SWG 115 discussion: some of the functionality is underlying protocol specific, such as MQTT or AMQP. So the exmaples have to be specific. 
`/` does imply at that level, whereas `/*` (in MQTT) would imply that level and all levels below.

**Comment by chris-little** [comment]
`It sounds like GeoJSON is one of the payloads, but not necessarily required. So could this also be a Collection JSON?`
EDR API SWG 115 agreed that the payload conformance class will be restructured to clarify that a payload and decalration of its format are mandated. Then it is recommended that JSON/GeoJSON/FG-JSON are used.
@tomkralidis will prepare a PR.

**Comment by chris-little** [comment]
`if yes, it is a bit weird that the properties (which originate from GeoJSON Features) is explicitly referenced in 10.1.2.x for pubtime and operation. The Collections don't have properties. That seems to be GeoJSON specific.`
@m-mohr The restructuring of the conformance class should address this weirdness.

**Comment by chris-little** [comment]
@m-mohr Are you happy to close this issue once @tomkralidis PR https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/539 merged?

**Comment by m-mohr** [comment]
It's hard to judge this from the PR because I'm not sure where all the small files in the end appear. A rendered version would help to understand whether this is sufficiently fixed or not.

**Comment by chris-little** [comment]
@m-mohr @tomkralidis awaiting a rendered version for review.

**Comment by chris-little** [comment]
@m-mohr we have created a rendered version of [Part 2: PubSub](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/files/15263543/document.pdf). Let us know when we can close this issue. Of course if you spot anything else, please raise a new issue.

**Comment by chris-little** [comment]
@m-mohr Agreed to close at EDR API SWG 118 on 2024-05-30. Please reopen if you are not happy.
