### ISSUE TITLE
Advertising HTML-encoded AsyncAPI definition documents in PubSub enabled OGC API landing pages

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#534]
This issue is related to https://github.com/opengeospatial/ogcapi-common/issues/329 , however is more severe for HTML-encoded definition documents.

Consider the following fragment from the links in a landing page.

```json
        {
            "rel": "service-doc",
            "type": "text/html",
            "title": "The OpenAPI definition as HTML",
            "href": "http://localhost:5000/openapi?f=html",
            "hreflang": "en-US"
        }
```

If a server wishes to advertise links to HTML-encoded AsyncAPI definition documents and HTML-encoded OpenAPI definition documents, there is a need to either provide a `rel` or `type` that allows such distinction to be made. Any thoughts on how this could be achieved?

Note that the reason why the issue is more severe for HTML-encoded definition documents, is because at least for JSON-encoded definition documents there is a specific media type for OpenAPI definition documents.

**Comment by ghobona** [comment]
This issue was discussed in the Joint OGC API SWGs session on 2024-03-27 session and a proposal to declare an OGC-specific relation type was approved.

**Comment by cportele** [comment]
Apologies for not attending the Joint OGC API SWG session, but I do not see the argument for a different link relation type. `service-doc` applies both to a HTML documentation derived from an OpenAPI definition or an AsyncAPI definition. If there are two `service-doc` links, the human reader will understand their scope and that they describe two different APIs. And the `title` link attribute should clearly specify the meaning of the link target.

At least, if OGC defines a special AsyncAPI link relation type, it should not be mandatory to use it for links to the documentation of an event-driven API.

In any case, the `type` link attribute is only a hint.

**Comment by chris-little** [comment]
EDR API 115 agreed not to change anything in the Part 2 spec but suggest a link with a media type suitable for all OGC APIs until the AsyncAPI community have an IANA registered link. @ghobona should be consulted. We suggest modelling on OpenAPI media type:
 `application/vnd.oai.openapi` (YAML variant)                 -> application/vnd.oai.asyncapi`
`application/vnd.oai.openapi+json` (JSON only variant) -> `application/vnd.oai.asyncapi+json`
`application/vnd.oai.openapi;version=2.0`                      -> `application/vnd.oai.asyncapi;version=2.0`
@tomkralidis will propose this to the AsyncAPI community.

The IANA OpenAPI proposal probably will look like:
        `application/openapi+yaml;version=3.1`
        `application/openapi+yaml;version=3.0;q=0.5`
        `application/openapi+json;q=0.3`

**Comment by tomkralidis** [comment]
ACTION: add note to 8.2.1 that AsyncAPI media type may change in the future.

**Comment by cportele** [comment]
@tomkralidis 

Since RFC 9512 has recently been [published](https://datatracker.ietf.org/doc/rfc9512/), it should be `application/vnd.oai.asyncapi+yaml` for the YAML variant, that is, with the suffix. 

Also, I do not understand the use of `oai`. What does this refer to? Should this be `aai` for the "AsyncAPI Initiative"?

**Comment by tomkralidis** [comment]
- @cportele I've updated @chris-little 's text above (indeed `aai` is to be used for a vendor definition), so`application/vnd.aai.asyncapi+yaml`
- note added to specification that AsyncAPI media type may change in the future

**Comment by m-mohr** [comment]
#539 still uses `application/json`, right? Is this planned to be updated?

**Comment by tomkralidis** [comment]
No, not until there is clarification from the AsyncAPI community.  There is enough delineation for now of `rel=service-desc` between the OpenAPI media type and `type=application/json` (there is a possibility that `rel=service-desc` and `type=application/json` may get overloaded if one has multiple JSON-based `service-desc` endpoints, but IMHO that is an edge case atm).
