### ISSUE TITLE
Public Comment 1.5: x-ogc-api-link object in /req/pubsub-channels/channels is unclear

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-environmental-data-retrieval#535]
EDR, Part 2, RFC version:

`/req/pubsub-channels/channels` mentions "an `x-ogc-api-link` object", but this object is undefined and only used in examples. Even from the examples, I do not understand the use of the `rel` and `type` members.

The requirement should either be deleted or it needs much more detail to be meaningful - and testable.

**Comment by chris-little** [comment]
EDR API SWG 115 agreed `Channels (topic/destination/node depending on protocol) that have equivalent API endpoint functionality SHALL be expressed within an AsyncAPI channel with an x-ogc-api-link object.` should read

`Channels (topic/destination/node depending on protocol) that have channels that communicate changes of resources in an OGC Web API SHALL be expressed within an identified AsyncAPI channel.`

@tomkralidis will also add explanation in 8.2

**Comment by tomkralidis** [comment]
I've also added a short description of `x-ogc-api-link` in clause 9 (i.e. link object as defined in OGC API - Common).

**Comment by chris-little** [comment]
@cportele  Are you happy to close this issue once @tomkralidis PR https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/539 merged?

**Comment by cportele** [comment]
@chris-little - No, see my review comments in the PR.

**Comment by chris-little** [comment]
@cportele Apologies - I missed those as just reading the issues!

**Comment by chris-little** [comment]
@cportele @tomkralidis awaiting a rendered version for review.

**Comment by chris-little** [comment]
@cportele We have created a renedered version at  [Part 2: PubSub](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/files/15263543/document.pdf) for you further review. Please let us know if we can close this issue, or raise new ones if something else spotted (we've seen spelling mistakes, and the moving goal posts of Common Part 2 are being fixed.)

**Comment by cportele** [comment]
@chris-little @tomkralidis 

There are still links to an MQTT broker in the updated draft, see 8.2.3 and 8.2.4. These are not proper web links, the link relation types are semantically not applicable for a MQTT broker resource. I would delete the two sections.

"x-ogc-api-link" is now only mentioned in an informative example, but the use of the link relation types is also in this case not consistent with the definitions of the link relation type, e.g. "collection". If such links should be included, new link relation types that accurately describe the link should be specified and registered with the OGC NA.

**Comment by chris-little** [comment]
@cportele We are weakening the text of 8.2.3/4 and making clear that they are examples. We wish to keep them in as they are very important for the EDR use cases. 
"x-ogc-api-link" is an AsyncAPI object defined to be compatible with the OpenAPI link object. So we are changing the text to reflect this more clearly. OGC API-Common Part 1: Core states that link relations can be used that are not in IANA or OGC registers.
We think we have now addressed your concerns in this issue.

**Comment by tomkralidis** [comment]
Addressed in #547

**Comment by cportele** [comment]
@chris-little 

> We are weakening the text of 8.2.3/4 and making clear that they are examples. We wish to keep them in as they are very important for the EDR use cases.

If the links are very important for the EDR use cases, then the design of Part 2 is broken. There are no normative provisions for the links and the example links are not consistent with the architecture of the web. The links seems to be a convention that is basically unspecified and will not be understood by anyone outside of the core EDR group.

> "x-ogc-api-link" is an AsyncAPI object defined to be compatible with the OpenAPI link object. So we are changing the text to reflect this more clearly. 

As far as I can see, these links are unrelated to the [OpenAPI link object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#link-object). These look more like Web Links based on RFC 8288, but they are not compatible with the semantics of RFC 8288.

> OGC API-Common Part 1: Core states that link relations can be used that are not in IANA or OGC registers.

Yes, of course, but the examples use standard link relation types, but the links do not adhere to the semantics defined by the link relation types.

> We think we have now addressed your concerns in this issue.

No, but if you want to keep those sections in EDR Part 2, I am OK with closing this issue as long as there is no intent to propose such links in future OGC API Pub/Sub standards or any other OGC standard related to Pub/Sub.

**Comment by chris-little** [comment]
@tomkralidis @m-burgoyne @solson-nws @ShaneMill1 We need to discuss this. I would like to keep clemens ahppy and have something thing that is mainstream web rather than a WMO silo.
What are you views on closing this issue, recognizing that the generic OGC API-Pub/Sub may be different?

**Comment by m-burgoyne** [comment]
The AsyncAPI documentation has no concept of a Link object but as it follows similar conventions to OpenAPI it would make sense to use the OpenAPI link definition.  To achieve this, as a minimum the two fields that must be represented are:  **operationId** and **operationRef** where the **operationId**  should match the  **operationId** value for the HTTP request in the OpenAPI document for the EDR service and the **operationRef** is the URL for the HTTP request.

**Comment by chris-little** [comment]
@tomkralidis Any comments?

**Comment by tomkralidis** [comment]
The driving use case is being able to have a choice between polling or event driven for a given resource.

We have relaxed clause 8 to make Pub/Sub linkages in a given OGC API response model a permission, and have tried to add "links" to an AsyncAPI document as a result.

In the WMO environment, AsyncAPI is not a requirement for data publishers, so the thinking to express these relationships as "links" in OGC API - Records style Record core metadata (by also adding a `channel` property).

In the OGC context, AsyncAPI is in scope.  In any case, we would like to express a relation between a resource's Pub/Sub and API capabilities.  I'm not sure if AsyncAPI has such primitives, hence the `x-ogc-api-link` addition to a given channel definition.  If there are alternatives/better approaches that serve the use case, maybe we can draft some examples for review.

**Comment by cportele** [comment]
For links from OGC Web API resources to a Pub/Sub broker/server (clause 8), we would need a new link relation type that says that one can get notifications about changes to the current context from the referenced Pub/Sub resource (because no such link relation type exists yet AFAICT). The `channel` is an additional, optional hint. If `channel` is not understood, the server can still be investigated how to retrieve such notifications (which will depend on the technology used by the server).

For example:

```json
{
  "rel": "http://www.opengis.net/def/rel/ogc/1.0/pubsub",
  "title": "Data notifications for surface weather observations",
  "href": "mqtt://example.org:8883",
  "channel": "collections/surface-weather-observations"
}
```

The alternative option would be to not use web linking (RFC 8288), but dedicated Pub/Sub link objects, similar to what OpenAPI did with their link objects, but designed for link targets that are AsyncAPI channels.

The same options apply for the links from an AsyncAPI channel to the corresponding OGC Web API resource. Either web linking with a dedicated link relation type is used or the OpenAPI link object as proposed by @m-burgoyne.

One comment on that proposal:

> To achieve this, as a minimum the two fields that must be represented are: operationId and operationRef [...]

This would not be a valid OpenAPI link object, the two properties are mutually exclusive.

**Comment by m-burgoyne** [comment]
Currently the example is as follows:

```yaml
 x-ogc-api-link: 
     rel: collection
     type: application/json
     href: https://example.org/collections/wthr_stn
```
Is the proposal that it the AsyncAPI entry would be better as:

```yaml
x-ogc-api-link: 
     operationRef: https://example.org/collections/wthr_stn
     description: wthr_stn collections 
````

**Comment by chris-little** [comment]
@cportele @m-burgoyne @tomkralidis Short to midterm It would be good to only used defined links and structures. Longer term, it is probably cleaner to define a link type as suggested by @cportele that `notifications about changes to the current context from the referenced ... resource`, initially as an OGC link then later an IANA registered one. Is that a realistic roadmap?

**Comment by chris-little** [comment]
@cportele Can we close now? After the workflow fixes, this is the [latest / final version](https://docs.ogc.org/DRAFTS/23-057.html).

**Comment by cportele** [comment]
Yes, we can close this now.
