### ISSUE TITLE
Public Comment 1.6: "equivalent functionality" in /req/pubsub-channels/channels is unclear

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-environmental-data-retrieval#536]
EDR, Part 2, RFC version:

`/req/pubsub-channels/channels` mentions "channels that have equivalent API endpoint functionality", but it is unclear what "equivalent functionality" means. Should this be "channels that communicate changes to resources in an OGC Web API" or something similar?

**Comment by chris-little** [comment]
@cportele @tomkralidis Section 9.1.1 Req 2 will be changed to read "channels that communicate changes of resources in an OGC Web API".
