### ISSUE TITLE
Public Comment 1.7: Message payload requirements

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-environmental-data-retrieval#537]
EDR, Part 2, RFC version:

`/req/pubsub-message-payload/id` requires that a different id is used for the message than the identifier of the resource. Since `/req/pubsub-channels/channels` relates the channels to resources of the API, which all have IDs, another option would be to use the resource id also for the payload id. This approach seems more meaningful, for example, for features. The use in EDR Part 2 is fine, if it is not understood to be a general rule for Pub/Sub payloads of other OGC API resources.

Similar concerns will apply to the other requirements in the requirements class. For example, a feature may already have `pubtime` property.

**Comment by chris-little** [comment]
EDR API SWG115 agreed that not sharing `id` between payload and resource enables the distinguishing of multiple messages for one resource. This is a very common use case. For example, messages are issued updating the completion of an extensive resource. 

Another use case is where a recipient has been accidentally offline for several hours and is requresting a replay of a feed to 'catch-up'.

@cportele So, no change. Are you content that we close this as addressed?

**Comment by cportele** [comment]
@chris-little

Yes, if it is the general understanding that this is an EDR-specific requirement and not a general rule for OGC API PubSub payloads, then I am ok with closing it. 

In other cases, where the payload is a representation of a resource and not a  special message, there is no point in using a different feature id or to introduce reserved property names (like `pubtime`) that may clash with existing resource properties.

MQTT, for example, has the QoS mechanism to ensure that clients receive all messages (at least or exactly) once - even,  if they have been offline for a while.

**Comment by tomkralidis** [comment]
I've added a clarification to the recommendation in https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/commit/62f98e1e3edf6aded44cef6920813ddb2e8d6b13.  Let me know if this helps.

**Comment by cportele** [comment]
That helps, but only on the "id" aspect, not the other properties like "pubtime", which may conflict with existing resource properties. In addition, it should be possible to clearly distinguish in the representation properties of the resource and notification message metadata.

**Comment by tomkralidis** [comment]
We have reworked this Requirements class for a "Notification Message" requirement, and have removed FG-JSON specifics.  This means that anyone who wants to implement this requirement understands that the goal is to provide "notification" messages, which now steers clear of actual data payload specifics.  This keeps things sensible for EDR and generic enough to include in future status Pub/Sub efforts.

Update now pushed in #539.

**Comment by chris-little** [comment]
@cportele @tomkralidis awaiting a rendered version for review.

**Comment by chris-little** [comment]
@cportele We have created a rendered version at  [Part 2: PubSub](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/files/15263543/document.pdf) for your further review. Please let us know if we can close this issue, or raise new ones if something else spotted. We have removed references to pure data payloads. We have seen spelling mistakes, and the moving goal posts of Common Part 2 are being fixed.

**Comment by cportele** [comment]
@chris-little @tomkralidis 

There are a few inconsistencies or sentences that are unclear to me, other than that this looks fine now.

1. In 9.1.1, it says:

> `/collections/{collectionId}`: Notifies Subscribers whenever there is an update to a single collection resource (for example, spatial or temporal extents, new items, etc.). The message payload would be defined by the resource model of the given collection (items, etc.), or a message referencing the resource model of the collection.

I do not understand the second sentence. On `/collections/{collectionId}` I would expect messages about changes on the collection that impact the resource representation like a change in the extent or the item count, if that information is included in the resource representation. I would expect notifications about a new item, an updated item or a deleted item at `/collections/{collectionId}/items`.

2. In 10.1, it says (2nd paragraph):

> ..., the Message Payload Requirements Class provides further requirements for interoperability of message payloads as part of an OGC API implementation ecosystem.

This should be "..., the Notification Message Payload Requirements Class provides further requirements for interoperability of message payloads as part of an OGC API implementation ecosystem for use cases where unique message identifiers are essential."

3. In Recommendation 2 "resource_id" is used as a recommended property name. I think the convention discussed in the Naming Authority / Common was to use kebab case for query parameters and camel case for JSON keys. So this should be "resourceId".

4. I do not understand Permission 3. What does it add to Requirement 6?

**Comment by tomkralidis** [comment]
Addressed in #547

**Comment by chris-little** [comment]
@cportele We have made editorial changes at the EDR API SWG 118:
1. Clarified the distinction between message payloads that are actual changed data or notifications of change;
2. Changed. Thank you well spotted!
3. Changed to camelCase;
4. Removed Permission 3.

**Comment by cportele** [comment]
Thanks @chris-little.

Regarding item 1, I still think that the text and design is fuzzy. If the current text is ok for EDR, we can close the issue, in particular since this is just informative text and it has no impact on implementations. But for future OGC Pub/Sub standards we should agree that they should have clearer provisions and be more precise in their design.

**Comment by chris-little** [comment]
@cportele @tomkralidis Agreed - hopefully more implementation experiences may sharpen the EDR spec and contribute to the OGC Pub/Sub spec.
