### ISSUE TITLE
Can't find edr-geojson in the spec?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-environmental-data-retrieval#540]
I went searching for the edr-geojson schema and maybe I'm not looking in the right place, but it does not appear in the spec?

e.g. the content here:

https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/abstract_tests/edr-geojson/ATS_content.adoc

Does not appear here: https://docs.ogc.org/is/19-072/19-072.html ??

**Comment by chris-little** [comment]
@m-burgoyne discovered this:
Something odd is happening

=== Conformance Class Collections
=== Conformance Class GeoJSON
=== Conformance Class EDR GeoJSON
=== Conformance Class CoverageJSON
=== Conformance Class Queries

Are all defined in the raw ASCIIDOC but are missing in the HTML output

@ghobona @gbuehler Do you know why this is happening please?

**Comment by dblodgett-usgs** [comment]
https://schemas.opengis.net/ogcapi/edr/1.1/openapi/schemas/edr-geojson/edrFeatureCollectionGeoJSON.yaml is now available in https://docs.ogc.org/is/19-086r6/19-086r6.html#_81254e3a-d734-4195-ad15-ce64e208728c
