### ISSUE TITLE
Adherence of OGC API-EDR Part 2: Publish-Subscribe Workflow to OGC Web API Guidelines

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-environmental-data-retrieval#546]
The [OGC Web API guidelines](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/wiki/Compliance-to-OGC-Web-API-Guidelines) form needs filling in before any submission to the OGC Architecture Board for Review.
We did this for the original API-EDR V1.0, and we managed to avoid doing it for the OGC API-EDR Part 2: PubSub review, but I think we should do it anyway.
We can start with the our [original responses](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/ogc-web-api-guidelines-checklist.md).

**Comment by chris-little** [comment]
@ghobona If we put the WebAPI Guidelines forms in the Wiki, they can be editted without an audit trail. Shouldn't we put them as Markdown files in the Master branch of the repo?

There is already one for OGC API-EDR V1.0.

**Comment by ghobona** [comment]
@chris-little The wiki lists [revisions](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/wiki/Compliance-to-OGC-Web-API-Guidelines/_history) too.

You may use Markdown in the master repo as an alternative. Please do, however, add a link from the wiki page to the file in the master repo.

**Comment by chris-little** [comment]
@ghobona Forms added to the Repo and links from the Wiki also, in PR #548. Awaiting @tomkralidis to fill in fomr for Part 2 Pub-Sub.
The original form that we filled in for V1.0 had a check box for each Principle, as some Principles were not applicable. This was very easy to review. The current form requires all the comments to be read.
