### ISSUE TITLE
Metanorma failing with errors

### ISSUE THREAD

**Issue by gbuehler** [opengeospatial/ogcapi-environmental-data-retrieval#555]
Here are the errors I am getting on the Metanorma build:

Unresolved directive in ogcapi-environmental-data-retrieval/extensions/pubsub/standard/sections/annex-pubsub-notification-message-payload.adoc - include::../../examples/json/pubsub-message-payload.json[]
Unresolved directive in ogcapi-environmental-data-retrieval/extensions/pubsub/standard/sections/annex-pubsub-notification-message-payload.adoc - include::../../openapi/schemas/pubsub-message-payload-schema.yaml[]

It works when I change the lines to:

include::../examples/json/pubsub-message-payload.json[]

include::../openapi/schemas/pubsub-message-payload-schema.yaml[]

**Comment by tomkralidis** [comment]
Thanks @gbuehler.  PR in #556

**Comment by tomkralidis** [comment]
@gbuehler this was now implemented/pushed in master branch.  I am guessing we should have a build soon?
