### ISSUE TITLE
clarify bbox parameter requirement for cube/items queries

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#561]
The `bbox` query is **required** for the following query types:
- [cube](https://docs.ogc.org/is/19-086r6/19-086r6.html#_fe30ac95-7038-4dd1-902d-f4fcd2f31c8d)
- [items](https://docs.ogc.org/is/19-086r6/19-086r6.html#_81254e3a-d734-4195-ad15-ce64e208728c)

However, the bbox parameter definition shows `required: false`.

1. cube query: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/paths/queries/cube.yaml
2. items query: https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/paths/queries/items.yaml
3. bbox parameter (referenced by 1 and 2): https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/parameters/core/bbox.yaml

This yielded errors on EDR CITE against my pygeoapi instance (CITE is testing that the OpenAPI `.../cube` endpoint has a **required** bbox parameter).

If the bbox parameter is required for all of the queries it applies to, then the bbox [parameter definition](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/parameters/core/bbox.yaml
) needs to be updated (`required: true`).

Happy to PR if this is the intended behaviour.

**Comment by m-burgoyne** [comment]
@tomkralidis @chris-little I there will need to  be two different bbox definitions, the items query can still use the current  bbox [parameter definition](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/openapi/parameters/core/bbox.yaml
), but there needs to be a new definition for the cube query which has a required attribute of true

**Comment by tomkralidis** [comment]
@m-burgoyne looks like the items query has bbox as required as well?

https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/core/standard/requirements/edr/query_type/item.adoc

**Comment by m-burgoyne** [comment]
@tomkralidis That is an error in the document, the Items query bbox should be optional, so that document will need to be updated

**Comment by chris-little** [comment]
@tomkralidis @m-burgoyne Is this an error only in V1.1, to be addressed in V1.2, or do we need a V1.0.2 and/or a V1.1.1?

**Comment by m-burgoyne** [comment]
@chris-little  V1.0.2, V1.1.1 and v1.2
