### ISSUE TITLE
Clarification Needed for /locations Endpoint in OGC API - EDR Specification

### ISSUE THREAD

**Issue by webb-ben** [opengeospatial/ogcapi-environmental-data-retrieval#568]
I am seeking clarification on the usage of the `/locations` query in the OGC API - EDR specification. There seems to be ambiguity regarding whether the endpoint should support a RESTful pattern like /locations/{locationId} for accessing specific location data. This pattern is not explicitly mentioned in the documentation, which has led to confusion.

The current spec appears to suggest using `/locations?locationId={locationId}`, but this approach feels less intuitive and deviates from typical RESTful practices. Additionally, we're wondering if the `/locations` endpoint is intended to follow a similar pattern to the `/items` query, where specific items can be accessed via a direct path.

Could you clarify if `/locations/{locationId}` should be supported as part of the standard, similar to how /items queries work?

**Comment by m-burgoyne** [comment]
@webb-ben `/locations/{locationid}` is the correct usage for accessing specific location data.   `/locations?locationId={locationId}` is not a valid EDR locations query

**Comment by webb-ben** [comment]
I presume what is different about the locations query is that you can still filter by time and parameter?

i.e. `/locations/{locationId}?datetime=2020`?

**Comment by m-burgoyne** [comment]
Yes, that is correct.  The locations id is basically an identifier for a predefined set of spatial coordinates, and the user can define datetime, parameter-name, CRS and format as part of the request.

**Comment by dblodgett-usgs** [comment]
> The current spec appears to suggest using /locations?locationId={locationId}

Where do you see that in the spec?

**Comment by webb-ben** [comment]
When reading the [description about](https://docs.ogc.org/DRAFTS/19-086r7.html#rc_items-section) `/items`, it is clear there are more than paths in the URL pattern, one for requesting a `FeatureCollection`, and on that will return a `Feature`.

The [next section](https://docs.ogc.org/DRAFTS/19-086r7.html#rc_locations-section) on `/locations`, proceeds to acknowledge a similar behavior, but instead listing the additional URL path within the query structure table. This table it seems is otherwise only ever used to describe query arguments, except in the locations case. 

I understand it may be a bit more complicated than the OAF specification, because the single location at `/locations/{locationId}` still allows for those query parameters to be used in addition to the single item.

**Comment by webb-ben** [comment]
As a related/aside, as I update https://github.com/geopython/pygeoapi/pull/1776, is z a valid query paramter for locations?

**Comment by dblodgett-usgs** [comment]
> When reading the [description about](https://docs.ogc.org/DRAFTS/19-086r7.html#rc_items-section) `/items`, it is clear there are more than paths in the URL pattern, one for requesting a `FeatureCollection`, and on that will return a `Feature`.
> 
> The [next section](https://docs.ogc.org/DRAFTS/19-086r7.html#rc_locations-section) on `/locations`, proceeds to acknowledge a similar behavior, but instead listing the additional URL path within the query structure table. Table 13 seems to be the only table that implements path elements of a URL inside the query argument table.
> 
> I understand it may be a bit more complicated than the OAF specification, because the single location at `/locations/{locationId}` still allows for those query parameters to be used in addition to the single item.

I see -- yeah, `locationId` being listed as a query parameter in table 13 seems wrong, I agree..

**Comment by m-burgoyne** [comment]
The current EDR specification does not include a  z  query parameter for the locations query

**Comment by m-burgoyne** [comment]
@webb-ben  The expected URL pattern for location queries is `/locations/{locationId}`, resulting in `/locations/London,Paris,Washington`
