### ISSUE TITLE
Part 2: AsyncAPI example has some minor yaml syntax errors

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#569]
The following AsyncAPI example has some minor yaml syntax errors (e.g. a trailing colon and some indentation issues).

https://raw.githubusercontent.com/opengeospatial/ogcapi-environmental-data-retrieval/master/extensions/pubsub/standard/examples/yaml/asyncapi.yaml

Please fix the errors and let me know when it is fixed.

**Comment by tomkralidis** [comment]
PR in #570
