### ISSUE TITLE
Format of bbox in spatial extent object

### ISSUE THREAD

**Issue by lukas-phaf** [opengeospatial/ogcapi-environmental-data-retrieval#582]
[Section C6](https://docs.ogc.org/is/19-086r6/19-086r6.html#col-spatial) of the spec says that the `bbox` should be of type `Number Array`, but all examples in that spec, and the [schema](https://schemas.opengis.net/ogcapi/edr/1.1/openapi/schemas/collections/extent.yaml) show an array of array of numbers.

This is related to https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/331. Did the corresponding PR (https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/pull/339) just miss the change in section C6.

Or is the description in section C6 correct, and are the examples and the schema wrong?

**Comment by chris-little** [comment]
@lukas-phaf  The schema is generally considered normative and overrides the text, but we can ask @m-burgoyne to confirm that it is not a mistake in the schema.

**Comment by m-burgoyne** [comment]
@chris-little, Yes section C6 is incorrect and the schema is the correct representation

**Comment by m-burgoyne** [comment]
The text in section C6 has been corrected in  #577

**Comment by chris-little** [comment]
Addressed by PR #577
