### ISSUE TITLE
C 5 Extent object is missing custom dimension in documentation

### ISSUE THREAD

**Issue by mrauhala** [opengeospatial/ogcapi-environmental-data-retrieval#583]
Custom dimension is explained in 
https://docs.ogc.org/is/19-086r6/19-086r6.html#_a2113fbe-7d9d-4295-bdfa-25b9cc89fa03
and it states that it is located in Extent object.

However it is missing altogether in C5
https://docs.ogc.org/is/19-086r6/19-086r6.html#_2a2d533f-6efe-48df-8056-2eca9deb848f

**Comment by mrauhala** [comment]
It seems to be missing also from schema https://schemas.opengis.net/ogcapi/edr/1.1/openapi/schemas/collections/extent.yaml

**Comment by m-burgoyne** [comment]
Missing custom dimension documentation has been added to the changes in #577

**Comment by chris-little** [comment]
Addressed by PR#577
